### ISSUE TITLE
181745735 Download problem with hyphenated Civil Parishes (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#1001]
Issue reported by **johnt** at 2020-10-04 12:55:35 UTC
Time: 2020-10-04T12:49:57+00:00
Session ID: d1691d98ea7dd7ef4c7ac30958184d51
Problem Page URL: [/freecen_csv_files/my_own?locale=en](/freecen_csv_files/my_own?locale=en)
Previous Page URL: [https://test3.freecen.org.uk/csvfiles/5f797c07e93790274b5f2ede/edit?locale=en](https://test3.freecen.org.uk/csvfiles/5f797c07e93790274b5f2ede/edit?locale=en)
Reported Issue:
There is a problem within the download routine where there are hyphenated civil parishes such as  Beaumont-Chase. The load program handles this ok, but when you download the file there is no hyphen present, hence re-loading produces civil parish errors.    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen  can you confirm that the initial upload with a hyphen passes through OK

**Comment by Captainkirkdawson** [comment]
Looking down Rutland there is a similar issue for Edith Weston/Edith-Weston; Holt/Holt or Nevill Holt; Leigh-Field Forest/Leighfield; Market Overton/Market-Overton: There are a few others that may need consideration.
Perhaps we should write this as a separate story.
IMO the fist task  the initial setup of a county is to go through the Districts, Pieces and Civil Parishes to ensure consistency and linkage to Places

**Comment by geoffj-FUG** [comment]
Kirk, John
Whilst this is being considered should we throw in the Out of County Places as well?
If you look at Somerset you will find that Appledore is shown in Somerset in 1901, and only 1901. It is actually in Devon so is showing in the incorrect County. 
Similarly Bitton is in GLS but the Registration District was in Somerset from 1851-1911. 
These examples will also cause problems during searching.
I think that this background issue is now showing its true colours.
Maybe we need an additional field so that when the Coordinator is doing their review for hyphens etc they can enter the correct County. It could be prefilled with the County of the Reg District and the Coordinator just does a few edits. 
Geoff

**Comment by Captainkirkdawson** [comment]
@johnt-freecen @geoffj-FUG 
Have resolved the issue. The download was the symptom of an issue rather than the cause.
The cause was my old enemy titlieze (A ruby method) which drops the - for some reason best known to itself.
As you are aware CsvProc is case insensitive but for consistency and professional display we impose certain case controls. Rather than apply the case control whenever and wherever we display a field we store the field the way we want to display it. Hence in this case we were dropping the - on storage. 
To cut the long story short it is now resolved on test3.
Thank you for picking the issue up now.
You will have to reload the file with the - present to achieve consistent performance with your testing.
The matter of consistent Civil Parish naming does however remain to be addressed but that is a different story.

**Comment by johnt-freecen** [comment]
Hi Kirk,

I have just uploaded the file with the hyphens in place and then downloaded and they are present, so I think we can close the case.

Regards

John

Sent from Mail for Windows 10
