### ISSUE TITLE
Add birth place to search record so that we can sort results by birth place.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1010]
Requires a field to be added; to be populated by a) the transformer for both vld and csv and b) a one time rake task

**Comment by Captainkirkdawson** [comment]
Field added to search_record; rake task written to populate existing records; code added to csv transformation. Deployed to test3

**Comment by Captainkirkdawson** [comment]
populated CSV birth record field in search records for CSV Procon test3

**Comment by Captainkirkdawson** [comment]
Given the extensive time that would be required for this to run on the production system it would be better to add the code to the transformation code run as part of the monthly update.

**Comment by Captainkirkdawson** [comment]
Added to freecen1 vld translator as part of CEN2 code

**Comment by Captainkirkdawson** [comment]
Needs to be checked after a deployment and a freecen1 update

**Comment by geoffj-FUG** [comment]
Next update is due around the 16th November. Will test after this update is done.
Geoff

**Comment by geoffj-FUG** [comment]
This appears to work OK. I compared results on test3 with results on the live system and they were comparable.
I did one search where I simply searched for surname Jones born in BRK and census county BRK to see what sort of result I got. Naturally there were a lot of them.
Do we want to give the researcher the option of sorting them on the Birth Place so that the records for one Birth Place all appear together? It may help find the record that the resarcher needs to find instead of having similar Birth Places scattered in a long list.
Geoff

**Comment by Captainkirkdawson** [comment]
Need to review

**Comment by Captainkirkdawson** [comment]
Confirmed that the monthly update now adds the birth_place to the search record.
Now need to write a slow crawler to update all existing search records with the field.
Once that is done we can sort on that field

**Comment by geoffj-FUG** [comment]
Kirk

 

I presume from this that it is the birth_place you are searching on and not the verbatim_birth_place. Or is it verbatim_birth_place unless birth_place is populated?

 

There will be places that we have never found at validation. They usually have a note entry. The reason that I raise this is that there will be several thousand entries that will not match the Place Names database. In addition there will be many Place Names that exist but are not in the database. Often woods, hills etc that were very rural. They would have been validated as valid under the FC1 system because all we did was make sure that they existed somewhere. It was not as specific as FC2.

 

Will that affect the crawler results?

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG this has nothing to do with the search. Late in 2020 we added the display of an individuals birth place to the Search results page
![search results](https://user-images.githubusercontent.com/2874694/103708417-c9c39600-4f6d-11eb-9818-fd6422c1dd37.png)
For vld entries we look up the individual to get the information. For csv we add the information to the search record at incorporation. We use the alt POB if there else the Verbatim POB. Code had been added to the vld transformer to place the birth place in the search record. The crawler will simply look up the individual for a search record and add the birth place to the search record.
At that point in time we will be able to sort the display by Birth Place like the other columns.

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

Just sanity checking.

 

I understand now.

 

Geoff

**Comment by Captainkirkdawson** [comment]
After considering how to write an run a crawler to populate the birth place field realized there was a simpler way. When we retrieve the results of a search code is added to extract the birth place from the individual document if it is not in the search record. It then stores it in the search record for future use. This adds a short amount of time to the first search that retrieves the record for the first time but nothing thereafter. It therefore populates the field over time but only those records that are ever retrieved. 
The results ate then sortable by place of birth

Implemented on test3.
