### ISSUE TITLE
volunteer ID (for log on)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#104]
Volunteer can log on, and (minimum function) change password (further functions to be determined by other issues).
Data from existing spreadsheets uploaded.

**Comment by dougkdev** [comment]
Ability to create account and log on / change password should still be working.  However, I believe we should get #60 done before enabling the link since backups aren't performed on the test server.  Also, we should make sure coord accounts are set up first and associated with their respective counties before other volunteers.

**Comment by helhyde** [comment]
I agree with both points.



*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
As per correspondence with Pat, we are holding off on enabling the volunteer link until the Transcription Agreement is finalized.  Adding "needs info" label.

**Comment by dougkdev** [comment]
this story is now dependent on the system-wide volunteers gateway story.

**Comment by dougkdev** [comment]
Not dependent on volunteers gateway any more since that plan was postponed indefinitely several months ago. I believe this story can be closed as there is really nothing here that isn't part of other stories (#125, #118, #234)
