### ISSUE TITLE
Should WAL Country code  be permitted as a county of birth.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1059]
@geoffj-FUG 
While experimenting with the VLD downloader I have observed that files containing **Country Codes** for both Verbatim and Alternate County of Birth of WAL.
Clearly CEN1/2 permits this. CSVProc has this as an error. 

Do we continue to error it? Do we change CSVProc to accept it or produce a warning rather than an error?

It is not a valid chapman code

**Comment by geoffj-FUG** [comment]
Kirk

 

We shouldn’t be using Country codes. There is a standard list but we use only OVF and OVB. 

 

I asked that question when we started CSVProc and the answer was no change.

 

I suggest that they might have been early FC1 pieces when they would still have been experimenting.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Issue is the use of WAL as a chapman code rather than WLS

**Comment by geoffj-FUG** [comment]
WAL used to be rejected by either CSVCheck or Valdrev, (I am not sure which, maybe both). I have corrected it many times when it has cropped up when the piece was tested. So it has been accepted by a validator along the way even though there was a Warning against it. WAL is not in the original list of valid Chapman Codes from the early 2000s. I copied and pasted that original list from the documentation to get my list of Chapman Codes. 
We did not invent the Chapman Codes. They are a standard Genealogical list. See https://en.wikipedia.org/wiki/Chapman_code
If an open data researcher wants to join data between 2 databases they will not be looking for a Chapman Code of WAL because it is not in the standard set. 
WAL is someones invention, not a standard Chapman Code so in my opinion should not be used.
In addition http://home.vicnet.net.au/~mgfhs/chworld.htm shows that WAL is allocated to German Old Empire | Waldeck | WAL

**Comment by FreecenBren** [comment]
Quite a few of the Welsh Census often say just Wales and no County.
Probably because of the spelling of many POB’s.
 The enumerator went for the easiest.

CSVCHECK accepts WLS but rejects WAL as Geoff says.

**Comment by Captainkirkdawson** [comment]
@FreecenBren @geoffj-FUG I am sorry to have to tell you that RG121953.VLD (a SOM file) contains WAL as a Chapman Code on CEN2 so something is not right somewhere

**Comment by geoffj-FUG** [comment]
Kirk
I immediately know who transcribed that. I used to do a replace all on his spreadsheets. I must have missed one. Not sure why it validated though.
Mea Culpa
Geoff

**Comment by Captainkirkdawson** [comment]
No problem; just needed to ensure we were not missing something; looks like Valdrev does not check.

Will close
