### ISSUE TITLE
Allow searching by title 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1064]
A search for CHANDOS Duke finds the Duke of Buckingham, family name Chandos (in Haddenham, Buckinghamshire).
Searching _just_ by title (e.g. Duke of Buckingham, Reverend, Sir is only permitted in a specified county and place
A search for DUKE in Haddenham, Buckinghamshire finds him.
A search for Rev or Rev. or Reverend can be made but a search for Rev. in Fotheringhay, Northamptonshire started to run and then generated an error report.  Repeating in Aswardhurn, Lincolnshire 1841 found two vicars!  Edward The Rev C and Rev Granvel MENTEATH.  Repeating with Rev* in York, East Riding 1871 again timed out and produced an error.

Suggest adding common title abbreviations to the aliases of forenames (e.g. Rev, Rev.., Reverend) and Dr, Dr., Doctor).

**Comment by Captainkirkdawson** [comment]
There is no such field as title. 
The only field is the forename and it is the one you are using . 
If the forename has a title as a component of the forename then it will already be retrievable since we index and search by each of the forenames in the field. 
Do not believe we ever entered abbreviations for title names
Timeouts are frequent on wildcard searches which is why the wildcard augmentation of mongo is of interest

**Comment by PatReynolds** [comment]
emendation is the only thing left - @Pat to add that story number to the roadmap and close this.

**Comment by PatReynolds** [comment]
Could not find existing story, so created #1088 and clsing
