### ISSUE TITLE
Promulgate an entry in the notes field

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1085]
John Toplis has suggested:
It would be a nice enhancement if we could be offered the chance to promulgate an entry in the notes field. I am  just validating a 9,000+ piece and there quite a few entries for "Kibworth” I am entering that it could be either “Kibworth Beauchamp or Kibworth Harcourt”

**Comment by Captainkirkdawson** [comment]
Initial reaction was 
If it applies to the same POB that is being promulgated it is doable

**Comment by Captainkirkdawson** [comment]
Geoff  supported
John’s enhancement sounds good. I can see it saving the Validator a lot of work. It should be a separate action to Promulgating the POB and should be able to be actioned when there are no notes and the POB fields match. The flags should change so that it gets validated when the recurrences occur.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
It is possible to promulgate the note added when an alternate POB is added for an entry as part of that promulgation. 
It is also possible to promulgate the note added to an entry to other entries with the same POB 
It would be one or the other that gets offered NOT both

**Comment by PatReynolds** [comment]
@geoffj-FUG could you comment on this, please?

**Comment by geoffj-FUG** [comment]
The test should simply be Has the Notes changed?
Promulgate Notes should copy the notes into every record that has the same Verbatim Chapman Code and Verbatim Place of Birth and where the existing notes are null. It should not be dependant on an alternative entry.
The purpose is to promulgate information where an entry such as Newton Devon is enumerated. Now we have the space we can suggest all 6 Newtons in Notes and promulgate them to every record that has a verbatim POB of Newton Devon. If you get a lazy enumerator there can be a lot of them in a piece.
Geoff

**Comment by AlOneill** [comment]
But, there could be more than Place suggestions in the Notes field. Can we separate the parts without losing information or adding anything irrelevant? (I hope so!)

**Comment by geoffj-FUG** [comment]
Alison
The Promulgation will be an Action that the validator chooses to either do or not do. This is already the case with alternative POBs at the moment.
My Place suggestion was an example. But the promulgation will be dependant on the verbaitim place of birth otherwise we have no way of controlling it.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  @johnt-freecen Have added the notes propagation to test3 for testing

**Comment by geoffj-FUG** [comment]
Tested and appears to work OK. 
I note that the buttons stay when both the alternative place of birth and notes are entered. I was able to promulgate them one by one but was not sure whether they had worked or not as there was no message. Having said that I did keep receiving proxy server fault messages so that may have had an impact.
Maybe we shoud have either an extra button that promulgates both fields, or a screen message that says one or the other field has been promilgated so that the ambiguity is removed. 
The proxy server really slowed everything down during this test.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
There are messages at the end of the promulgation of both fields; as you say the proxy error likely caused issues. 
Likely best to retest. 
propagation is separate actions by design as one may succeed and the other may not and if we combined could get into a mess in that case.
If there is already a note on one of the entries being propagated to then we concatenate the messages.

**Comment by geoffj-FUG** [comment]
I have now completed the validation of a piece with repetitive entries. I promulgated everything and had no issues.
Works well
Geoff
