### ISSUE TITLE
189963661 missing parish (Kirk)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1100]
Issue reported by **Captkirk** at 2021-01-07 15:41:01 UTC
Time: 2021-01-07T15:38:12+00:00
Session ID: e0a712c8a93c59b38ac52dee70dd0459
Problem Page URL: [/feedbacks](/feedbacks)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
One of my transcribers has an error report. I am looking at RG13_2286 Entry 991. It is an ED transition

 

The reported Error is Line 991 Civil Parish Pawlett Is Not In The List Of Civil Parishes.

 

The file information says

 

Enumeration Districts

{"Bawdrip"=>["1"], "Puriton"=>["2", "0#8"], "Pawlett"=>["3"], "Huntspill"=>["4", "5", "6", "0#8"], "Woolavington"=>["7"], "Cossington"=>["7"], "Chedzoy"=>["8"], "Moorlinch"=>["9"], "Chilton On Polden"=>["10"], "Stawell"=>["11"], "Sutton Mallet"=>["11"], "Edington"=>["12"], "Catcott"=>["13"], "Shapwick"=>["14"], "Greinton"=>["15"], "Ashcott"=>["16"]}

 

So the Civil Parish and ED number look OK.

 

Pawlett SOM is in the Place Names Database.

 

What am I missing? It looks right to me but is producing an error report.    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG clearly the EDS are not alright "Puriton"=>["2", "0#8"],  Huntspill"=>["4", "5", "6", "0#8"]. Further research is required

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG research is required, may take a day or 2

**Comment by Captainkirkdawson** [comment]
this looks dangerous
![worrisome.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/57745b46-b0ad-488e-8ba1-b2e349b978b2)

**Comment by geoffj-FUG** [comment]
Kirk
I have asked for this to be fixed. I will add a note against each field in the Handbook.

I still cannot see why the Civil Parish should not match Pawlett.

PS I did not refer Chilton on Polden to you as I have added it as an Other Place Name in the Gazetteer. I have asked him to retest that one.

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
It is because Pawlett is spelt Powlett in 1901 parms for that Piece
![2286.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/45523256-0cf3-4677-894e-e607cee31cd9)
Doing a fill index civil parish csv for Somerset shows it missing and where it is.
![pawlett.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5bb2aa6d-ac09-446e-9b7e-8f6c35793c9e)
![powlett.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8215b8ff-6403-46ab-aa47-a113033a8af4)
This shows that Somerset still needs lots of work to clean up spelling mistakes
@rhodamackenzie 
It also shows the importance of the coordinators downloading and reviewing the fill index CSV displays and once cleaned up keeping a copy to hand

**Comment by geoffj-FUG** [comment]
Thanks Kirk
I couldn't see that. A case of wood and trees.
The spreadsheet is going to be a big help in this. It is easier to read.
Geoff
