### ISSUE TITLE
add google-site-verification meta content in application.html.erb

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#111]
Do we have an app-specific key to use for freecen?  This meta tag is used for site verification for webmaster tools, etc.  There are other ways of verifying site ownership, so I don't know if we need this or if we already verified using a different method, but there is a key for FreeReg so I wondered if we need to go ahead and add one for FreeCen.

**Comment by richpomfret** [comment]
Potential task for Chee. May not be necessary. To investigate.

**Comment by PatReynolds** [comment]
Lemon may know.

**Comment by PatReynolds** [comment]
Pat to contact Lemon

**Comment by AlexAvlonitis** [comment]
I don't have access (or links) to google web master tools yet. Is this about the .html page you create with the google ID for verification?

**Comment by richpomfret** [comment]
To also consider applying google analytics (separate story perhaps).

**Comment by richpomfret** [comment]
Added Israel/Lemon to investigate this task further. There's also a separate story now for adding google analytics..

**Comment by israelriibeiro** [comment]
Hi, @dougkdev . 

I found two ways of veriying a website ownership. First: google webmaster, as you said. And bing, microsoft search engine. I believe that google webmaster tools is enough. 

To add this key, each website has to have its own keys: 
There are many ways of adding this keys, one of them, as you said, is adding the key in html tag.
In this website they describe what you have to do in order to get this done.

https://support.google.com/webmasters/answer/35179?hl=en

Bing:

https://www.bing.com/webmaster/help/how-to-verify-ownership-of-your-site-afcfefc6

@lemon-ukgen , did you find another way of verifying a website ownership?!

**Comment by lemon-ukgen** [comment]
On 12/02/2017 06:22 AEDT Israel Borges wrote:
>
> @lemon-ukgen , did you find another way of verifying a website ownership?!
>

I don't mind which we use (`TXT` DNS record is easiest for me) but
someone needs to log into the Google Webmaster Tools account we're going
to hook up, generate the verification token and pass it on to me or
Israel to publish.

It's likely best to use the same account as FreeCEN Google Analytics,
which is mentioned above.

So... is there a Google Webmaster Tools account already setup somewhere?
Who has access? Or shall I create a new one?

**Comment by dougkdev** [comment]
In application.html.erb there is a verification key in the <head> section:
<meta name="google-site-verification" content="zAYAee-PuoiMAfi5hbUreeLsvTGf4XFNXDxMDB9PcCQ" >

 I do not have access to the analytics or webmaster tools, so I don't know how (or if) you all have set up the analytics and verification for FreeCen 2.  I was just wondering if we need to add a separate verification key to application.html.erb that is specific to FreeCen2.  That all depends on how whoever has set up the verification set it up. It is a simple one-line change in the code, but somebody who has access to the analytics/ webmaster tools would need to tell one of us developers what verification key to use instead of "zAYAee-PuoiMAfi5hbUreeLsvTGf4XFNXDxMDB9PcCQ" if you don't want us using the same key that is used for FreeReg.

**Comment by dougkdev** [comment]
There is already a separate analytics tracking code (UA-71283391-1) for FreeCen2 in application.html.erb , we just need to know if we also need a separate google-site-verification key, and if so, what that key is.

**Comment by richpomfret** [comment]
@lemon-ukgen Restarting this issue so we can see if it's still valid or not. I can give you access to FreeCen analytics if you need and we can get this story moving or close if applicable? I am currently checking to see if we have a Google Webmaster tools account.

**Comment by smrr723** [comment]
I've created a Webmaster Tools account (now called Google Search Console) and added FC2 and FC2 Test2.  Added you as another user @richpomfret - https://www.google.com/webmasters/tools/home?hl=en

I was doing this as part of Issue #511 in order to update our robots.txt file, and add a sitemap for FC2.
