### ISSUE TITLE
Coordinators or System administrator  can add transcriber information to a VLD file 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1127]
E3 C3 S7 C5:  P18

**Comment by Captainkirkdawson** [comment]
Need to add transcribed_by_person_surname,  transcribed_by_person_forname, transcribed_by_person_email address and transcribed_by_userid fields to freecen1_vld_file; 
add edit action to the show. restricted to county and master county coordinators, data  and system administrator
the edit form to have the new fields
The update needs to strip whitespace, name and email address are mandatory. Need to check that the userid is valid.

**Comment by AnneV-Learn** [comment]
Hi Kirk,

When you get a spare moment can you give me a bit more information on this one please.

Questions I have at the moment are:
What is a VLD file?
Does this assignment process already exist (eg transferring a csv file)?
Does Tech include Data Administrator and System Admin?
How is the transcriber of a file identified (ie it’s transcriber)?

Bye for now
Anne

**Comment by Captainkirkdawson** [comment]
Renamed to clarify scope and make consistent with description.

A VLD file is a FC1 file created by the validator of the file originally transcribed for FC1 (You may be sorry you asked; https://west-penwith.org.uk/fctools/doc/reference.html )

Files are sent by coordinators to Brenda who passes them to the person who runs the monthly update of FC1. The vld file gets into Freecen2 by a monthly transfer of files.   There is no information on who produced the file.

The transcriber information is entered by the person entering the data ie there is no look up it is a simple data entry

![vld access.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/963b24e5-eadf-4069-a6e2-0d979de0606d)

**Comment by AnneV-Learn** [comment]
Hi Kirk,

Still trying to get my head around this.

Is there user documentation for this process? (It will probably help me to better understand the flow and how the different files in the link you provided are used.)
I have looked on the old FREECEN website and followed some of the routes to documentation but it is not make a lot of sense to me - I have only been involved in transcription and have no knowledge of the processes after that for the old system.

I will want to be able I have a VLD file in my local app so that I can eventually test any code.

In the link you provided the transcriber info appears in the ctyPARMS - file is this what we are talking about?

[cid:C195344D-880E-4F6A-B762-DEF44ADBF0CE@home]


What is the ultimate purpose of allowing CO-ORDs and SYS ADMINs to add Transcriber info - where will it ‘go’ after that?
Do we need to have to actually modify the VLD file or can we just have a link object that holds the VLD file identifer and the transcriber details which the CO_ORDs and SYS-ADMINS can populate/update?

Probably way off the mark here and we may need to ‘meet’  to bring me fully up to speed.

Bye for now,
Anne

**Comment by Captainkirkdawson** [comment]
Will reply off line
