### ISSUE TITLE
Update the civil parishes list for 1911 to eliminate the second parish if it has more than a single word and inserts 'needs review'

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1131]

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
I cannot do as planned since there is no specific order for the entries. 

I will have to say needs review in all cases where there are 2 or more civil parishes listed

**Comment by Captainkirkdawson** [comment]
Completed the processing of 1911; Only 10% of the pieces were affected.

The list of 47 pieces that might or might not have a problem with the civil parish name and had files attached and therefore need to be checked. Only those with a problem need action Sent off line to @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Kirk

Have checked all these 1911 Parishes against the pieces.

It was interesting. The rubbish place names had disappeared and the good ones are on the list. That is because the good place names had entries but the spurious ones did not, despite being in the same piece.

None of the 1911 entries in the text file need action.

Geoff

**Comment by Captainkirkdawson** [comment]
That is likely a result of the first test on any civil parish being to do nothing other than report if there were transcriptions made for the parish.

**Comment by PatReynolds** [comment]
Thank you both, is anything more needed, if not please close @Captainkirkdawson or @geoffj-FUG
