### ISSUE TITLE
194111791 Problem linking Saltfleetby All Saints (John)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1168]
Issue reported by **johnt** at 2021-02-24 15:56:31 UTC
Time: 2021-02-24T15:53:28+00:00
Session ID: 56665411489a24ef64112538b9b04b03
Problem Page URL: [/freecen2_civil_parishes/5fc7c6ddf4040b5f994c1ff0?locale=en](/freecen2_civil_parishes/5fc7c6ddf4040b5f994c1ff0?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_civil_parishes/chapman_year_index?chapman_code=LIN&locale=en&year=1841](https://www.freecen.org.uk/freecen2_civil_parishes/chapman_year_index?chapman_code=LIN&locale=en&year=1841)
Reported Issue:
I am attempting to add the place name Saltfleetby All Saints to the 1841 civil parish of the same name. The screen returns update successful, but on viewing the screen it displays the place name as blank. This also happens with Toynton All Saints.    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
For some reason, currently unknown the standard place name was not corrected; it was the place name. Hence no match was found. Have added code to notify the member of the reason for a failure and described it as such. There was previously no such check or message it was assumed that since we were displaying the name it would always be found. Rule 2 is never assume anything!!. Code has been deployed to production and the place name corrected to have the correct standard name and the connection made to the civil parish.
I have located other similar incorrect standard names and will correct those.
As stated earlier why they are incorrect is unknown.
