### ISSUE TITLE
Statistics do not include uploads as expected

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1169]
https://www.freecen.org.uk/userid_details/transcriber_statistics does not seem to be displaying the number of transcribers who have uploaded to CSVProc.

**Comment by Captainkirkdawson** [comment]
That's because it has yet to be coded; It is part of the work on #1076 and #1135 
Transcriber statistics for FreeCEN have never been accumulated as part of the FC1 operations

**Comment by PatReynolds** [comment]
Thanks, @Captainkirkdawson.  It will be lovely to have more transparency.

**Comment by Captainkirkdawson** [comment]
This![Freecen member statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/94f7dc87-02d9-44db-beb6-ad90151138a5) is a copy of the first report.

You will see that we have had 104 new transcriber volunteers in the past 3 months. This is why we need to have a volunteer coordinator

The other block shows the number active on FreeCEN2 since the launch of CSVProc on 1 December 2020; just 3 months ago. One of the reasons  for the number active since then is firstly all new registrants will have been included and I expect some other transcribers will have looked at the site.

The number of people to have uploaded files is extremely encouraging at 30 transcribers and 11 coordinators and others.
