### ISSUE TITLE
CHI PARMS issues

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1180]
I have started on the CHI PARMS. I need to restructure them.
I wish to establish the structure
District - Channel Islands
Piece - Island
Civil Parish - Civil Parish.

That is for 2 reasons. It aligns with our 3 levels in the Chapman Codes but more importantly it is the researchers three most obvious search paramenters. (If they are not in the parish, look on the Island. If they are not on the Islands look at all teh Islands).

To do this I need to do it in steps
Change all the Districts to Channel Islands (Chapman Code CHI) - Rhoda I have sent the spreadsheet to you for these changes. That fixes the District level.
Allow the Chapman Codes of ALD, GSY, JSY and SRK to be visible from the CHI Chapman Code. Then I can link Alderney for instance to Alderney. In most years it is stuck in with the Guernsey pieces. Kirk - This is similar to the HAM / IOW problem that is holding up HAM PARMS.
Once this is done I can link the Pieces correctly and then the Civil Parishes correctly.

Geoff

**Comment by FreecenBren** [comment]
Hi Geoff,

Just an update.

We only have the 1861 & 1891 for CHI.

1861  : JSY x 3 to PR  and 5 to validate 1 to transcribe and GSY  is all
complete.

1891 :  JSY x 5 to PR  : 3 to Validate  3 to transcribe
1891   : GSY x 3 to Validate.

Sark and Alderney images are either none or were lost at the time as per NA.

We have no helpers at all for the CHI at the moment.
Therefore no movement.

IOM :  very similar but also no helpers
1851 : 4 to PR but no images. Donated CSV
1861 : 1 to Validate. 17 pieces but no images.
1891 : 11 pieces all the images on microfiche for Helen to digitise when
needed.

Cheers. Brenda

**Comment by geoffj-FUG** [comment]
Thanks Brenda

 

The FC2 PARMS has to be done whether we have images or not. Then the researchers searches will work properly.

 

Geoff

**Comment by geoffj-FUG** [comment]
Step 1 done by Rhoda
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I am totally and utterly confused about what is happening with CHI.

Last week I was asked to remove the 1841 IOM , Guernsey and Jersey parms and put them in their respective counties. Story 1178. In 1841 IOM , Guernsey and Jersey are located in the Channel Islands. This I did as an urgent action

On on the 14th it appears that you want to move JSY and GSY back into CHI for all years and that @rhodamackenzie has done that.

There are no Freecen2Places for CHI they are with JSY GSY and ALD.

Talk about confused.

**Comment by FreecenBren** [comment]
I too am confused.

All the Alderney, Jersey and Guernsey so far in FC1 are all in CHI.
I am having validated the last few and they will all get uploaded in FC1
the same in CHI.

When I do the next FC1 upload at the end of the month and I do manage to
get any CHI  Validated  VLD’s uploaded, when Vino does the FC2 upload for
us from FC1 where will the CHI VLD’s go to in FC2, or will they end up in
the FreeCEN Two error folder till FC2 is sorted out.

So can someone decide where the current CHI in FC1 will go in FC2 and also
those I have left to upload in the future.

Just confused.

We only have the PARMS in FC1 under CHI and do not use JSY  nor  GSY etc.
So will  they fit into FC2 now CHI has been taken out.

Brenda

**Comment by Captainkirkdawson** [comment]
Brenda

Not sure where your confusion really comes from.

Anything coming into Freecen2 from FC1 knows nothing about CSVProc or the
Freecen2 Districts/Pieces or Civil Parishes.

What happens to files from FC1 is based solely on your traditional Parms.
Just as it has been for the past 3 years. Nothing has changed. So you have
nothing to be concerned about at this time.

Kirk Dawson
Fairmont, B.C. Canada

>
>

**Comment by geoffj-FUG** [comment]
Kirk

 

The TNA index treats the Channel Islands in different ways in different years. My first attempt was aimed at linking as is. This meant that when they changed their model our PARMS would not be consistent across the years. That means the our researcher searching would not be consistent.

 

It struck me that to get consistent search results we would need to have all of the Channel Islands under one County Code - CHI. This is level 1 in the hierarchy that we have established for Chapman Codes. It is also the structure that was used in FC1. 

So I am going to establish one District – Channel Islands

At the sub-District level I can establish an island basis for the PARMS. This is also a good search level for researchers.

At the third level will be the civil-parishes as is standard throughout.

 

This model is consistent with the model within Counties, except that Counties have several RDs.

 

I know I changed but it was during linking that I discovered that TNA sometimes had Islands as a civil parish and sometimes as a piece or as an RD.

 

I am just trying to establish a consistent model.

 

It means that the CHI Coordinator must be able to see the parishes within the ALD, GSY, JSY and SRK Chapman Codes.

 

Geoff

**Comment by FreecenBren** [comment]
Thanks Geoff,

That makes sense.
 Brenda

**Comment by Captainkirkdawson** [comment]
Thank you @geoffj-FUG 
I agree that TNA catalogues that are the basis for our fleshing out our many of our collections change according to the census year.
For 1841-1861 TNA uses in essence the Channel Islands. I say in essence because IOM is included in the Channel Islands in 1841. For 1871 onwards they Islands are treated separately.
However whatever we do has to consistently fit within our data model. Our data model is Country/County/Place/District/Sub District (piece)/Civil Parish. Almost all of this comes from TNA except Place which comes from our own collection perhaps I should call it our gazetteer. 
In the initial setup we viewed the channel Islands as separate counties and set up the Gazetteer that way. In that set up the Channel Islands does not exist from a data perspective. Although it can be constructed by a merge of the counties in the the Channel Islands. We placed 1851 and 1861 into this structure as well leaving 1841 in the Channel Islands. We also have county and syndicates set up for the various island counties. 
In this set up FC2 would be different from FC1 which only deals with The Channel Islands. Other search engines use the Channel Islands.
A factor to remember is that the Channel Islands only had a population of 100,000 up to and including 1911.
Last week I made the 1841 census fit within that that structure and at that point we were fully consistent with the individual island counties and nothing in the Channel Islands (CHI)
Based on your comments of this past weekend and the movement of all the Islands into the Channel Islands you wish to revert to to a Channel Islands structure. I have no opinion either way. 
What I do have is a very strong interest in ensuring our data model remains consistent. **To complete the change we should integrate the individual islands into the Channel Islands for our Gazetteer.** Since there is currently no such county
**We should also remove the individual islands from the counties and syndicates lists.**
With respect to naming 
 **I believe the District name should remain the Island name as it is now i.e. Jersey etc** 
The sub district is more difficult as here TNA was really inconsistent. Over the years they changed from the island name, to A B C etc in 881 and 1891, then back again to the island name in 1901 and in 1911 they left it blank so we inserted the island name. **I believe the sub District name should be the Island name.** This makes for a bit of handful for 1911 since there is a piece for every ED
**The civil parish names are fine as is.** (Although the full list crashes likely due to the method of creation. Story #1183 raised and will be dealt with once an agreed path forward exists)
**How do you wish to proceed?** It will take a couple of hrs to restructure the gazetteer and then I can leave the rest to you and @rhodamackenzie to edit names and make the links. Alternatively in addition I can take a few hours and tweak the original xml input to fit what we want in naming and replace the CHI collections. Doing so would make the place name linkages at the time of creation.

**Comment by geoffj-FUG** [comment]
Kirk

I have had a long think about this. I have now looked at the problem from a different perspective. I previously only considered it from a search results perspective.

Channel Islands is a level 1 Chapman Code in the FC2 table of Chapman Codes. Under normal circumstances we do not attach place names to a level 1 code. It equates with ENG, SCT and IRL. We have identified the Codes of JSY, GSY, ALD and SRK as the level 3 Chapman Codes to attach places to. 

This principle is based on making validation work. In validation we force the Island name to be entered as the alternative County when the County Chapman Code has been entered as CHI. Integrating the Islands into CHI would stop auto-validation. So that options is not practical.

The Gazetteer has to align with the model or validation of POBs will not work.

So I have to agree that I erred and the District name and the County Name should be the Island, but I suggest that they be limited to GSY and JSY (the Bailliwicks). TNA seem to have used the Bailliwick model in most of their years. 

Wikipedia tells us that

“Alderney is the northernmost of the inhabited Channel Islands. It is part of the Bailiwick of Guernsey,” 

Sark – “It is a royal  fief, which forms part of the  Bailiwick of Guernsey, “

That means that the Island name (including Alderney, Herm etc where applicable) will often be the piece name and the civil parish the civil parish name.

What is the impact of this model please?

Geoff

**Comment by Captainkirkdawson** [comment]
In my opinion we should, under the Channel Islands, have 2 districts  Jersey and Guernsey ( The 2 bailiwicks). Within those districts we have pieces for the parts of the specific bailiwicks all of which fall within Guernsey  since I understand there are no inhabited islands within the  bailiwick of Jersey.
All of the place names are to become part of the Channel Islands
With respect to validation we can adopt the following the County of Birth can be CHI, GSY, JSY, ALD, SRK. Any place will be validated against the place name contents of CHI

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG If this is the way you wish to go it will take a day to restructure the place names and upload the new structure for CHI

**Comment by geoffj-FUG** [comment]
Kirk

 

I can run with that.

 

It is the same model as we are using for IOW and the Ridings.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Actions needed: 
1)Copy places for ALD (1), GSY, FSY, SRK to CHI on both test3 and production
2)Modify/Create xml for ALD, GSY, FSY, SRK and CHI to create Districts and pieces with appropriate names for each census year in CHI
3)Remove districts/piece and parishes from CHI. (There are none for ALD, GSY JSY) on test3
4)Upload and process CHI xml for each year on test3.
5) Confirm all OK on test3
6)Remove districts/piece and parishes from CHI. (There are none for ALD, GSY JSY) on production
7)Upload and process CHI xml for each year on production.

**Comment by Captainkirkdawson** [comment]
Codes all written and tested. Production cleaned up and ready for creation of CHI tomorrow

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @rhodamackenzie 
CHI recreated according to the agreed design

**Comment by geoffj-FUG** [comment]
Thanks Kirk
Linking almost completed. This story can be closed.
Geoff
