### ISSUE TITLE
195651420 Over - a place name in Cambridgeshire (Michael)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1181]
Issue reported by **MikeS** at 2021-03-14 11:37:00 UTC
Time: 2021-03-14T11:25:36+00:00
Session ID: cf207ad3cd1570b04327f8f42fc1ed57
Problem Page URL: [/freecen2_places?locale=en](/freecen2_places?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/new?locale=en&name=Over](https://www.freecen.org.uk/freecen2_places/new?locale=en&name=Over)
Reported Issue:
I have screenshots as follows but can only send No.5:
1. Searched for Over in Cambridgeshire
2. Message "No such names"
3. Found the entry in Gazeteer with Grid Ref
4top & 4bottom. Entered the County, name, Grid Ref and Source
5. Message "Unsuccessful. Active place with that name"
I can send the others if necessary.
MikeS
https://www.freecen.org.uk/uploads/feedback/screenshot/604df55cf493fd510644a1cb/Over_CAM_Search___Create_5.jpg    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
The Place name is there which is why it cannot be added.
All of the advanced place name search find the entries (There are 2)
@AnneV-Learn has identified the cause cause; https://stackoverflow.com/questions/49171693/disable-stop-word-filtering-in-a-mongodb-text-search
Put simply the text index does not index certain common words (Predominantly those possessive and connective words) and they are dependant on language. examples:  is isn't it it's its itself of on only over. There are 174 for English.
See https://github.com/mongodb/mongo/blob/0e3b3ca8480ddddf5d0105d11a94bd4698335312/src/mongo/db/fts/stop_words_english.txt for the full list
There are several possible actions.
1. Do nothing. There are few if any other words in the list that are likely to be place names.
2. Add a footnote about stop words that are not indexed with a link to a page with them listed
3. Add a footnote suggesting people used the advanced search options if they do not get places returned
4. Do 2 and 3
5. Rebuild the text index with no language so that all words are indexed. Simple to do but could lead to an increase in false results.

**Comment by AnneV-Learn** [comment]
A disadvantage of taking option 5 above is that we would lose ‘stemming’ I believe.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Your opinion please. Mike agrees with option 4

**Comment by geoffj-FUG** [comment]
Kirk
My brother lives there so I know it exists.
Option 4 sounds goo to me.
Geoff

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn Change looks fine. Lets do a merge and then deploy to the test3 server

**Comment by AnneV-Learn** [comment]
Deployed to Test3
