### ISSUE TITLE
Develop a plan for the future of the Records displays

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1194]
Review the FreeREG approach and perhaps the FreeBMD2 approach if developed (talk to vino) and look at the old FreeBMD approach. Develop an overall plan for how to build the system from a top down perspective.

**Comment by rhodamackenzie** [comment]
Looks good apart from typos in button (I realise these is a rough draft!). I like the “added in last 30 days”. 
I would have percentages available for all the county and district level pages, do we need percentage graphs too over time? I don’t think so myself. I guess could have a pie chart with the percentage rather than a graph through time. 
For results table in each section, I would put number online first, then total number rather than the other way round, makes the percentages look more sensible. Have a think about how many decimal to put in percentages, I think one decimal place, max 2. 
 
The unique names section is very exciting, could this be done for whole UK and county too (even just for surnames)? My tail is wagging just thinking about having that.

**Comment by AnneV-Learn** [comment]
I've updated the draft page designs to reflect Rhoda's comments.
Regarding pie charts - I propose that we introduce those in a second phase of development, so that we get the basic data out there first. 
[RecordsPageDesign I3.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/6277308/RecordsPageDesign.I3.pdf)

**Comment by rhodamackenzie** [comment]
Anne, 
Just to check, for the unique names - is that possible at all levels? ie Full dataset, county, piece, parish?

**Comment by AnneV-Learn** [comment]
I’ve added a Unique Names button in the draft design at all levels, except parish. I’m starting to investigate more fully what is actually available. If do-able, I’ll update.

**Comment by AnneV-Learn** [comment]
I have been looking at the data sources for this story to work out what is actually possible. Updated Excel file is attached (has data source tab). 
Having passed initial ideas by Kirk here is a summary of thoughts so far: 

1. The outline page designs need to be reviewed and agreed. 
2. Providing Records data at the Parish level probably needs to be put off until we can hopefully find a way of integrating the VLD based input into a a common structure. (After Freecen1 updating has been switched off.)
3. The level to which we can provide 'Unique Names' (and would actually be useful) needs further investigation and performance testing. 
4. A suggested phased implementation plan is as follows:
  a. Implement changes to Freecen1 and Freecen2 so that all pieces have a process to set status field to 'Online' and populate an Online_date field. (see #1202 for freecen2 - need new story for freecen1?)
 b. Develop new Records pages (excluding Parish data, unique names and charts). 
 c. Develop unique names capability at Piece level. 
 d. Develop charts. 
 e. Investigate capabilities for providing unique names at higher levels (performance testing on Test3?) and implement where possible. 
 f.  Records data integration at Parish level for VLD and CSVProc data.

[RecordsPageDesign I6.xlsx](https://github.com/FreeUKGen/FreeCENMigration/files/6328923/RecordsPageDesign.I6.xlsx)

**Comment by PatReynolds** [comment]
Please could everyone review and feed back @geoffj-FUG @FreecenBren @DeniseColbert (I will make a document to comment on , rather than feeding back here, please.  Document for feedback: https://docs.google.com/document/d/1xb_O3sIm1uyocXGcs1xht4o1HNQsGBf0f1rQ9q2SXno/edit?usp=sharing (please ask if you don't have access, I think you do , but could be wrong...

**Comment by PatReynolds** [comment]
As there have been no comments, to be developed.

**Comment by DeniseColbert** [comment]
I haven't received or seen a document for comment? Could someone share it with me please? (If it's not too late!)

**Comment by DeniseColbert** [comment]
Sorry I hadn't seen this. Initial design looks good- no comments from me. Thanks Anne!
