### ISSUE TITLE
Repeated Folio numbers

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1209]
It has a lot of repeated Folio numbers. We have now developed code to fix this in the download of vld files (being developed) so I will ask for this to be applied to the conversions 

The code on the download is totally different.

@geoffj-FUG Are you saying that we do not need a warning message generated if the folio number  is repeated?

**Comment by geoffj-FUG** [comment]
Kirk

 

We have two scenarios

 

The first is a new transcription on new spreadsheets to the new rules. In that case the folio numbers should be subject to testing for duplicate Folio numbers. They should only be entered once, when they change.

 

The second is when a FC1 file is being downloaded in FC2 format. This can be because the original file is a vld file and also because a transcription is on the FC1 spreadsheet to the FC1 rules. In both cases the repetition of Folio numbers occurred.

 

When we download a vld file the code enters a folio number onto a row only when it changes (the vld file has it on every row). When we are converting a FC1 spreadsheet to a FC2 spreadsheet then it would be ideal if we could only list the Folio number when it is different to the last Folio number entered (the spreadsheet does not have a folio number on every row). This would remove a large number of unnecessary Warnings from the report and bring the spreadsheet closer to the standard of a FC2 spreadsheet of only being entered when they change.

 

The test is no different, it is just being achieved during the conversion and download.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I am afraid I just do not follow. I need concrete examples of what you are talking about.
