### ISSUE TITLE
Transfer Freecen to mongodb database server

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1219]
Commenced the transfer on Monday May 17

**Comment by Captainkirkdawson** [comment]
Made a mistake in preparations that activated the monthly update as a scheduled task on Colobus that started on Saturday. This led to the systematic deletion of vld files , their entries and associated search records, individuals and dwellings Some 800 files were deleted before I noticed. Decided then to use the April 30 collections used to test Mongo 4.4. All data for the vld files was present since these were taken after the last update. One problem to be resolved was that the search record collection would not have the incorporated csv records. These however can be recovered by reprocessing the small number of files involved (15)

**Comment by Captainkirkdawson** [comment]
It turned out that merging the two collection sets was slow.Also it has become apparent that the merge only checks for new ids and ignores changed documents, Hence will have to reapply the districts, pieces and civil parishes collections as some have changed.
This is going to take longer than expected.

**Comment by Captainkirkdawson** [comment]
Refreshed freecen2 didtricts/piecse/civil parishes/places

Ensured all incorporated files had search records.

Ran a reconciliation between the two data bases and they now match.

Searches appear OK and this confirmed by @pat_reynolds

Propose to do the transition to the new data base on mongodb servers

All servers running against the mongodb servers as of 5pm MDT Wednesday

**Comment by Captainkirkdawson** [comment]
Performance on last 3 days has shown all searches EXCEPT wildcard searches running in less than 25 seconds with 95% taking less that 5 seconds.
Problem with wildcard is that we are not using place indexes correctly because we are using 2 place collections place and freecen2_place.
Solutions are with either solving place selection does not use the place index#1225 or implementing Convert VLD to use Freecen2Place rather than Place.
IMO the later is the best long term solution

**Comment by PatReynolds** [comment]
I agree that option 2 is better.  Will it add significantly to the workload in getting FC1 uploads into FC2?

**Comment by Captainkirkdawson** [comment]
As a result I propose that we undertake story Convert VLD to use Freecen2Place rather than Place#1228. and that we apply this after the next monthly update (due this or next week) and that this be the LAST update from FC1.
What to do with work underway by Bev and others? It is either converted to CSVProc or uploaded directly into FC2 as a VLD using the capability in story Upload and process VLD file#1199 that is ready for final test and deployment.

**Comment by ghost** [comment]
No operational work for me. It can be done by the coordinator or Brenda  or we could have Rhoda do it. It is just like uploading a cvs file

**Comment by FreecenBren** [comment]
Sorry to be a pain.
Before it goes to the COORDS, A little history of FC1  uploads.
Also anticipated questions for those who do not see this list.

When I and all the COORDS uploaded them into the FC1 Database they all had
a sign-on for each County they looked after.
They could upload a VLD at any time, but we did have a date each 4 week
cycle to work to as per the schedule we all use now with FreeREG, FreeBMD,
 FreeCEN and Maintenance.
The  system changed for FC1 because NETWORK PLACES  was closed down by the
service operator.
We did not like having to go into a different county each time to upload  a
VLD all though each COORD had the same password for all their counties.
I could use them all. But if it has to be so then OK!

Dave Mayall then set up the current system that we use today.
I know the COORDS liked to do it themselves.
At the moment they send them to me before the scheduled update which is
this week, I collate them for Lemon. They have to be done using two
categories.

1. New VLDs
In each one the VLD’s have to be saved in a another folder by each County.
Example: Notts will be NTT etc.  All census years together.
This is to make sure that Lemon knows which County it needs to be added too.

2. Number amended VLD’s.
This is always an issue.
FC1 does not let you add an amended to the FC1 automatically.
The original one online,  has to be removed first, then the amended version
added.
 Otherwise,  if not, then the newly amended VLD, when added,  would fail as
a duplicate. (As previously mentioned to Anne  or Rhoda.)

Personally I think the COORDS would prefer to go back to being able to
upload the finished VLD.

*So what would they be asking is?*
1. Would that be by county!
2. Would it be by PIECE number. (FC1 format)! or (FC2 format with the
underscore)
3. Would it be by Census Year!
4. How would they deal with replacing an amended PIECE and removing the
original.
5. Would the FC1 Stats show it is online as it does now.
6. Would they have instructions how!
7. Will they be able to use the test system to have a go?
8. Any questions I might have missed  to add here from the COORDS.
9. I do not have any preference wether COORDS do it themselves, or  myself
as now,  or a volunteer COORD!
10. Anymore  question or suggestions.

Sorry it is long winded but I need to know the answers myself .
Not being in the testing myself!
It is very easy to miss something.

Cheers Brenda

**Comment by PatReynolds** [comment]
Hi Brenda,

This story is about the transfer of the database from the old servers to the new servers.  It has now been resolved.  It has nothing to do with the uploading of files (via FC1 or direct to FC2) as such, but I see now that Kirk has added a comment about which Place files we use.  

I'll include that the other points you raise in my email.

**Comment by ghost** [comment]
@PatReynolds the comments from @FreecenBren are quite appropriate SHOULD the decision be taken to undertake story Convert VLD to use Freecen2Place rather than Place#1228. 
The problem that it proposes to fix was identified as a result of the Transfer Freecen to mongodb database server and an analysis of performance.
This specific story ie the Transfer should be considered finished and should be closed in the next scrum. Further comments relating to the issues arising from the transfer should be considered there.
