### ISSUE TITLE
Disparity in total records?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1221]
Today FreeCEN1 is reporting 40,834,241 total records, and FreeCEN2 35,071,112

It took FreeCEN1 5.5 years to add 10million records, but half a million were added to FreeCEN2 in the last month (adding 10 million in under 2 years at this rate).

**Comment by FreecenBren** [comment]
Last month end I found a discrepancy  in what FC2  records had added.
I mentioned it to Kirk to see of there was a breakdown by piece number.

Can we have a breakdown please on the FreeCEN two totals please since
December by County and Piece number that were uploaded. Hi

I am assuming the FC2 totals should only be what has been added direct into
FC2 since December using FC2 and not include those added to FC2 after the
FC1 upload.
Just curious that is all.

Brenda

**Comment by Captainkirkdawson** [comment]
Brenda
The footer report INCLUDES all records in the database. Including those from VLDs and those from CSVs. Our users are not interested in their means of entry.
The reports in early May because of an error in the processing system
The reports are now functioning correctly.
![footer.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/6d02e1b8-edb3-4466-9125-066c647917c6)
There is a detailed report on the content of the database in Site Statistics
![sit.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9d8fdc0a-b06c-494a-985b-8c024da61bcf)
Each county has a detailed report
![Leicester.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ca11d607-07d7-43c3-84bb-3a0b3ec53413)
The reports section is currently under a rewrite Develop a plan for the future of the Records displays#1194
