### ISSUE TITLE
Issues with record count?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1222]
Looking at number of individuals on FreeCEN1 (almost 41 million) FreeCEN2 has only 35 million.

Rate of increase on FreeCEN1 is a fairly constant 10 million in 5.5 years, but last month FreeCEN2 had over half a million (adding 10 million in under 2 years).

**Comment by FreecenBren** [comment]
This is due to a duplicate piece  in two counties that needs adjusting.
On my list to do.

**Comment by PatReynolds** [comment]
Also due to an issue that occurred during the switch of servers on FreeCEN2 - which should be resolved by tomorrow.

**Comment by Captainkirkdawson** [comment]
The database should be reporting correctly as of deployment to the new servers
![footer.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0d6e2bc9-e354-41bf-985d-7c8185795e6b)
![sit.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/010f7dfa-5f23-4af9-8c54-cb75782ebd40)

**Comment by Captainkirkdawson** [comment]
FC1 reports 40,834,241 individuals; FC2 reports 40,818,431 VLD individuals and 393,996 individuals from CSV

**Comment by PatReynolds** [comment]
@PatReynolds to check that the counts are identical on FreeCEN1 and FreeCEN2

**Comment by PatReynolds** [comment]
FreeCEN1: 40,923,091 records
FreeCEN2:  41,388,925 records of which 1500480 are CSV rececords (so 39,888,445). 1,034,646 vld records presumably are those which did not load.

Need to test after that work undertaken.

**Comment by PatReynolds** [comment]
Emailed Lemon (and Vino) 14/7/2021

**Comment by DeniseColbert** [comment]
More work needs to be done on reconciliation before Pat can do her bit

**Comment by PatReynolds** [comment]
Today (7 Sep 2021) there are 42,194,618 records on FreeCEN2, and 41,015,224  on FreeCEN1 - given that there are some records uploaded to FC2 but awaiting uploading to FC1, or never going to be uploaded to FC1, or uploaded ot FC1, but only enabled on FC2 ... is the difference - which is what is expected, and will grow -  now  not capable of being reconciled?  Is a reconciliation desirable?

**Comment by Captainkirkdawson** [comment]
@PatReynolds @AnneV-Learn 
Fundamentally since FC1 is basically static there is no value in any regular attempt to reconcile numbers between the FC2 and FC1. 
There is however a need for ensuring that FC2 has ALL files uploaded into FC1.
@FreecenBren  attempted to do this following each monthly update and she and I attempted to do that following the last update. I believe we came close but I cannot say for certain that it is 100%.
What has become clear is that the Online status as reported by FC2 is less than reported by FC1 by some 40 files.
![online](https://user-images.githubusercontent.com/2874694/132617506-f39fb1e0-b2ed-4a61-97a7-0d2253a42481.png)

I have spent several hours today correcting FC2 information as it appears that the initial load done in 2017 was NEVER fully checked. There were some 40 files not showing Online when they should; There were some 306 pieces showing they had a file and the filename was incorrect and the linked file had not been processed, most in Scotland.
These I have cleaned out

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn  The clean up has now resolved the Online status discrepancy on site statistics.
![Online status.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c2a68ad7-6c8f-4967-bfe0-e704eb194086)

**Comment by Captainkirkdawson** [comment]
@FreecenBren  Lemon and I have compared the vld file contents of FC1 and FC2 and believe that the following files are missing from FC2
./BRK/RG120997.VLD
./CON/RG091546.VLD
./CON/RG121835.VLD
./LAN/RG092825.VLD
./OXF/RG121165.VLD
./PER/HS414387.VLD
./PER/HS415387.VLD
./SOM/HO511940.VLD
./SOM/HO511943.VLD
./SOM/RG091698.VLD
./SOM/RG121932.VLD

Will discus this with you off line

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen @PatReynolds @DeniseColbert  @AnneV-Learn @geoffj-FUG 

I have dealt with and addressed them as indicated below
./BRK/RG120997.VLD, missing fc1 piece, added and file loaded
./CON/RG091546.VLD, missing file, loaded
./CON/RG121835.VLD, missing file, loaded
./LAN/RG092825.VLD, not missing
./OXF/RG121165.VLD, missing fc1 piece, loaded
./PER/HS414387.VLD, file was present but with different case vld, no action
./PER/HS415387.VLD, file was present but with different case vld, no action
./SOM/HO511940.VLD, missing file, loaded
./SOM/HO511943.VLD, missing fc1 piece, added and file loaded
./SOM/RG091698.VLD, missing fc1 piece, added and file loaded
./SOM/RG121932.VLD, Missing fc1 piece, added and file loaded

As you see
6 of the cases were a result of a missing piece parm for FC1 (No idea why)
3 were files not loaded for some reason
2 were a result of an incorrect case comparison as the files are there
1 was indeed there.

So I believe that all of FC1 VLD files are now present and correct on FC2

**Comment by geoffj-FUG** [comment]
Kirk

 

I have just looked at the 4 SOM files. The numbers rang a bell.

 

As a result of Action Reports data has been corrected in all 4 SOM files as
follows:

 

HO511940.vld removed and now reloaded as HO107_1940.csv and HO107_1940A.csv

HO511943.vld removed and now reloaded as HO107_1943.csv and HO107_1943A.csv

RG091968.vld removed and now reloaded as RG09_1968.csv

RG121932.vld removed and now reloaded as RG12_1932.csv

 

Old vld files were removed when the csv files were loaded. Therefore there
will never be an exact match on FC1.vld files as transferred and FC2 vld
files as received from FC1.

 

'Missing from the PARMS' is probably that early problem we had where
Coordinators, including myself, were deleting the PARMS entry when doing
Action Reports instead of the vld file. You fixed up that problem. 

 

I presume, but have not checked, that Rhoda is now the person who would
normally delete a PARMS entry from now onwards. It should not be available
to Coordinators as an option. Coordinators should only be able to delete the
old vld file when uploading a replacement csv file.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk
If the vld files have been restored to FC2 we now have duplicate data, the vld copy includes the transcription problems that were reported by researchers.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG yes as noted in the post they were restored but have now been deleted at your request.
Perhaps you can ask the CON and OXF coordinators about the 3 for those counties if you will.
BRK, LAN and PER are OK

**Comment by geoffj-FUG** [comment]
Kirk

 

Both CON files RG9 1546 and RG12 1835 are now incorporated as csv files. The
vld files were removed when the Action reports were done.

 

The reality is that the number of vld files will gradually decrease once no
more vld files are incorporated into FC2. They will be replaced by csv files
as Action Reports are generated and corrected.

 

I will follow up OXF. 

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG the 2 CON that were added have been removed

**Comment by Captainkirkdawson** [comment]
The OXF vld has been removed as requested

**Comment by Captainkirkdawson** [comment]
I believe reconciliation is now complete

**Comment by DeniseColbert** [comment]
Done- closing
