### ISSUE TITLE
Shipping parameters

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1240]
There is a batch of pieces under England and Wales Shipping for 1861 (only)

Districts level looks OK. There are 2 links required:
Merchants At Home
Shipping at Sea and in Ports abroad
They are already linked at District level correctly

Now we come to Piece level. The Merchants at Home piece name can be anywhere in the UK. (Shipping at Sea and in Ports abroad is OK at this level). Ali needs to see every place in the Gazetteer to link the Pice Names.

Our instructions say that the civil parish that we are going to match against is:
Civil_parish – This is the parish in which the census was lodged. If the ship was at sea on census night, it will be the first port visited.
This is the same as the instructions for FC1.

However Civil Parishes is empty. None are recorded. Given the nature of Shipping the Civil Parish will probably be the same as the piece.  (Though I suspect not always). I think that we need to copy the piece names to the civil parish level. Any anomalies can be sorted out as they arise.

Geoff

E2 U6 S8 C5: P21

**Comment by PatReynolds** [comment]
Looking at this example, it appears that there _is_ a civil parish: "General Register Office: 1861 Census Returns database, FreeCEN (https://www.freecen.org.uk/search_records/5c87acbcf4040bce77a9886d : viewed 23 Jun 2021), Robert ALCOCK in household of Charles LILLFORD, (Abraham) Gool, England and Wales Shipping, England; from 1861 "England, Scotland and Wales census," database and images; citing The National Archives RG 9/4442, Folio 13, Page 0, Schedule 0, The National Archives, Kew, Surrey.  But the CP is misleading.

This is the original 
https://drive.google.com/file/d/1s6_l8HOcNqAq6PuQFXceEM4-UrgIiQM0/view?usp=sharing
https://drive.google.com/file/d/1isQRhuLPchXF1eBhyMazrinVyQh-PzZt/view?usp=sharing

1871 appears very similar
https://drive.google.com/file/d/1qaKFAOb8baWJEd5HK5vNiJlpPJCFmjpK/view?usp=sharing
https://drive.google.com/file/d/17MkKMeZyt-U_zzFvth4BDDx4U_JqL4c6/view?usp=sharing

The place where the census delivered is not Hull ERY, it is Hull Roads - i.e. Hull Roadstead, a body of sheltered water where shipping can wait for favourable conditions, or to enter harbour.  So a subsection of "at sea" rather than of the East Riding.

The 'place delivered' is of interest to the researcher, but we have no way of knowing if the Abraham was coming from / going to Hull or Goole.

I think that searching by home port is something that our users would want.   It's complicated by the need to TWYS but index by normalised spelling (similar to the place of birth) - and a PoB type solution seems useful (i.e. index as Goole, but display Gool in this case).

Options for where to type Gool (and where to index Goole) are: Civil Parish or District.  Or adding a new columns.

For district: for larger ports, this would mean that the  shipping and the port would be the same district (e.g. Goole) but for smaller ports (e.g. Staithes) the district (Whitby) would be misleading (and perhaps a place inland).

If we go with home port as Civil Parish, then we would need to find out where the harbour, quay or docks were at that time (perhaps choosing the one with the customs house if the docks spanned a number of parishes).

**Comment by geoffj-FUG** [comment]
Pat

 

The story is to enable the geographic work on the shipping to be done.

 

The transcription rules were well documented in FC1 and have been continued into FC2.

 

There are 2 groups of returns:

Ships in dock. The civil parish for these is straightforward. We just need changes to be made to the PARMS processes to allow them to be linked.

The ships at sea handed in their census at the first port they arrived at. In the case of Bristol, for instance, they were handed to the pilot who came from Pill. The ship however docked in Bristol. The census will be recorded against the civil parish of Pill. So for each of these pieces the cover sheet of the ED will need to be examined and the parish where the census was lodged will need to be identified. Ali will then link to that parish and tell Rhoda to amend the parish to the one on the census.

 

So the story is about a code change to make it happen.

 

Geoff

**Comment by Captainkirkdawson** [comment]
I am afraid its a great deal more complex as the individual EWS pieces are not connected to the 2 Districts

**Comment by Captainkirkdawson** [comment]
@PatReynolds Your example is from a VLD record ie FR1 not a CVS record. What @geoffj-FUG is talking about is the set up of Shipping records loaded into CSVProc and how they are to be  connected to Civil Parishes and Freecen2 Places.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  I propose we split this story into 2 separate stories as the work required is different in nature. I would also suggest that this is of lower priority than other aspects of our work and should be dealt with later in the year.

**Comment by Captainkirkdawson** [comment]
Dependant stories created

**Comment by PatReynolds** [comment]
I Don't see what the VLD ves CSV has to do with it - I was taking the data directly from the censuses.  Which differs between censuses.

I _think_ this story is about indexing rather than content - and about searching those indexes.  If that's a different story, could you point me at it?

**Comment by Captainkirkdawson** [comment]
Sorry @PatReynolds this story is about how to establish the parameters that link Freecen2CivilParishes, Freecen2Pieces, and Freecen2Districts with Freecen2Places. It does not deal with FreecenPieces and its linkages to Places

**Comment by PatReynolds** [comment]
There is a piece for each port.

This needs to be fixed first.

Then a decision can be taken on the next step.

**Comment by PatReynolds** [comment]
Closing as wne stories made
