### ISSUE TITLE
Explain  that if place is not transcribed, it does not appear for selection, and that counties without places can be selected, but nothing is there to be found

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1270]
E0 U3 S6 C6: P15

**Comment by DeniseColbert** [comment]
@AlOneill could you add this into the Help please?

**Comment by AlOneill** [comment]
It appears to be more nuanced than the explanation suggests. I could not think of a county that would have zero transcriptions. So I looked at Rutland (being small!):

![FreeCEN_places](https://user-images.githubusercontent.com/14852554/134387809-f590fa15-388a-4be3-b873-9358dbf65d64.png)

Four 'Places' (RDs) are listed, with the years that we have transcribed. The years selected for the search have no effect on what is shown in the 'Places' field. That is how you can select a 'Place' that has no records for the selected census year.

BTW, why is there a single quotation mark in front of every year except the first? Instead of a space??

**Comment by AlOneill** [comment]
The DRAFT Help is ready for review. Have updated the [Census Location section](https://test3.freecen.org.uk/cms/draft-help#location) and added a lead paragraph to the page.

I will update the image (same as in post above) if and when the single-quotation mark separator issue can be resolved.

**Comment by DeniseColbert** [comment]
@DeniseColbert and @PatReynolds to review. Thanks @AlOneill

**Comment by PatReynolds** [comment]
Hi @AlOneill all looking good but I'm a little confursed by the "special counties" paragraph, but think that can wait until the below is resolved (#495 covers improvements to searching for shipping).

The pseudo-counties presented will need some pruning (or development).

Census counties with no Smiths (so presumably completely empty, and need not be covered in the help:
Unknown
Out of County
Overseas British (needs deleting from search options anyway as being removed from records)
Overseas Foreign
Other Locations
Royal Navy Ships (is this E+W RN?  If so, why not the same search choice as Scotland?  )
Military

Cencus counties with Smiths, so need explanation:
E&W shipping - possibly should note include the at home / at sea distinction in search Doesn't seem helpful for a family history search.
Scottish shipping - distinction between Marchant Shipping and Royal Navy good and needed.  Help should include that Merchant shipping definition is wider than the usual meaning of "trading vessel", "ship designed to carry goods" - it includes passenger liners, fishing boats, whalers, etc. etc.

**Comment by Captainkirkdawson** [comment]
@PatReynolds @AlOneill Part of this story will become irrelevant if we agree to deploy **Integrate all components to use places in our Gazetteer.#1305** One of the changes eliminates counties with no transcriptions from the Census County drop down list.
![searchpage](https://user-images.githubusercontent.com/2874694/137929491-eddacfd2-df15-4322-a0dc-2ef3b667e5e0.png)

**Comment by AlOneill** [comment]
@PatReynolds the counties "Out of County" "OVB" and "OVF" cannot be **Census** counties: they are only ever **Birth** counties. I'll review the information on special counties, but the changes of #1305 should help to make that clear.

The _usual_  (dictionary) definition of Merchant Shipping is any shipping that is not military. Perhaps this is not obvious if English is not your first language (or you know nothing about shipping!), so will add a note to that effect.

**Comment by AlOneill** [comment]
Have not added the note re Merchant shipping as I could not find Scottish Shipping in the list of Census counties (and England and Wales shipping does not appear to use it).

**Comment by PatReynolds** [comment]
@PatReynolds to retest after the St Nicholas gift deployment

**Comment by PatReynolds** [comment]
Hi @AlOneill the 'list of counties' is the one on the search form.  

I looked at some definitions of "merchant shipping" online and the meaning now does seem to be narrowing to those carrying raw materials or manufactured goods.

**Comment by AlOneill** [comment]
@PatReynolds OK, but I do not know where a researcher would encounter the term Merchant Navy and so do not know the context for the proposed explanation.

I can see that E&W and Scottish Shipping plus Royal Navy are included in the **Birth County** choices, but only E&W Shipping is listed for **Census County** and that has a single associated Place, "Shipping at Sea and at Ports abroad (1861)". What am I failing to notice?

**Comment by PatReynolds** [comment]
EWS offers 'Merchants and Home' and 'Merchants at Sea' as the choices (even worse than Merchant Navy or Merchant Ships!) Scottish offers 'Merchant Ships'.

**Comment by AlOneill** [comment]
@PatReynolds Thanks, I see them — after a re-load of the page (doh!). As I said above, I will make it clear what is meant by Merchant Navy  in our context …

… We'll have to see how the meaning shifts (or not) as we encounter 20th century census returns.

**Comment by AlOneill** [comment]
@PatReynolds I'm thinking that we need a bit of explanation re shipping returns for the various years: I know what happened in Scotland (at least up to 1871) but have little idea of how things were organised in E&W. I cannot find out easily as Scottish Shipping is not listed (I know that there are transcriptions) and E&W has returns for 1861 only. I will dig into search results for 1861 so that I can explain what can be found where. I've already noticed that a ship in E&W shipping could have an all-Scottish Crewe if that ship was registered at an English port!

For Scotland, the 

* 1841 returns are with the parish returns

* 1851 returns were destroyed

* 1861 and 1871 returns were counted as Scottish Shipping

My guess would be that for the subsequent years, shipping returns continued to be counted separately, but that is only a guess.

**Comment by AlOneill** [comment]
Draft Help edited to explain meaning of 'Merchant' in the context of shipping.

Image replaced as the format of the year listing is largely resolved — the leading space jumped out at me but it might not trouble many others!!

Moving beck to 'Needs review'. Will work on remaining issue (what is where in the detail results and how organisation changed from year to year) when Scottish Shipping becomes searchable. In the meantime, **do we publish the revisions so far?**

**Comment by AlOneill** [comment]
Re-opening as I feel like I've been left hanging on this one …

@PatReynolds Do we publish this draft version or not?

**Comment by AlOneill** [comment]
@PatReynolds Do I publish this draft version? I am confused …
https://test3.freecen.org.uk/cms/draft-help

**Comment by AlOneill** [comment]
If it's not to be published, then what should I do with it?

**Comment by PatReynolds** [comment]
Excellent, @AlOneill ! Ready to publish!

**Comment by AlOneill** [comment]
@PatReynolds Thank you. Page is now sync-ready.

**Comment by Captainkirkdawson** [comment]
Refinery updated on cen

**Comment by AlOneill** [comment]
@Captainkirkdawson Oops — something has gone wrong. It seems that I did not make the changes in Refinery that I thought I did. Will sort it out next.

**Comment by AlOneill** [comment]
@Captainkirkdawson @PatReynolds Changes made and confirmed. Page _is now_ sync-ready. Apologies for the blunder!
