### ISSUE TITLE
Can we (or do we) tell how many transcribers are active?

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1358]
This info is included in FreeBMD newsletters and is also in the latest FreeREG newsletter. It would be very useful if we could have a similar metric for FreeCEN. I imagine it could be difficult to know in FreeCEN...

**Comment by Captainkirkdawson** [comment]
Both FreeBMD and FreeREG have always worked on the basis of transcriber uploading and processing their transcriptions (file) it is possible to define some metric for active. e.g. uploaded a file within the last year, 6 months or 3 months; or been active i.e. uploaded a file. 
Since FreeCEN until very recently worked by transcribers giving their work to a coordinator who then uploaded the file and the file never identified its transcriber there are no systematic metrics.  With the advent of CSVProc for FreeCEN it is possible to get some sense of activity. I say sense because only a very few counties are actually using CSVProc. The current statistic says that 106 transcribers have uploaded at least one file in the year that CSVProc has been available. But who knows how many more are active the old way? 
CSVProc has had 1313 files uploaded in that period with 479 incorporated into the database so clearly some transcribers are more active.

**Comment by cmahoneynz** [comment]
I do not think we can tell how many are active at this time with any certainty, maybe something to revisit at a later date.
Take my FreeCEN group for sample, while I have 13 I would consider active at present, only four at this time have made use of CSVProc.  Rest are not at this time for various reasons, mostly as they are transcribing large pieces which they started before FreeCEN 2 became live.  Would however expect some of these to start using CSVProc when they start transcribing under the FreeCEN2 system.
One also has to consider the length of time it takes to transcribe a piece, and also the delay in between transcribing a piece, and having it proofread

**Comment by PatReynolds** [comment]
Thanks all.  I think a (very rough!) calculation could be made along the lines of:
Count the CSV transcribers who have uploaded, and the number of records: get an 'average records per transcriber' number.
Count the number of records uploaded via VLD and divide by the number of records per transcriber.

Reprocessing might make that impractical, though.  

While VLD transcribers may be taking longer to complete (for very understandable reasons), they'll complete more, and previous year's transcriptions will be counted, although some this years will not be counted -  so the numbers should balance out.

**Comment by geoffj-FUG** [comment]
Once vld uploads are eliminated we should be able to d a count of the number of volunteers who have been active on the system in the past xxx months. However as long as we have vld uploads happening this count cannot be achieved.

**Comment by geoffj-FUG** [comment]
We can do it easily for FreeCEN2. We can define it as (for instance) the number of volunteers who have uploaded a test in the last 6 months.
The fly in the ointment is VLD files again. There is no way of knowing who worked on them. They are all uploaded by the Coordinator. The transcriber and proofreader may never have even signed in to the FreeCEN site.
Geoff

**Comment by geoffj-FUG** [comment]
Draft spec for report sent to Denise. Awaiting reply so that we can progress this.

Geoff

**Comment by DeniseColbert** [comment]
Captured in 1551, closing
