### ISSUE TITLE
Help pages revised to reflect changes

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#137]

**Comment by geoffj-FUG** [comment]
Is this still a valid issue. The story number suggests that this is a FC1 issue to me.

Geoff

**Comment by PatReynoldsFUG** [comment]
Pat to take a look

**Comment by PatReynoldsFUG** [comment]
a) if referring to FreeCEN1, the 'Information for volunteers' link now sends the user to FreeCEN2.
b) if referring to FreeCEN2, the 'information for volunteers' has been completely re-written to support the use of FreeCEN procedures and practices.  Further changes, where and when needed, are recorded in separarate stories.

Therefore I suggest that this issue is closed.

**Comment by DeniseColbert** [comment]
Agree: closing
