### ISSUE TITLE
227788464 Unable to validate entries (Geoff)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1395]
Issue reported by **somt.cen** at 2022-03-21 10:34:24 UTC
Time: 2022-03-21T10:32:01+00:00
Session ID: 83e2bf54e0fc28bc061c5356051cb624
Problem Page URL: [/freecen_csv_entries/62370d4cf493fdb714d6ffa8?locale=en](/freecen_csv_entries/62370d4cf493fdb714d6ffa8?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_entries/62370d4cf493fdb714d6ffa8/edit?locale=en](https://www.freecen.org.uk/freecen_csv_entries/62370d4cf493fdb714d6ffa8/edit?locale=en)
Reported Issue:
I have discovered that if there is a hyphen against either the forename or surname a note or alternative POB cannot be entered because the hyphen is rejected. The entry is unable to be changed because of the rejection.
Geoff    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I've just taken a look at this and pls bear in mind this is an area of the code that I haven't looked at previously and am not totally aware of all the intended fuctionality.
What appears to happen is during CSV file processing it will raise a **warning** if Surname or Forenames contain just a single hyphen.
Then when the record is being updated via Online Edit Entry facility of the validation process it checks for a hyphen in either of those fields again and this time will raise an **Error** unless the ‘Record valid’ status has been set to true.
Now in story #1384 we are proposing to remove the facility for a validator to update the ‘Record valid’ status so that approach will not be an option.
I don’t know the history of all this and why the code has this very deliberate functionality to check for a hyphen in Surname or Forenames again  in the Online Edit Entry and raise as an error - do you know what the intention was?

**Comment by geoffj-FUG** [comment]
Anne

 

My comment in red below in the copy sent directly to you as the red doesn’t come out on Github.

 

Geoff

**Comment by AnneV-Learn** [comment]
Thanks for your quick response @geoffj-FUG
The context of an Error during Online Edit Entry processing is different - it stops the edited record from being saved/submitted.There is no real concept of a warning specific to the Online Edit Entry functionality. Would a workaround be for me to remove the code that stops the record from being saved/submitted in Online Edit if it detects hyphen in Surname/Forename(s). Then perhaps the instruction should be that if warnings include hyphen in surname or forename(s) the record should be re-validated after any other 'corrections' are made so that it can be checked again??? may not be the right approach but if we remove facility for validator to change 'Record Valid' status (#1384) not sure I see any other way??? But I am a novice here.

**Comment by geoffj-FUG** [comment]
Anne 

 

That would be the solution.

 

The Warning would come up for the validator. They would normally just accept it. But if the POB needs validating they would resolve both issues in the validation screen.

 

Then if the hyphen was not retested the POB change would be verified with the Gazetteer and the screen would go to the Propagate / Accept options.

 

Geoff

**Comment by AnneV-Learn** [comment]
Ok @Geoff-FUG I’ll proceed that way.

**Comment by AnneV-Learn** [comment]
Modifications  have been deployed to Test3. 
@Geoff-FUG are you able to test please?

**Comment by geoffj-FUG** [comment]
Anne
The fix works fine.
It is now working as expected.
It can be moved to production.

Geoff

**Comment by geoffj-FUG** [comment]
Anne
This is related to the new #1424. We need to tackle this to create one solution. See my note against #1424.
Geoff
