### ISSUE TITLE
Website has incorrect instructions for language

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1409]
The handbook has the new instructions for language as follows:
Field name	language
Column Contains	Language 
Year/s Used 	Wales 1891 – 1911 and Isle of Man 1911 only
What Can Be Entered 	Up to 2 letters or blank
Description and Rules	In many censuses there was a question about language. This occurred in Wales and the Isle of Man. Enter the appropriate letter or letters for the language spoken here. Leave this entry blank if it has not been filled in on the census.
Use a code from the list below:
•	E 	English
•	G 	Gaelic
•	GE 	Gaelic and English
•	I 	Irish
•	IE 	Irish and English
•	M 	Manx
•	ME	Manx and English
•	W 	Welsh
•	WE 	Welsh and English
If you are using the England and Wales spreadsheet for a County that is not in Wales or the Isle of Man leave this column blank.
Note: If the language is enumerated as Both Transcribe the appropriate double entry from the list above. Do not use B as it will produce an Error when tested by CSVProc.

The website still has the old instructions from FC1 as follows:
![image.png](https://images.zenhubusercontent.com/5e8c52a8b7c1d94d472bb276/46bab7e5-8c39-4e78-b564-3fd3f48f8433)

This is causing confusion. Can the old instructions be taken down please and replaced with a note to refer to the Handbook.

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG I can make the changes you request, but let me check that I understand the situation correctly.

[The spreadsheet fields](https://test3.freecen.org.uk/cms/information-for-transcribers/the-spreadsheet-fields) is for volunteers using the VLD system, yes? So, are you saying that transcribers using the VLD system need to follow the same instructions for the Language field as those using CSVProc?

In which case, I suggest that the instructions be changed in situ, rather than referring volunteers to the Handbook (a lengthy, probably unfamiliar document at this stage).

If no-one is using the VLD system any longer, then the whole page would need to be taken down.

I also note that the Language field applies to some Scotland census returns (even though we do not have access to those images for now), not only to Wales and the Isle of Man.

**Comment by PatReynolds** [comment]
Will be updated as part of update of Information for Transcribers page, so closing.
