### ISSUE TITLE
Problem with search?

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1463]
A search for
Last Name
BROWN
Exact Match?
Yes
Birth Year
1865 - 1865
Census Year
All
Census County
Yorkshire, East Riding
Census Place
Kingston Upon Hull (including 100 additional places within 22.2 miles )

Returned 60 results.  A search for the same, but with birth year 1860-1864 returned 246 results: but a search 1860-1865 produced "too many results".

**Comment by DeniseColbert** [comment]
@AnneV-Learn to investigate

**Comment by AnneV-Learn** [comment]
Actually I got the following results for that search:

Birth Year 1865 - 1865 -> 125 Results
Birth Year 1860 - 1864 -> 487 Results

So the total for 1860 - 1865 by just summing the number of results is >500 (i.e. 612)

However it does have to be born in mind that the Census captures Age and not Year of Birth.
So for example a person aged 10 at the time of  he 1871 census could have been born in 1861 or 1860.

The following example illustrates this and means that a simple summing up of results across years does not work. 

SEARCH: Surname = BROWN, Exact Match? = YES, Census County = ERY, Place = Kingston upon Hull, Census Year = 1871


1.Birth Year  - 1860 - 1860 -> 3 Results

Individual			Age		Birth Year in Results Summary
Frances Elizth BROWN 	11 		1860
Mary A BROWN		10		1861
Thomas BROWN		10		1861


2.Birth Year  - 1861 - 1861 -> 3 Results

Individual			Age		Birth Year in Results Summary
Mary A BROWN		10		1861
Thomas BROWN		10		1861
Frederick BROWN		 9		1862


3.Birth Year  - 1862 - 1862 -> 3 Results

Individual			Age		Birth Year in Results Summary
Frederick BROWN		 9		1862
Thomas BROWN		 8		1863
William BROWN		 8		1863

THEN 4.Birth Year  - 1860 - 1862 -> 6 Results

Individual			Age		Birth Year in Results Summary
Frances Elizth BROWN 	11 		1860
Mary A BROWN		10		1861
Thomas BROWN		10		1861
Frederick BROWN		 9		1862
Thomas BROWN		 8		1863
William BROWN		 8		1863


So with out looking at the results in detail one might think it was correct to sum the number of results for 1860, 1861 and 1862 to get to the number of results for 1860 - 1862 
but because when using Year of Birth in the search criteria the same individual can appear in the results for 2 consecutive years that will not work.


![Screenshot 2022-12-03 at 17.38.48.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/5d4c64de-6640-4461-ade1-d0c0cf249f11)
![Screenshot 2022-12-03 at 17.44.45.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/534a8026-efc5-4c33-9a58-0c1c0c918451)

**Comment by geoffj-FUG** [comment]
Most genealogy websites default to age +-2 years in their search forms. This is because the censuses were (generally) taken in April. That means that a person could have been born in the year before or the year after the calculated year based on the age. Most researchers take that situation for granted.
The same applies to FreeBMD an FreeREG as well as FreeCEN. Always use +-2 unless you happen to know the exact date of birth and can therefore make the calculation accurately.
I do not see this as an issue. It is simply a genealogical paradigm.
Geoff

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG it seems that this isn't a problem, if you check and it is we can re-open
