### ISSUE TITLE
Create a log of pieces that are deleted once they have been uploaded as a vld file or incorporated

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1466]
Chris Mahoney commented:
Quote
Where an incorporated piece is removed from the website, is there any kind of follow up on this (assuming one is aware that it has happened) to check that that there are genuine reasons for removing it.  . . .
Just asking in case it happens, and we have the situation where the piece is missing from the website (when it should not be).
FreeBMD has this policy where if a file is deleted, one of the administrator is notified, and they are known to restore it if not convinced a replacement has been uploaded.
Unquote

We should produce a report each month of deleted pieces. It should go to the Data Manager. Rhoda can then check it against the report of pieces Incorporated during the month to ensure that it has been replaced, or follow it up.
Geoff

**Comment by geoffj-FUG** [comment]
This log will also need to include unincorporated csv pieces. We will need to audit this as well to make sure that they are replaced or that the noncorporation is valid.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
The following has now been deployed to TEST3 and is ready for testing:

Having chosen the County to work on (**Manage Counties** dropdown), users with the following roles
'system_administrator data_manager county_coordinator country_coordinator master_county_coordinator' 
will see a **'List Deleted VLD Files**' button on the 'Manage VLD Files' landing page and on the 'Review Batches by Filename' landing page they will see a '**List CSV files that have been Unincorporated/Removed/Deleted**' button.

Each of this will list (most recent first) all files that have been 'deleted etc.' regardless of whether they have subsequently been incorporated but the final column(s) will indicate the CURRENT status of the associated fc2 piece. 

There is also a rake task which creates an email detailing CSV/VLD files that were 'deleted etc.' more than 7 days ago but have not subsequently been incorporated. The email is delivered to the user(s) with data_manager role.

For easier testing I have made it possible for me to divert that email to a specified email address, so whoever does the testing on TEST3 should let me know when they want to test the email (suggest after testing the buttons above first by 'deleting etc.' some of both file types and waiting 7 days!) and I can run the RAKE task so that they get the email.

**Comment by geoffj-FUG** [comment]
Looks good. This can be deployed

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Did you manage to test the functionality ok?

**Comment by geoffj-FUG** [comment]
Yes thanks. Geoff

**Comment by DeniseColbert** [comment]
No evidence of Geoff's test in the log, @geoffj-FUG can you retest?

**Comment by geoffj-FUG** [comment]
@geoffj-FUG     Geoff to let Rhoda know it is happening.

**Comment by DeniseColbert** [comment]
Done, closing
