### ISSUE TITLE
Report a data problem (correction) and Donate info not appearing on detailed result page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1507]
A user reported this record doesn't have the info:

https://www.freecen.org.uk/search_records/62528b0df493fd3deb6e1184/thomas-prescott-1891-worcestershire-redditch-1865-?locale=en

I checked, it doesn't:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/5968e70d-2a2c-4228-8c29-66663867747c)

(Also "String" in tab text- perhaps something to speak to Alison about re. a similar story)

Whereas this one does:

![FC.PNG](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/dc0ea428-19c5-4141-be95-06ba3f3324e0)

**Comment by DeniseColbert** [comment]
Also, he suggested that we make the link more prominenet, like FreeREG (this is important for consistency anyway)

![FR](https://user-images.githubusercontent.com/19173257/227200541-b31db32e-b33d-4359-b4d1-eed2595190c0.PNG)

**Comment by AlOneill** [comment]
Three comments:
1. "string" in the tab-text, the `title` element, is **not** correct. It looks like a placeholder. At the very least it should say "Census entry | FreeCEN". Ideally it should include more detail that identifies the specific entry.
2. the "please report it to…" link is a link (rather than a button) and the styling should keep that general look; and "please" would be better before the link rather than part of it
3. the REG styling makes the link look like a button — if it is **not** a button it should not look like one

**Comment by DeniseColbert** [comment]
@Vino-S to look at this and find out what's happening

**Comment by DeniseColbert** [comment]
@Vino-S to investigate, potential layout issue

**Comment by AlOneill** [comment]
@Vino-S @DeniseColbert 
The current "Report an Error …" is set up as a link. However, I'm now thinking that it _should be_ a button because it **does something rather than simply going somewhere**. So, whatever the issue that  Vino is looking into, making it an actual button, rather than simply looking like one, is what should happen. Apologies for not spotting this previously.

**Comment by DeniseColbert** [comment]
@Vino-S to upload this piece into the test database to check fix in Test 3

**Comment by DeniseColbert** [comment]
@Vino-S to send Denise info on a record to test in Test 3 (then test on live once deployed, with further records)

**Comment by Vino-S** [comment]
Search record:
https://test3.freecen.org.uk/search_records/623f31cdbd30f27542bbb01a/thomas-aswell-1871-london-city-bermondsey-1833-?locale=en

Freecen Csv Entry:
https://test3.freecen.org.uk/freecen_csv_entries/623f3117bd30f273f9b638e3?locale=en&type=Ind

**Comment by DeniseColbert** [comment]
CSV page layout:

![image](https://github.com/FreeUKGen/FreeCENMigration/assets/19173257/3b3e5ebc-1887-4da2-a08f-473c59cbfca8)

Record layout

![image](https://github.com/FreeUKGen/FreeCENMigration/assets/19173257/233acdd3-7faf-4fa6-9d86-d4ad3365fc97)

No donate or buttons on record @Vino-S

**Comment by DeniseColbert** [comment]
Ctrl+F5 fixed this, so can be deployed

**Comment by Vino-S** [comment]
Deployed

**Comment by DeniseColbert** [comment]
Done: closing
