### ISSUE TITLE
Changes to the text on "Opportunities to Volunteer" page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1515]
**Below Transcribers:**

We will send you images to transcribe, and pre-formatted spreadsheet and guidance on how to transcribe. 

**After quality standards:**

Your Coordinator will support you with any issues you encounter, and you can join a friendly support group where other volunteers can help you learn, and in turn you will be able to advise others.

**After advise others:** 

Time commitment is solely up to you: you can work entirely at your own pace.

**Comment by DeniseColbert** [comment]
@AlOneill could you take a look please? Feel free to improve for sense, grammar etc.

**Comment by AlOneill** [comment]
I will also take the opportunity to add ARIA attributes to the page as appropriate.
DRAFT page created on test 3.

**Comment by AlOneill** [comment]
@DeniseColbert 
Text changed as per description, with tweaks to text as noted in the [DRAFT Opportunities to volunteer with FreeCEN](https://test3.freecen.org.uk/cms/draft-opportunities-to-volunteer-with-freecen).

Other changes:
 * give the opening paragraph `class="lead"` 
 * change the following links so that they open in the same tab: donate; Easy Fundraising; FreeUK Gen volunteer page
* add ARIA markup and do a basic check with VO (i.e. VoiceOver, the built-in Mac screen reader)

**Comment by DeniseColbert** [comment]
Looks great, thanks @AlOneill

**Comment by AlOneill** [comment]
@DeniseColbert Thank you. 
Page is now sync-ready (i.e. ready for deployment).

**Comment by DeniseColbert** [comment]
Deployed: closing
