### ISSUE TITLE
Executive Director role can access/manage To Be Destroyed syndicate

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1519]

**Comment by AnneV-Learn** [comment]
'Move to inactive syndicate' made available to executive_director role. 
If this is used for a user it moves them to the 'To be Destroyed' syndicate and then the 'Destroy' button appears against that user. The user can then be completely destroyed by clicking that button or moved make to an active syndicate via edit user.

**Comment by AnneV-Learn** [comment]
@DeniseColbert ready for testing on Test3

**Comment by DeniseColbert** [comment]
I can't see it, @AnneV-Learn 

![image](https://user-images.githubusercontent.com/19173257/235883808-7d1bd8ad-856d-420d-b893-528824f0e5ca.png)

![image](https://user-images.githubusercontent.com/19173257/235884014-e5899bde-3667-4752-8ac5-ce22b768459b.png)

Where should "Move to Inactive Syndicate" be?

**Comment by DeniseColbert** [comment]
I can't see it @AnneV-Learn, will send screenshots on Slack

**Comment by AnneV-Learn** [comment]
Were you on Test3 @DeniseColbert?

**Comment by DeniseColbert** [comment]
Executive Director role needs to include Master Coordinator abilities

**Comment by AnneV-Learn** [comment]
Ok @DeniseColbert I have made updates so that Executive Director includes Master Coordinator abilities.
This has opened up the following processes to Executive Director:

1. Full capabilities to edit users
2. Destroy a Freecen1 Piece
3. List of 'deleted….' CSV files
4. CSV files access to functions that lock/unlock file
5. Delete a Freecen2 Piece for 1901 and 1911
6. VLD files Download and Replace functions
7. List of 'deleted….' VLD files
8. List VLD files with invalid Civil Parishes
9. VLD file downloads
10. Edit/Delete Civil Parish
11. Edit District

It is ready for testing on Test3.

**Comment by DeniseColbert** [comment]
Thanks, Anne. I won't touch any of those without clear guidance and instruction from someone with a lot more knowledge than me!

**Comment by DeniseColbert** [comment]
Yes, everything I need to do I have access to. I don't want to crawl around the actions above as I'm not sure I won't break something and I don't need to _do _ any of that so happy to deploy this as-is.

**Comment by DeniseColbert** [comment]
Deployed, closing
