### ISSUE TITLE
Editing of London Gazetteer entries

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1526]
The ability to add or edit London Gazetteer entries is only available to the data manager so that we can control the entries that are made.
I would like to extend this ability to the London Coordinator as well please. (Only LND **Not** all Coordinators).
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on Test3.
Could you do 2 tests please:
1. The current LND coord on Test3  is Brenhanna, so the first test should prevent you from editing a LND Gaz place. If passes that test, let me know and I will then make you the LND coord on Test3.
2. Then re-test and you should be able to edit a LND Gaz place.

**Comment by geoffj-FUG** [comment]
Step 1 passed

 

Can you make my GeoffJ Userid London Coordinator please?

 

Thanks

 

Geoff

**Comment by AnneV-Learn** [comment]
Hi Geoff,

Done 🙂

Anne

On 5 May 2023, at 03:54, Geoff J ***@***.***> wrote:

﻿


Step 1 passed



Can you make my GeoffJ Userid London Coordinator please?



Thanks



Geoff

**Comment by geoffj-FUG** [comment]
Anne 

 

I can add an alternative place name and change attributes such as the source. I can destroy an entry.

 

I cannot add an entry because the LND choice does not appear in the list. Can this appear for the London Coordinator only please?

 

Geoff

 

Beki

This is in the test environment, so you can’t see it. Just keeping you up to date.

Geoff

**Comment by AnneV-Learn** [comment]
Ok Geoff I’ll get on to that today hopefully and let you know when to retest.

Anne

On 5 May 2023, at 08:09, Geoff J ***@***.***> wrote:

﻿

Anne



I can add an alternative place name and change attributes such as the source. I can destroy an entry.



I cannot add an entry because the LND choice does not appear in the list. Can this appear for the London Coordinator only please?



Geoff



Beki

This is in the test environment, so you can’t see it. Just keeping you up to date.

Geoff

**Comment by AnneV-Learn** [comment]
@Geoffj-fug correction made, so ready for retesting

**Comment by geoffj-FUG** [comment]
Anne 
That is working well. We can deploy
Geoff

**Comment by AnneV-Learn** [comment]
🙂👍🏻

**Comment by DeniseColbert** [comment]
Deployed, closing
