### ISSUE TITLE
LAN Syndicate Message did not send

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1528]
I sent a message to CHS and LAN on April 18th. 

Anne says: the Cheshire one was sent to ‘Members of the Cheshire Syndicate’ but there is a problem with the Lancashire one it appears to have attempted to send to ‘Members of the All Syndicate’.
All Syndicate does not exist to my knowledge so there is some sort of bug.
I believe it is driven by session parameters (cookies). If you log out of Freecen, then log back in again and try to create and send the LAN again that may work.
There is obviously a bug somewhere, however the whole ‘messages’ area of code is pretty complicated as it tries to be all singing all dancing

From previous discussion:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/146157a6-9a02-4928-ba87-a530f457d41e)

**Comment by AnneV-Learn** [comment]
@DeniseColbert try as I might I could not replicate the issue with it sending a syndicate message to 'all' rather than an actual syndicate. So I have just trapped it instead so that an informative error message is displayed and the user is asked to re-select the syndicate. You won't be able to test that unless you can exactly replicate the step you too when the error occurred.
In the light of comments in story #1500 I did a bit of tidying up that I hope will make it more user friendly (I too found it a bit confusing when I was testing, probably due to unfamiliarity). This is what I have done:

**Check box caption**: Active Members -> Active Members Only (BTW this was already checked as the default when you create a new syndicate message)
**Sender list** - put pre-selected current user at the top of the list 
**Send/Resend message button**: text expanded to indicate that it is for selecting the recipients and sending/resending.
You may or may not agree with those changes, so could you please test on Test3 where it has been deployed.

**Comment by DeniseColbert** [comment]
Done, closing
