### ISSUE TITLE
270889380 Welsh place names (Merle)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1555]
Issue reported by **Deedee** at 2023-08-02 07:03:00 UTC
Time: 2023-08-02T07:01:23+00:00
Session ID: dcda4f8df9b26a44fc80f930ea4be5f0
Problem Page URL: [/freecen2_places/search_names_results?locale=en](/freecen2_places/search_names_results?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names?locale=en](https://www.freecen.org.uk/freecen2_places/search_names?locale=en)
Reported Issue:
Searching for towns beginning with 'Llan' in Wales I was told there were none..... Wikipedia list 18 such towns....    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Should the Gazetteer search ‘include’ all counties in Wales if Wales is selected as the search county? 
(NB the places did exist but are recorded against individual Welsh County.)

**Comment by AnneV-Learn** [comment]
Further comment from user:

Thanks for your super-fast reply, Anne.

Having the towns listed under Welsh county is no help when the County is simply stated as Wales.  

Same thing with Yorkshire - in order to look up Birth, Death or Marriage using FreeBMD it is necessary to state the ‘Riding’ which means, if we have only been given Yorkshire as the County we have to research which Riding the person was born in to effect the search.  Not always possible and, when it is, just another step that takes time.  Be so useful to have Yorkshire listed as the County on the Counties list.

Thanks in anticipation.

Merle Drury

**My Note: However according to the Handbook, it is policy to use the lowest level chapman code when creating places in the Gazetteer.** Will this affect our ability to have 'automatic' links between the 3 systems in the future?

**Comment by DeniseColbert** [comment]
This will be tackled in the Search development (ability to search by England, Wales, Ireland etc.)

**Comment by DeniseColbert** [comment]
@geoffj-FUG to contact Merle

**Comment by geoffj-FUG** [comment]
What is involved in enhancing the Gazetteer search so that a user can search from the level 1 entries in the Chapman Code hierarchy (in Part 2 or part 3 Appendix B of the Handbook).
What is the work involved in developing this please?

Geoff

**Comment by DeniseColbert** [comment]
@AnneV-Learn to take a look at what's involved

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Enhancement to the Gazetteer search so that a user can search from the level 1 entries in the Chapman Code hierarchy has been deployed to Test3.

**Comment by DeniseColbert** [comment]
@geoffj-FUG please could you test this in the Gazetteer?

**Comment by geoffj-FUG** [comment]
Overall it looks good. However ...
I tried Helier CHI. It should have brought up 2 entries:
CHI St Helier and JSY St Helier.
CHI St Helier should not be in the Gazetteer, I have created a story to get rid if it. St Helier JSY is found when I use JSY as a Chapman Code but not when I use CHI.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Oh dear - I ‘overlooked’ Channel Islands - I’ll look to including that and let you know when ready to re-test

**Comment by geoffj-FUG** [comment]
Thank you.

 

At least you didn’t miss the scrum! ☹

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Test3 has now been updated to handle Channel Islands correctly - so please re-test.

**Comment by geoffj-FUG** [comment]
Anne

 

That works well now. Please deploy.

 

Geoff

**Comment by DeniseColbert** [comment]
Done; closing
