### ISSUE TITLE
Rake task for vld data collection

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1583]
Now that I have had a look at the live data in the vld collection there are a huge number of entries that need adjusting as follows:

Do while not eof()
    If verbatim_birth_county is not null
        If verbatim_birth_place is null AND birth_place is null
             Replace verbatim_birth_place with -   (hyphen)
             Replace birth_place with -    (hyphen)
       Endif
    Endif
    Next record
Enddo

This will tidy up a huge number of incorrect entries where the verbatim birth place was uploaded as null and therefore the birth place is also null. There should be a hyphen in all these fields. Once the rake is run it will reduce the number of records to be adjusted and result in a significant reduction of revalidation workload. I cannot do this adjustment by propagation as the verbatim fields need amending.

Geoff

**Comment by geoffj-FUG** [comment]
A second Rake task will be to find all the Chapman Codes of WAL and amend them to WLS.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Having looked into the null birth place further I have noticed a couple of 'issues':
1. The monthly VLD upload did **not** populate birth_place in the search_records (manual upload does), I didn't notice this before because there is no monthly uploaded data in Test3. I think the solution is as follows:

- Update the POB validation so that when POB is valid it writes the birth_place to the search_record if it is not already there
- Write a Rake task to populate birth_place in search records for all valid POBs in SOM

2. The spreadsheet for 1841 does not include birth_place, so it seems to me that  I should update the POB validation code for 1841 vld data so that as long as the birth_county is valid the POB is marked as valid

I'll await your comments

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
A Rake task to find all the Chapman Codes of WAL and amend them to WLS has been deployed to Test3. 
I propose to run across SOM vld data on Test3 but don't want to do that until you have had a chance to identify some records that it should have updated so that you can compare before and after it has run.
Please let me know when you are ready for me to go ahead and run on SOM on Test3.

**Comment by geoffj-FUG** [comment]
The spreadsheet that is produced daily with the SOM validation has lots of examples. All I have to do is match to that.
Please let me know when it has been run.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Ok I have run the WAL -> WLS Rake across **SOM** on **Test3**. 
Please bare in mind that there is no overnight POB validation running on Test3 so when you have identified VLD files to check please re-run **Auto Val** against that file to bring the POB validation status up to date after the WAL -> WLS updates that the Rake will have made. (Hope that makes sense).

**Comment by geoffj-FUG** [comment]
That will take me a while. I will test it in the morning as it is late now.

 

Geoff

**Comment by geoffj-FUG** [comment]
Anne

 

This looks good.

 

Can you run this across SOM on the production database please? About 1700 entries (most have 2 instances so 3400 changes).

 

If that runs OK I will get you to run it on the rest of the database.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoff-FUG
There is likely to be a Production deployment this weekend, so I'll run the WAL -> WLS Rake over Production data for SOM after that.

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG
Geoff when you get time can you please have a look at my comment above from a week or so ago about a couple of issues I found when tackling the other rake task you requested.

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG
Geoff when you get time can you please have a look at my comment above from a week or so ago about a couple of issues I found when tackling the other rake task you requested.

**Comment by geoffj-FUG** [comment]
Anne

Will do. 
We need to get the sequence of the change to GLS right alos.
1. Run Rake task WAL.WLS
2. Overnight revalidation run on SOM to pick up changes from Rake task.
3. Change from SOM to GLS for re-validation overnight run.
4. 
That will keep everything straightforward.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - Ok 👍🏻- just need to wait for latest code to be deployed to Production (hopefully this week)

**Comment by geoffj-FUG** [comment]
I have checked the actual changes of several pieces from WAL to WLS successfully. I have also auto validated 3 pieces and the change in number of entries matches the number of WLS entered. Some do not change but they are entries such as WLS Cardiff which will end up being changed during re-validation.

Ready to be deployed.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG
Could you look at my comments on the issues I found related to the original rest to resolve where verbatim birth place was uploaded as null. 
See screenshot below: 
<img width="531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f18ef8985e35d5bf0ef87000b177c22580a9364/IMG_0310.jpeg" alt="IMG_0310.jpeg" />

**Comment by AnneV-Learn** [comment]
@geoffj-FUG
Could you look at my comments on the issues I found related to the original request to resolve where verbatim birth place was uploaded as null. 
See screenshot below: 
<img width="531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f18ef8985e35d5bf0ef87000b177c22580a9364/IMG_0310.jpeg" alt="IMG_0310.jpeg" />

**Comment by geoffj-FUG** [comment]
Anne

 

I noticed that batch. There are quite a few places like that.

 

Our only option is to do a rake task throughout the collection and replace the null birth places with a hyphen.

 

Geoff

**Comment by geoffj-FUG** [comment]
The live rake on SOM has worked well. Did we do all counties or do we need to complete the exercise?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG No it just ran across SOM. I’ll aim to run across all other counties this weekend.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG It has now been run across all counties.

**Comment by geoffj-FUG** [comment]
Anne

 

Thank you.

 

Have we run the null to hyphen across all counties? If not we need to do that.

 

GLS has tested all vld pieces and I have the spreadsheet. Can we move to CON before you go on holiday please? First time 100 to get past 1841 then 20 per day, please.

 

Geoff

**Comment by AnneV-Learn** [comment]
Hi Geoff,

I haven’t run the null to hyphen yet as I’m still developing it. As mentioned in the ZenHub issue there are complications due to an inconsistency in the VLD load process where a manual upload of a VLD file populates birth_place on the search record but the monthly upload did not.
I need to resolve the consequences of that first. The most efficient way to write the null to hyphen is to start with the search record and then cascade the hyphen through the linked individual records and then down to the VLD records. There is a lot of data and doing it the reverse if that would take simply ages to run. But of course all search records must have the birth_place value from the VLD source first otherwise it would put a hyphen in the search record inappropriately.
I doubt all of that will be resolved before I go on holiday.

I’ll switch the VLD run to CON at the end of next week.

Remember that propagation wider than file only happens during the overnight rake (or Auto Val of a specific file) so if you are still working on GLS but the overnight rake has moved to CON you should run Auto Val on a file before working on it to make sure all propagations have been applied.

Anne

On 30 Dec 2023, at 06:36, Geoff J ***@***.***> wrote:

﻿

Anne



Thank you.



Have we run the null to hyphen across all counties? If not we need to do that.



GLS has tested all vld pieces and I have the spreadsheet. Can we move to CON before you go on holiday please? First time 100 to get past 1841 then 20 per day, please.



Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
I have just switched the overnight POB validation rake to CON with max of 100 previously unvalidated vld files and I'll reduce to 20 tomorrow (assuming it runs successfully tonight).
Now to summarise where I am with the missing birth place -> hyphen and population of birth place on the search records for VLD files uploaded via the Monthly upload:

- The replacing missing birth place with a hyphen  will be included in the POB validation code (overnight rake and Auto Val option in the VLD files screen). This will be deployed when I return from holiday and I will run validation across SOM and GLS again to catch any missing birth places still lurking there.
- I have written a rake to populate birth place on the search records for VLD data where it is missing. This will be run county by county by me as you request a switch to the 'next' county for the overnight VLD POB validation, eg when you ask to switch from CON, I'll run it over CON and then switch the overnight rake to the new county. When I return from holiday this rake will be deployed to production and I'll run it over SOM and GLS to catch up with those.

One final point to note is that when you have finished POB validation across all counties with VLD files, I will need to run the POB validation rake across each county one final time to ensure all 'whole dataset' propagations that were added while validating a county are acted on by all counties and to ensure all Gazetteer updates are utilised by all counties (eg. whole dataset propagations and gazetteer updates saved when validating GLS (the second county to revalidated)  may affect records in SOM (the first county to be validated)).

**Comment by AnneV-Learn** [comment]
Hi Geoff,

Looks like it did run on CON but probably timed out after about 60 files. I’ll investigate further (bit busy with granddaughter’s birthday party today so won’t get to it immediately) and switch it to 20 anyway.
(You can still look at individual file records via the VLD file list screen of course).
Anne
On 30 Dec 2023, at 06:36, Geoff J ***@***.***> wrote:

﻿

Anne



Thank you.



Have we run the null to hyphen across all counties? If not we need to do that.



GLS has tested all vld pieces and I have the spreadsheet. Can we move to CON before you go on holiday please? First time 100 to get past 1841 then 20 per day, please.



Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Code to resolve missing birth place -> hyphen and population of birth place on the search records for VLD files uploaded via the Monthly upload where birth_place not populated on search_records was deployed to production on 03/02 and I have now run the required Rake tasks over SOM, GLS and CON. Moving forwards other counties will deal with these issues automatically via the updated POB validation code.
I believe this story can be closed now.

**Comment by geoffj-FUG** [comment]
Anne

 

That has cleared the 1841 validation for SOM so appears to have run OK.

 

I have completed GLS. Can we run it on GLS too, please?

 

Fromm your comment I presume that this now happens automatically when we run the vld validation. If not can you also run it on CON, please?

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have just now re-run validation over GLS.
Validation summary is now as follows:
**Processed GLS - 43 vld files with 211771 individuals - found 2268 invalid POBs.**
Yes, as you say the issues are now handled automatically when POB validation is run (both overnight RAKE job and individual VLD file validation), so as CON is still running via overnight RAKE they will have been resolved there now too.

**Comment by geoffj-FUG** [comment]
Thank you. 

 

2268 invalid POBs is 0.45% of all records. I didn’t think I could get that low.

 

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
