### ISSUE TITLE
Search form wording - leave blank to search all counties

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#164]
Initial testing indicates Users do not realize they can search all census counties or all birth counties by not selecting a county (due to the current wording that says "Select one to three").  Since there is no "All counties" option in the drop-down like in FC1, we should clarify the wording with something such as "..., or leave blank to search all" or else add an "All Counties" option to the drop down.

**Comment by PatReynolds** [comment]
Add 'all counties' option.

**Comment by AlexAvlonitis** [comment]
@dougkdev 
https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/views/search_queries/_form_freecen.html.erb#L100

<option value="">All Counties</option>

For the option to be there but pass nothing as a value.

I was wondering what's the best way of reviewing code, since we are not using pull requests.
If the solution is small i can post it here but what if it's multiple lines and files?  because if i just push it on master directly and wait for a review, it might cause issues, someone can deploy the code without a review first. Or still need multiple corrections until it's ready.

**Comment by dougkdev** [comment]
Hi @AlexAvlonitis ,

When working on FreeCen, instead of checking in to master, check in to the freecen_parsing branch.

The way we have done it in the past has been to test changes on our own development machine, then push to origin freecen_parsing, and then test on test2.  We haven't really had any formal code review before committing changes to the git repository, although a few times have had each other look something over informally, and I assume we all sort of keep tabs on what is being committed at a high level (commit messages) even if we don't review the code itself.  For major work, sometimes a new branch has been started for that work (primarily from master, I don't think we have branched freecen_parsing at all).

Now that there are more of us, and especially now that we will have a production FreeCen deployment, maybe bring this up in the scrum tomorrow and we can get @benwbrum 's opinion of how to best communicate going forward to avoid accidental deployment of code that isn't finished being tested.  We will also want to get @Captainkirkdawson 's opinion once he is back for how best to coordinate for FreeReg.
