### ISSUE TITLE
Piece shown in report that not online, but it is.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1726]
Chris Mahoney reports
"Picked up on something odd when I checking on a particular piece today.
If you refer to the link below which brings up the list of pieces for Gloucester 1841, it show that for piece HO107_354A that it is not online https://www.freecen.org.uk/freecen2_contents/display_pieces_by_number?census_year=1841&county_description=Gloucestershire&locale=en&order=name&place_description=all
However, for this piece, I can see in my list of files that it has been 
incorporated, and if I were to do a search for entries in the piece, 
they are showing up in search results with full details of the household 
available when the view button is clicked.
Am wondering if this is simply a one off, or if there are other pieces 
out there which show that they are not uploaded but are actually there."

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I looked at the underlying data for this piece (GLS HO107_354A) and the status
 was indeed blank. I am not entirely sure how this could have happened but think perhaps it somehow got unset when a VLD or CSV file was deleted after incorporation of the latest CSV file. Currently I cannot find any other such occurences, so think it might be a one off.  I have now corrected the status for this piece (see screenshot below). If we do notice a reoccurence I'll have to investigate further. 

<img width="1641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ece07e3e8fac883f6c4cb7a10e12e242ba7af7e/Screenshot%202024-04-14%20at%2012.02.55.png" alt="Screenshot 2024-04-14 at 12.02.55.png" />

**Comment by Vino-S** [comment]
Made the changes in LIVE data. @cmahoneynz could you have a look please

**Comment by cmahoneynz** [comment]
Records page for GLS 1841 now correct.

Just did a check on all other counties I coordinate in years which are fully transcribed, and found one other that has been uploaded, and incorporated with the website able to show entries from the piece in search results (with correct piece number of RG12_4611A showing), but the records page is showing that it has not been uploaded.

This one being FLN 1891 Piece RG12_4611A.  Piece originally uploaded as a VLD, since split into their correct parts, and uploaded as CSV's.  Other two splits of the piece on their relevent records page (DEN, and CHS) are showing that those parts have been uploaded.

**Comment by AnneV-Learn** [comment]
@cmahoneynz Ok Chris I think I have sorted  'FLN 1891 Piece RG12_4611A' now too. Please check when you have time.

**Comment by cmahoneynz** [comment]
Records page now showing this one as being uploaded
