### ISSUE TITLE
Handle INC birth counties

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#174]
We need to modify the INC counties mentioned in #169 and #170 and reload those files.

**Comment by AlexAvlonitis** [comment]
https://github.com/FreeUKGen/MyopicVicar/pull/1026

**Comment by benwbrum** [comment]
Excellent!  I've merged the pull request, so the next step is to deploy on production and re-process the bad files.

**Comment by AlexAvlonitis** [comment]
thanks Ben, i'm currently testing it on vervet, the 'bad' files are more than 10, every time i re run it, more are popping up, so i'm wondering what's the best way to approach this.

**Comment by richpomfret** [comment]
Doug to deploy.

**Comment by dougkdev** [comment]
@AlexAvlonitis , good work on the initial fix for INC counties, it worked for nearly all of the files. It looks like we do still need to make sure INC is fixed in the other field (should be done for both transcribed birth county and the corrected birth county). FC1 fixes both fields and we should, too.  Once the code is fixed for the second field, there are just a handful of VLDs that will need to be reloaded.

**Comment by dougkdev** [comment]
deployed and reloaded the .VLD files that had INC in the other field.
