### ISSUE TITLE
Address performance on FreeCEN2

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#177]
http://freecen2.freecen.org.uk/ seems to be a bit slow.  Let's figure that out.

**Comment by dougkdev** [comment]
Some of the slow response is due to asset loading and also the double-loading of some assets (see FreeReg issue #915) and may be able to sort some of that out while dealing with #152.  However, initial connection/response and responses in general also seem quite slow compared to FreeReg.

**Comment by richpomfret** [comment]
To contact Lemon and clarify if this might be related to apache loading.

**Comment by dougkdev** [comment]
In scrum we discussed the initial response lag of about .75-1.25 seconds that I had been seeing and @Captainkirkdawson mentioned there had been a similar issue with Reg that was resolved a couple of years ago by Lemon configuring Passenger to pre-load the rails application. I communicated with Lemon and he informed me that it had already been done for FC2, too. He indicated that he was not seeing the issue on production, so if only on vervet probably just due to processes getting swapped out.  I had discovered this delay on vervet, and double-checked and indeed do not see the issue on production, had only seen it on vervet, so the particular portion of the performance investigation related to the small delay before data transfer begins is resolved. Additional investigation needed for next comment.

**Comment by dougkdev** [comment]
At 11:57 on 2016-12-21 @DeniseColbert reported that "FreeCEN2 is taking up to / around 1 minute to load pages." I was unable to reproduce the problem about an hour later.  The bmd build is going on, so perhaps there had been some resource-contention related to that at the time when Denise was experiencing the issue?  As first point of investigation, I will communicate with @Captainkirkdawson about whether bmd builds usually cause degradation with Reg at all.

**Comment by DeniseColbert** [comment]
Re. reproducing the issue, Pat and I experienced this on 19th Dec at around 10am GMT also. Upon trying now,  one or two pages took a couple of seconds to load, most were fine.

**Comment by Captainkirkdawson** [comment]
Responding to @dougkdev email but in this thread.
Attached is the performance of Cen on colubus for the past 60 minutes 
![cen](https://cloud.githubusercontent.com/assets/2874694/21395849/4f909eee-c75b-11e6-8eb7-0f501e164096.JPG)
Also attached is the REG performance over the same period
![reg](https://cloud.githubusercontent.com/assets/2874694/21395877/6c8e8ccc-c75b-11e6-977b-a7d8a8959503.JPG)

What is clear is that there is no issue with REG as far as loading rails is concerned BUT there is for CEN.

**Comment by Captainkirkdawson** [comment]
I always see time spent loading ruby with CEN.
Are the assets for CEN precompiled? Is the app set up to use precompiled assets with apache delivering them?

**Comment by Captainkirkdawson** [comment]
There was a performance peak on REG at the same time as "At 11:57 on 2016-12-21 @DeniseColbert reported that "FreeCEN2 is taking up to / around 1 minute to load pages."
![reg1](https://cloud.githubusercontent.com/assets/2874694/21396243/c761b484-c75c-11e6-9c72-3406f7eb9590.JPG)

**Comment by dougkdev** [comment]
Thank you, @Captainkirkdawson . I did precompile assets and believe we are properly set up to use precompiled assets and have them served by apache, but will double-check to make sure I didn't miss something. Also, I notice the CEN 07:20 request (immediately after a previous request) had no ruby load time.  Lemon mentioned ruby processes maybe getting swapped from memory to disk when they haven't been used for a while.  Will need to investigate with a higher amount of traffic to know for sure whether ruby load time is only when it has been a while since a request or whether the 0 ruby time at 07:20 was a fluke.

**Comment by Captainkirkdawson** [comment]
When we restart REG on production there is a very noticeable delay in respon se for the first user. It seems that passenger takes 30-60 seconds to load the new ode into the server. Once there response is extremely good. .I normally do a search following a restart just to get the load underway.

**Comment by Captainkirkdawson** [comment]
I ran a number of searches on production (brazza) performance was slower but still very good.

After the initial load, response was good. I did notice someone else was doing cen searches at the same time  (howler)
![cen2](https://cloud.githubusercontent.com/assets/2874694/21410300/c8245e4a-c79c-11e6-8058-35cd2ff5b77c.JPG)

**Comment by Captainkirkdawson** [comment]
REG performance on brazza at the same time was quite similar
![reg2](https://cloud.githubusercontent.com/assets/2874694/21410343/1d21894a-c79d-11e6-8584-9144410d44c9.JPG)

**Comment by Captainkirkdawson** [comment]
ruby performance is similar. Mongodb is similar brazza was responding to significantly more requests from REG than CEN but there were no issues that would concern me

**Comment by dougkdev** [comment]
Just a few minutes ago at about 00:18 GMT, I visited freecen2 and it hung for over a minute before initial page load. After first load, it was fine on subsequent page loads. My session cookie indicated that I was on colobus.  Similarly I had about 1-minute hangs with initial visit to howler and saki, followed by normal load times for subsequent requests on each.  Brazza and drill didn't exhibit the same initial lag.

I do not know whether each server was visited after deploying most recent code changes.  @AlexAvlonitis , do you remember whether or not you visited each server after your most recent update/reload?  If you didn't, that probably explains the slow initial load, but if you did, a minute seems really long to just be getting swapped back into memory from disk (although all disk access on production is much slower than I would have anticipated).  Here's a quick linux command for hitting a particular server after an update without having to mess with the cookies in your browser to make sure you visit them all:

wget -O /dev/null --header="Set-Cookie: freecen2-session=brazza" freecen2.freecen.org.uk

**Comment by Captainkirkdawson** [comment]
That's how long it takes to get passenger to reload the app (~1min)

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by dougkdev** [comment]
howler at 5:20 am 4 Jan. first request ~1 min, subsequent requests ~10sec. A couple of simple searches took somewhere between 30 sec and a minute.

**Comment by dougkdev** [comment]
brazza at about 5:30am GMT 4 Jan. first request 4 min 17 sec!  Second request 1 min 10 sec.
Need to check with @Captainkirkdawson  to see if indexes are currently being deleted for freereg story number 465, if so that might explain it.  Perhaps also resource contention from normally scheduled updates.

**Comment by richpomfret** [comment]
To investigate further - include Lemon in discussions.

**Comment by Captainkirkdawson** [comment]
WRT brazza. The nightly update of FR started at 05:00 GMT. It had a big impact on FR. Due in part due to the 35 indexes we are carrying as part of the transition. Based on the CEN scrum chat the following is the server loading at that time.
![brazza](https://cloud.githubusercontent.com/assets/2874694/21652499/0e8a4264-d26a-11e6-87f9-52befebd004b.JPG)
From that you can see that there was major disk contention at that time.
