### ISSUE TITLE
307808132 Invalid text in gazetteer? (Ali)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeCENMigration#1813]
Issue reported by **AH001** at 2024-10-02 14:15:32 UTC
Time: 2024-10-02T13:15:52+00:00
Session ID: eab012a4b15dd704af68bfc41e5c927b
Problem Page URL: [/freecen2_places/66fd2f20b18f7cf8bfbaef57?locale=en](/freecen2_places/66fd2f20b18f7cf8bfbaef57?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/66fd2f20b18f7cf8bfbaef57/edit?locale=en](https://www.freecen.org.uk/freecen2_places/66fd2f20b18f7cf8bfbaef57/edit?locale=en)
Reported Issue:
Invalid text allowed in gazetteer but not in csv??, although place is in gazetteer it is shown as a warning, ie not in gazetteer, in csv.

Sweden Soderhamn    

![Screenshot](https://www.freecen.org.uk)

**Comment by geoffj-FUG** [comment]
I do not understand the problem here.

 

The invalid text is presumably the dots over the o in the place name. The anglicised version is also recorded. A search to match a place of birth will presumably match the anglicised name.

 

We are aware that UTF8 has not been implemented on the csv collection. There is a story that covers this. 

 

Characters that are not currently recognised are appearing in the Gazetteer and that is deliberate. Irish names in particular require this to be able to record the Gaelic name. We are collecting these names so that the Gazetteer is comprehensive and will not need to be revisited.

 

In this case the place name is in Sweden and the letter o is recorded correctly.

 

This issue will be addressed during development of POB searching as UTF8 is implemented.

 

Geoff

**Comment by geoffj-FUG** [comment]
I do not understand the problem here.

 

The invalid text is presumably the dots over the o in the place name. The anglicised version is also recorded. A search to match a place of birth will presumably match the anglicised name.

 

We are aware that UTF8 has not been implemented on the csv collection. There is a story that covers this. 

 

Characters that are not currently recognised in csv and vld files are appearing in the Gazetteer and that is deliberate. Irish names in particular require this to be able to record the Gaelic name. We are collecting these names so that the Gazetteer is comprehensive and will not need to be revisited.

 

In this case the place name is in Sweden and the letter o is recorded correctly in the Gazetteer.

 

This issue will be addressed during development of POB searching as UTF8 is implemented.

 

Geoff

**Comment by geoffj-FUG** [comment]
The decision that the implementation of UTF-8 should be progressed (#1655) confirms that the characters in Gaelic, Scandinavian etc alternative names are correct. 
T believe that this story should be closed.
Geoff

**Comment by DeniseColbert** [comment]
Closing
