### ISSUE TITLE
Programmatic creation of parms info

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#195]
In FC1, for each new year/county, someone has to manually look at the corresponding information on the national archives website and manually create a specifically-formatted .csv file with the information for each piece in that year/county, then convert the completed .csv into a PARMS.DAT file to be used by FreeCen. The process is time-consuming and it is easy to make mistakes.

It may be possible to crawl the national archives site once, automatically parsing the necessary information to be ingested once into freecen2 so that Brenda and her coords do not have to continue manually entering the information for each new year/county/piece.

We would need to check the archives' robots.txt file to see if they allow indexing of their site, and also look at the format of their pages to see if directly parsing the data is practical.

Economic 0, urgency 6, strategic 8, size ?6 _P=20

**Comment by richpomfret** [comment]
Issue with amending rather than creating a new file - specifics for this error sent over email. Awaiting Doug's input.

**Comment by FreecenBren** [comment]
Just to clarify. We have 2 Issues with PARMS in FreeCEN 2.

1. The issue is with creating a new PARMS file using FreeCEN 2. (Waiting
for Doug to return)

2. Trying to delete a specific PIECE number in a current PARMS file.
We can amend details within a PIECE number, but cannot delete a PIECE
number.
These mostly relate to the Records that were lost over 100 years ago before
they reached the National Archives.
Doug suggested we could possible mark the number as "Data lost" instead.
Therefore the system will not need to account for it when all the other
PIECES for that Census Year x County are complete and will then show as
100% done.

We can however still use the FreeCEN 1 current system for the time being.

Brenda

**Comment by PatReynolds** [comment]
See email to Richard Light 10/3/2017 for suggestion that we may already have this data

**Comment by FreecenBren** [comment]
Update.
Richard has done all the PARMS using the NA as Doug described.
I am in the process of editing them as one column has only 21 digits to use
so some places have to be reduced to fit.
There should be some ready to send to Lemon hopefully in the next few weeks.
There are quite a few of them.
In fact Richard did everyone for all the Census Years including 1881 that
are not as yet on the database.
The problem with London/Middlesex/Kent etc  re earlier  Census I will leave
till the last.

**Comment by PatReynolds** [comment]
This only got the PARMS files into FC1 (and Brenda still converting from CSV to DAT and giving to Lemon for uploading) - need them also in FC2

**Comment by PatReynolds** [comment]
The (unedited) files need adding to FC2.

**Comment by PatReynolds** [comment]
Will the edited field need bulk converstion to the actual place names in order to be properly displayed / used on FC2, link with Pelagios, etc.?

**Comment by Captainkirkdawson** [comment]
@Vino-S is currently working on the upload of theparms file to CEN2

**Comment by Captainkirkdawson** [comment]
Upload no longer required and we are evolving towards a fixed parms/piece structure based on TNA. See #833 Suggest this be closed
