### ISSUE TITLE
Add in google analytics

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#197]
Ensure we have code implemented across all pages.

**Comment by DavidVerne** [comment]
Thanks Rich. It seems Bev has done this. I'm still not able to access any data, so just looking through my settings to figure out why.

**Comment by dougkdev** [comment]
FreeCen2 currently uses the analytics id 'UA-71283391-1'  If there is a new analytics id since that was set up, just let one of the developers know what the new id is and a developer can update it in application.html.erb  Or, could it be that the site has not yet been verified (see the other story regarding google site verification key)?

**Comment by PatReynolds** [comment]
UA-89287207-1 is the code for freecen2.freecen.org.uk - to be implemented if it is not already, on all pages
(UA-71283391-1 is the code for www.freecen.org.uk)

**Comment by israelriibeiro** [comment]
@PatReynolds , could someone test this  [code](https://github.com/FreeUKGen/MyopicVicar/commit/0fb7353cb46fa3f78d58244bbf1b9dc2a7600eca) ?

**Comment by PatReynolds** [comment]
It doesn't seem to be working (is it live on test2?)

**Comment by israelriibeiro** [comment]
@PatReynolds , @dougkdev  could you deploy it in test2?

**Comment by DeniseColbert** [comment]
Has this been deployed in test2? If so, the code doesn't appear to be working. Added Mike (our analytics volunteer) to contribute

**Comment by MikeLi1** [comment]
Just in case you need the universal google analytics tracking code. Google specifies that in order to get the full benefit of that we need to implement it on every page of the site:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89287207-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by israelriibeiro** [comment]
Is it not working or it was not deployed?!

**Comment by DeniseColbert** [comment]
@dougkdev can you confirm if deployed?

**Comment by dougkdev** [comment]
It is not deployed.  @Vino-S will you merge/test/deploy Israel's pull request?  @israelriibeiro , Vino is a full-time developer, whereas I have been mostly phased out of the projects. Going forward it is better to ask her instead of me in order to get a more a timely response, thanks.

**Comment by richpomfret** [comment]
To add into every page (currently it's only on search page). To also check/test real time analytics as unsure if this is working or not.

**Comment by MikeLi1** [comment]
Just a heads up. Google Analytics is not installed yet.

**Comment by Vino-S** [comment]
I have made few changes in code and deployed it in test2.  Could someone test it and let me know whether it is working?

**Comment by richpomfret** [comment]
@dougkdev to deploy/roll-out (which should fix it).

**Comment by richpomfret** [comment]
Working fine.
