### ISSUE TITLE
Search results page hard to read on mobile / missing info

### ISSUE THREAD

**Issue by draagc** [FreeUKGen/FreeCENMigration#198]
The search results table is quite hard to read on mobile as there are no borders between the rows.

Also, there is some missing info on mobile devices. 

Have a look at the following document for more details.

https://drive.google.com/open?id=1MwU3rcLTgRDx53wqYWoDwRqEW2VMZzmZG-giiKUy2rs

**Comment by AlOneill** [comment]
Ah! Looks like the mobile view has not been fully edited for FreeCen -- it retains some FreeReg labelling as well as missing specific FreeCen fields.  

I note that it is table-based rather than list-based as on FreeReg -- may or may not be an issue. If we keep the table format, then I suggest "Field" and "VALUE" are dropped as column headings, with each first column cell marked up as `<th scope="row">`.

Mobile view needs additional editing for disability accessibility (tooltips, for example).

**Comment by richpomfret** [comment]
Let's flesh out the tasks involved in making mobile view 'fully edited' and discuss table-based vs list-based. Thanks both!

**Comment by richpomfret** [comment]
Doug/Rich to review.

**Comment by dougkdev** [comment]
ok on my android phone
