### ISSUE TITLE
ability to reliably contact all volunteers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#220]
Implement message system to allow mailouts to all or a subset of volunteers and/or Registered Researchers -   including Bounced emails set invalid email address flag

**Comment by dougkdev** [comment]
I saw this got assigned to me yesterday, but I'm afraid I'm a little behind the curve on this story.  Is this the same or different than the messaging system in Reg? (Are we just making sure code that has been merged from master is similarly working in FC2? or is this a different set of requirements?)  Also-- I looked for similar story /discussion in FreeReg about what has been done as far as bounced emails setting invalid email address flag, but did not find it. I am certain I have previously seen such discussion going around, but at a loss as to where it was.  Can you point me to the previous discussion so I can come up to speed on what has already been done along these lines for Reg? Thanks

**Comment by PatReynolds** [comment]
Yes, it's the FreeREG system that we are bringing into FreeCEN.  Yes, it's got issues, but without throwing money we don't have at the problem, we haven't come up with a solution yet.  The set-email-to-bouncing code is there it is issue #989

**Comment by dougkdev** [comment]
Thanks, both. I will need to have a closer look at what has been done with #989, etc.

Did some initial work on this story to make app-specific changes to what was merged from FreeREG to use the same code on FreeCEN: Set up to use app-specific text and sending address,  made a couple cosmetic changes with the tooltips on the message creation form. Fixed a tiny bug that would cause a crash any time an attachment was added without a filename extension or a filename extension that didn't match those permitted. Discovered, but did not fix a probably very low-priority bug where it crashes instead of flash notice if a message no longer exists (such as if the user logs in, then the message gets deleted from system between the time the user pulls up their list of messages and the time they view the message).  Not sure that would actually happen much in practice.

The minor changes I made so far are on test2, not yet deployed to production, and so far only tested with an email trap (redirecting all outgoing messages to my own address). However, seems to be working and in the same state as the FreeREG message system.
