### ISSUE TITLE
Review build performance

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#223]

**Comment by dougkdev** [comment]
Made some improvement.  It is building on test2 (in the background) at about the same rate as last time we built, so no longer a concern.

**Comment by dougkdev** [comment]
While the build looked like it was progressing at about the same speed as our previous build when I compared the time for CON (perhaps even faster), it looks like it is significantly slower now that we are toward the end. There are of course more VLD files now than last time, but not so many more that it should account for how much extra time it is taking.  I believe it took about 2.5 days when we built in November and looks like it will complete in about 4 days this time.

I did some observations using mongotop with a few pieces in WAR. The first 10%-15% of the total time is spent creating the vld_entries; 14%-23% is dwellings/individuals/pieces.  The majority of the time is spent creating search records (65%-80% of the total time).  mongotop shows mongo as quiet for a few (4-7) seconds before the printout of how many dwellings and entries were loaded, perhaps while it catches up from all the writes and index updates?  These timings were done on relatively large pieces, for example WAR/RG12239.VLD has 7854 individuals in 1653 dwellings.

Since the build just runs in the background and is not done often, nothing further needs to be done as long as we can plan on about 4 days of build time for the final build before launch (and any future builds).  If 4 days is too long then additional developer time will need to be spent trying to improve build performance.

**Comment by FreecenBren** [comment]
I am concerned also that you mention  a Piece for WAR of 7854 individuals
as being relatively large.
We have been uploading pieces just lately more than double/treble + that,
 i.e. 15,000 + individuals and a couple between 25,000 to 31,000+
Will that size have any further impact on speed/time?

**Comment by dougkdev** [comment]
You are right, Brenda. These with 7,000 definitely aren't the largest.  Just "relatively" large compared to many pieces that only have a few hundred or couple thousand entries. And in fact, perhaps because some of the more recently added pieces do have 15,000 - 31,000+ entries, that actually might account for part of the reason why the build is taking longer.  Even if there haven't been enough new files to account for the longer build time, perhaps if the new files are much large than typical, the overall increase in number of entries to add to the database may account for the longer build time more than I suspected.  Thanks.

**Comment by dougkdev** [comment]
timing on  my development machine (with a nearly-empty database) to process WAR/RG122399.VLD:
load/parse/errorcheck:  2 seconds
vld_parser persist_to_database: 21 sec
transform: 38 seconds
translate: 40 seconds
total time to process: 101 seconds

**Comment by benwbrum** [comment]
I have switched vld_parser/persist_to_database to use bulk inserts, and found it drops a sample file from 23 seconds down to 7.  cf 79f0864636e8005b3ad8593a21737ae234a2cf4c

I'm not sure that we can take the same approach with transform and translate, but will look into that as well.

**Comment by dougkdev** [comment]
The majority of the time was spent in translate (creating the search records) so if we can do bulk inserts there, that would give the biggest performance gain on the database build.
