### ISSUE TITLE
Search fails, and redisplays with information button text distplayed poor layout

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#226]
This is on Chrome and Edge

**Comment by DeniseColbert** [comment]
![image](https://cloud.githubusercontent.com/assets/19173257/24348029/3adf7516-12d2-11e7-967b-d11dd4d56094.png)

**Comment by DeniseColbert** [comment]
Chrome:

![image](https://cloud.githubusercontent.com/assets/19173257/24348093/6b629aec-12d2-11e7-91fb-d1ab229cb004.png)

**Comment by richpomfret** [comment]
What platform was this on/resolution?

**Comment by PatReynolds** [comment]
I am still getting this (chrome) with https://freecen2.freecen.org.uk/search_queries/new but it is fine with https://freecen2.freecen.org.uk.  Failure of search more important than redisplay of form issue - please could this be checked/addressed urgently @Vino-S

**Comment by FreecenBren** [comment]
I cannot search for anything on https://freecen2.freecen.org.uk/search_queries/new

Always get this message.

We encountered a problem completing your request. Please resubmit. If this situation continues please let us know through the Contact Us link at the foot of this page

 

Same search on https://test2.freecen.org.uk/search_queries/  and I get a result.

This has been the same since last week when I mentioned it.

 

Brenda

**Comment by dougkdev** [comment]
The form display issue is because the .css styling files are sometimes not being loaded.  Sometimes returning 404 Not Found for the files, even though they exist on the server.  It looks to me like the load balancer is not correctly directing browser requests to the same server throughout a session. That could definitely cause the styling problem and maybe also the search problem (if the search result is on a different server than the page trying to display the result).  I will contact @lemon-ukgen to see if that is indeed the case and work on a resolution if it is.

**Comment by dougkdev** [comment]
I have emailed @lemon-ukgen about the load balancer.  That does appear to be the issue for both the search failure and the styling / missing css.  When I bypass HAProxy with direct access to one of the servers, the assets and search result are both fine.

**Comment by dougkdev** [comment]
see also #227  (freecen2-session cookie does not expire)

**Comment by dougkdev** [comment]
Thanks @lemon-ukgen . Fix confirmed.
