### ISSUE TITLE
Yorkshire records not found in Ridings

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#237]
A search for Nicholas Alcock 1700 1900 in place of birth 'North Yorkshire' finds 0, but in the whole of Yorkshire finds several (all in North Riding).

**Comment by richpomfret** [comment]
Quickest fix would be to remove option of searching in anything but 'yorkshire' i.e. remove north/east/west (riding). We can then readdress further down the line.

**Comment by PatReynolds** [comment]
Confusion on a suggestion for FreeBMD lead to question: does having Yorkshire AND ridings (etc)confuse people?  Need to monitor what feedback (if any) we get for absense of ridings in the search at launch, maybe add a survey.

**Comment by edickens** [comment]
We had this problem in FreeREG.  In the end we had to program the search options for it.  Researchers do not always know which Riding a Place is in, or for some, not even what is a Riding.
![capture](https://user-images.githubusercontent.com/8876165/27732614-ffd85520-5d89-11e7-808b-4169a3546c43.JPG)
York is difficult as it seems to span a number of Ridings.  We have it in the North Riding.
Birmingham and Bristol are also places which span different Counties, so we have gone for the County they were in when registration started in 1530,  This would not apply to FreeCEN or FreeBMD.
ED

**Comment by PatReynolds** [comment]
York is (technically) not in any riding.  It was a county in itself (and the County Town of undivided Yorkshire) It is now a unitary authority. Postally, it has been associated with North Yorkshire, but the deanery is York and West Yorkshire.  Personally, I'd say it was historically correct to list York separately from the ridings, or label the group North Yorkshire and York.

**Comment by PatReynolds** [comment]
Upon further investigation: it appears that the FreeCEN1 data has the code for Ridings, but this is replaced in FC2 with the YRK code - see https://docs.google.com/document/d/1GASFYeHV578KA69U_eiAymvIx190IBZHPg-v2o5ivNc/edit?usp=sharing for details.  Riding code needs to be brought across into FC2, and a search for place of birth as 'Yorkshire' should search all three riding codes (or are there four codes?)  A search for John Smith born York in the 1891 census shows that two are coded to North Riding, and one to Yorkshire..... I am not sure whether the County is being YWYS or interpreted.

**Comment by FreecenBren** [comment]
The Chapman code is not YRK it is YKS

 

Brenda

**Comment by PatReynolds** [comment]
TY Brenda, amended.

**Comment by richpomfret** [comment]
Is this still in-progress, @dougkdev?

**Comment by benwbrum** [comment]
We had a long discussion of this on the call as follows:

## Problem

Although in FreeREG, all Yorkshire records are encoded by Riding, FreeCEN data includes vaguer Yorkshire records, in which the enumerator only wrote down "Yorkshire" -- especially for birth county.  As a result, data in FreeCEN may be encoded as `YKS` in addition to `ERY`, etc.

## Proposal

Since we cannot deliver accurate searches by riding (as someone born in `NRY` may be encoded `YKS`), we should only allow queries for Yorkshire, hiding any riding-specific searching.  These Yorkshire searches will search for records encoded as any of `["YKS", "NRY", ...]`

**Comment by dougkdev** [comment]
@richpomfret yes this is still in progress, this is the one I emailed you about before the scrum that I had just begun to look at. Unfortunately I mis-typed the number (as #137 instead of #237) in the body of the email, sorry for the confusion.

**Comment by dougkdev** [comment]
Are we removing the ERY, NRY, WRY only from the birth county selection, or also in the census county? (We do have the riding information for census county, it is only birth county that we often only have "YKS" in the data instead of a specific riding).  We could remove the selection for the ridings in both places for consistency, or we could keep ERY, NRY, WRY, and YKS (all) for census county to facilitate the more specific searches when the user knows which riding they want to search.

**Comment by FreecenBren** [comment]
Whatever is decided by removing the Ridings from the POB for the search I
hope it does not have any impact when we upload the VLDS for the Ridings?
Silly question I know but just checking.
As long as the researcher when they select a birth place of YKS, the search
facility will use all 4 CHP's WRY, ERY, NRY and YKS in its search.
I prefer the 2nd option of keeping the Census County.
B

**Comment by dougkdev** [comment]
Won't impact uploading of VLDs, the data will still be the same as it is now. The change will just be to the query form. Birth county will have only YKS as an option and if YKS is selected, the search will return results of data with birth county listed as any of: YKS, ERY, NRY, WRY.

**Comment by dougkdev** [comment]
Removed ERY, NRY, WRY from the birth county list (YKS searches them all, plus anything just marked in the data as YKS for birthplace). Left ERY, NRY, WRY, and YKS (to search them all) in the list for census county as preferred by Brenda. Deployed to test2.

**Comment by dougkdev** [comment]
deployed to production, ready for user test
