### ISSUE TITLE
Researchers can leave bouquets

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#250]

**Comment by geoffj-FUG** [comment]
What is the purpose? Given that many transcriptions (and all in FC1) are anonymous we cannot get them back to the transcriber.
The best we can do is have some way of receiving comments such as the trip advisor star rating and comment system and include them in the Newsletters. That leaves the door open to abuse because it will need to be transparent.
Geoff

**Comment by geoffj-FUG** [comment]
See story #1454. This story will be resolved by story #1454.
Geoff

**Comment by geoffj-FUG** [comment]
See story #249.
If we make the newsletters available we could have a link under the same Newsletter menu item to allow researchers to leave comments. 
Geoff

**Comment by DeniseColbert** [comment]
Superseded: closing
