### ISSUE TITLE
Launch: Add message to FC2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#262]
"FC2 is a work in progress; we want your criticism so that we can make it better"

Duration: From day 1 of launch to point where we don’t want to ask for/ encourage more feedback

**Comment by PatReynolds** [comment]
I would say "feedback on all aspects" rather than "criticism"

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by DeniseColbert** [comment]
Message: "FC2 is a work in progress; we want your feedback on all aspects so that we can make it better"

**Comment by PatReynolds** [comment]
:-)

Pat Reynolds
Executive Director, Free UK Genealogy

On 15 Jun 2017 12:33 p.m., "DeniseColbert" <notifications@github.com> wrote:

Message: "FC2 is a work in progress; we want your feedback on all aspects
so that we can make it better"

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FreeUKGen/FreeCENMigration/issues/262#issuecomment-308705154>,
or mute the thread

**Comment by PatReynolds** [comment]
@DeniseColbert to create survey

**Comment by richpomfret** [comment]
@PatReynolds We now have a message implemented - so let's change this to 'done' and create a new story relating to any new task i.e. creating/adding a survey.

**Comment by PatReynolds** [comment]
Agree - will close. Story #276 is in progress.
