### ISSUE TITLE
Enhance volunteer recruitment

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#268]
Can we put a form in the members area to collect feedback?

E0 U3 S5 C6: P14

**Comment by DeniseColbert** [comment]
Form drafted, but improvements needed. 

Embed code for the form:

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfipOs-MRSbfdQ9gCml7CeePzomLzFLcmU9Zg18bQ-EQ8yO6g/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

Link: https://goo.gl/forms/zEKBuoHVRYnHTP8j1

**Comment by smrr723** [comment]
Adding myself to this for developer-specific things I've spotted that need doing.

- Add "topics" to the Github repository header section (ruby, rails, mongodb, etc) to make it easier for volunteers to find us - DONE
- Update website link in Github repository header - DONE
- Consider replacing `Actor: technician` label (unclear ATM and largely unused) with `developer`, `front-end`, 'back-end` labels to make issues easier to spot - Have added developer label for now to most applicable issues
- Update the README & CONTRIBUTING.md files - I've seen a few devs not able to progress because they've been confused about the location of the FreeCEN code, so I will edit these to add some clarification. - TODO

**Comment by smrr723** [comment]
Would also suggest to assist new developers or any other volunteer picking up Github issues, that someone needs to go through the current list and remove transcriber jargon/abbreviations as much as is possible to add clarity.

**Comment by Captainkirkdawson** [comment]
Is this still  a requirement it has been inactive since smrr723 left

**Comment by PatReynolds** [comment]
@DeniseColbert to check state of play with this.

**Comment by DeniseColbert** [comment]
It seems there's only this left to do: Update the README & CONTRIBUTING.md files - I've seen a few devs not able to progress because they've been confused about the location of the FreeCEN code, so I will edit these to add some clarification. 

@Vino-S , could perhaps one of the new volunteers you're working with review the above-mentioned files and improve/fix? Do you think it might be an appropriate/revelant task for them?

**Comment by Captainkirkdawson** [comment]
@jayto581 updated the CONTRIBUTING.md file 6 months ago; so is up todate.

**Comment by DeniseColbert** [comment]
Thanks Kirk, in this case I think it can be closed then.
