### ISSUE TITLE
FC2 Feedback: Angus 1841 database coverage page shows many places not online, yet the coverage graph is 100%

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#318]
Possible bug?

**Comment by DeniseColbert** [comment]
AFAICT the database coverage page shows all 1841 is online: https://freecen2.freecen.org.uk/freecen_coverage/ANS

**Comment by FreecenBren** [comment]
https://www.freecen.org.uk/coverage-ANS.html#1841

FreeCEN one says it is all complete for 1841. See above link.
I will compare the two.

**Comment by FreecenBren** [comment]
A few months back we had an issue with some VLD for Angus. Due to the names
not matching the PARMS.
They were then deleted and the correctly named VLD,s were uploaded.
Looking at the FC2 numbers and percentage graphs they appear to show the Up
and down movement.
That explains the fluctuation. The quantities for FC1 and FC2 are identical

FreeCEN does not have that problem as I asked Lemon to delete them ABD sent
the replacement.

**Comment by richpomfret** [comment]
Appears fixed.
