### ISSUE TITLE
FC2 Feedback: Too much white space

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#337]
#1) 
The results of a search in FreeCen2 take up too much screen space, for my tastes. A simple spreadsheet-like layout would be my choice without all the horizontal lines and triple-spacing -- it also makes a 'print screen' more useful.

#2)
The results of a search in FreeCen2 take up too much screen space, for my tastes. A simple spreadsheet-like layout would be my choice without all the horizontal lines and triple-spacing -- it also makes a 'print screen' more useful.

**Comment by richpomfret** [comment]
Can you clarify @DeniseColbert ?

**Comment by PatReynolds** [comment]
need to find out what devices, and try some mockups.

**Comment by edickens** [comment]
We had the same comment when we started FR.  The open text was said to be more readable on tablets and other devices.  But we did request that the Members' area had a different configuration with much tighter text so that the amount of scrolling is reduced.

**Comment by richpomfret** [comment]
To review once accessibility changes have been made and all such updates have been completed. To return to.

**Comment by richpomfret** [comment]
Thanks Denise. Let's focus on finding where this happens on the search results page, different examples of it and then we can explore elegant solutions to it.

**Comment by richpomfret** [comment]
Potential task for a volunteer who specialises in UX?

**Comment by PatReynolds** [comment]
See also FreeREG 1360

**Comment by AlOneill** [comment]
The ideal amount and location of white space on a page is as much to do with comfortable reading (amount of concentration needed) and meaningful associations (things that are closer together should be more closely related than those further apart) as the amount of scrolling needed.

Using a touch pad makes light work of scrolling, but perhaps mouse-users find it more troublesome.

**Comment by AlOneill** [comment]
Looking at a Search Results page, some of the problem at least is caused by the markup — it has become seriously unorthodox — the `div.container` and `main` element are being closed before the table even begins; the table is within an unnecessary/unhelpful `div.grid`and the widths applied to the columns are inappropriate, causing unnecessary wrap in some cells, and hence a lot of unnecessary extra white space in the row as a whole. The knock-on effects include not being able to access the whole width of the table in smaller windows/screens — horizontal scrolling has been lost.

The ERB files involved are rather complex, but I will take a close look and identify where the main issues are.

**Comment by AlOneill** [comment]
Should add that the buttons on the detail links will continue to add white space to a table row until the new colours are in place and we can revert to a simple link.

Markup issues located in ERB files and details sent to Vino.

**Comment by Vino-S** [comment]
Updated the markup of search_results ERB page as suggested by @AlOneill in Live Website.

We can change the Button of Detail to link as in FreeREG if needed.

**Comment by AlOneill** [comment]
@Vino-S  Thank you!

The big wobble in the table is down to the tooltips: a hidden tooltip is located to the right of where it will be shown. When we review for access, those particular tooltips will need to be replaced anyway: solution is not straightforward and will depend on how much information needs to be shown there, amongst other things. (Which is why we haven't fixed that now.)
