### ISSUE TITLE
FreeCEN favicon doesn't display correctly

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#34]

**Comment by dougkdev** [comment]
Problem: Because we are using several site-specific (freereg/freecen/freebmd) assets that use the same name, such as favicon.ico and some stylesheets etc., they could not all be included in the standard directories to be picked up by the asset pipeline without conflicting with each other.  The original solution was to put each set of assets in its own directory outside of the normal asset pipeline tree, and explicitly  add the corresponding directory to the asset path configuration.  This worked for most of the assets, but it did not work for the favicon image.  Due to the initialization order of the various parts of the rails app, the gems (including refinery-cms) get initialized after our configuration, and they insert their own paths in front of ours in the assets paths array.  As a result, the first favicon seen by the asset pipeline was the favicon for refinery, which prempted ours.

Solution: I fixed the problem by creating a rake task that copies the correct site-specific assets directly into the app/assets tree to be handled by the asset pipeline, preventing refinery's favicon from taking the place of ours.
