### ISSUE TITLE
FC2 Feedback: Ability to search all of (e.g.) Scotland, Wales

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#341]

**Comment by PatReynolds** [comment]
Need to know whether this can be done by 'Scotland' selects all Scottish counties, or does it need a database redesign?

**Comment by PatReynolds** [comment]
A birthplace search for Scotland should search the birthplace counties of Scotland, and SCT (also WLS for Wales and IRL for searches for Welsh or Irish births).  Also, possibly for English.  This is a facility on FreeCEN1, so I've added to the Essential Features epic (phase 1).  Could be phase 2, particularly if it involves other place develeopment.

**Comment by richpomfret** [comment]
@Captainkirkdawson we're reviewing this in connection with a more recent task - is there anything preventing us from doing this search function?

**Comment by Captainkirkdawson** [comment]
Performance as it means a search of 40+ chapman codes and a merge of results; likely most searches would either time out or produce too many results with surname only

**Comment by DeniseColbert** [comment]
Would it be possible if we required a forename?

**Comment by geoffj-FUG** [comment]
If you look at the Full Version of the FreeCEN Handbook there is a Chapman Code hierarchy. (not in the abbreviated version). This table has three levels of Chapman Codes. We already use level 2 chapman codes to search the Gazetteer and during validation, so for instance YKS (level 2) will find ERY, NRY or WRY places (level 3). Tjis table may be useful for this story.

**Comment by geoffj-FUG** [comment]
See my comment of story #238.
Geoff

**Comment by geoffj-FUG** [comment]
From a researchers point of view this is the search problem we discussed at the scrum 1 may 24

Geoff

**Comment by DeniseColbert** [comment]
@AnneV-Learn to investigate code that can be reused/repurposed and estimate size

**Comment by AnneV-Learn** [comment]
Yes this is relatively easy to code, estimated effort = 5 (i.e up to a day). Estimate is bit longer than I would have guessed because I actually found a bug in the existing Search functionality. 
**Problem Example** 

_Census County restricted:_
Searching for CROUCH Lydia (no other parameters) - yields 14 results - OK
 Searching for CROUCH Lydia Census County = CHI (Channel Islands) - yields 0 results - **Not correct** as there is one in the 14 above.
Searching for CROUCH Lydia Census County = DEV (Devon) - yields 1 result - OK
Searching for CROUCH Lydia Census County = CHI (Channel Islands) and DEV (Devon) yields - 2 results - OK
Searching for CROUCH Lydia Census County = CHI (Channel Islands) and WIG (Wigtownshire) - yields 0 results - **Not correct** as there is one in the 14 above, also on the Results page 'When you searched for:' Census County details, CHI is expanded to 'Alderney or Guernsey or Jersey or Sark' but Wigtownshire is not listed

_Birth County restricted:_
Searching for CROUCH Lydia Birth County = WIL (Wiltshire) - yields 2 result - OK
Searching for CROUCH Lydia Birth County = CHI (Channel Islands) - yields 1 result (Birth County = Alderney) - OK
Searching for CROUCH Lydia Birth County = WIL (Wiltshire) and CHI (Channel Islands) - yields 2 result - **Not correct** it is missing the CHI result above.

  I think I can see where the problem resides in the code but the User Testing of any changes I make to add the new functionality and fix the bug will have to be pretty thorough, so may take a while.

**Comment by AnneV-Learn** [comment]
Ready for Testing on Test3

**Comment by geoffj-FUG** [comment]
Searched with Elizabeth Jarvis OK
Elizabeth S Jarvis OK
Mary Caines OK including IRL entry
John Preece OK except HEF was included in ENG. It should also appear in the WLS results.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG The expansion of WLS to include HEF (and LND to include SRY, MDX and KEN) has thus far only been applied to Gazetteer searches. Should it be applied to Birth County and Census County in the main Search now?

**Comment by geoffj-FUG** [comment]
Let me put it to the FreeCEN Committee.

 

Geoff

**Comment by DeniseColbert** [comment]
The feeling in Scrum is that we should offer all places that have been part of the County/Country in the past

**Comment by geoffj-FUG** [comment]
Anne

I have discussed this with the scrum and the decision is that:
WLS will include HEF (as well as it being included in ENG)
LND will be Greater London for these search purposes. So it will include the Chapman Codes of MDX, SRY and KEN.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
LND to include Chapman Codes of MDX, SRY and KEN is a little problematic because LND is an **individual** chapman code not a Country group. As it stands at the moment if LND alone is selected for the Census County the list of Census Places will populate for selection because that list only poplulates if there is only **one** county selected.
How do you want this to work for LND? 
Treat as selecting the group of multiple counties and so Census Place options not available or populates the Census Places options with list made up from all places in LND, MDX, SRY and KEN?

**Comment by geoffj-FUG** [comment]
Anne

 

I am commenting from afar. Please say if I see things incorrectly.

 

If I am an Antipodean or an American, I would perceive London as being what makes up the modern Greater London. I doubt if I would recognise that there is an almost complete overlap with Middlesex and a partial overlap with Surrey and Kent.

 

I would therefore suggest that we treat it as selecting the group of multiple counties and places made up from all places in LND, MDX, SRY and KEN.

 

It is a shame that there is not a standard Chapman Code for Greater London. They re-used LND for the administrative area after 1974. If one had existed, we could have utilised that. I am not into creating one – we spent a lot of effort aligning things with the standard Chapman Code list.

 

Geoff

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG
Sorry still not entirely clear to me. It is the ability to choose a specific place via the Census Places list on the Search page that I am concerned with. 
So looking at the Search page if LND is selected as the Census County would you expect the ‘Census Places selection list’ on the Search page to be populated with a list of all places where we have data (census year in brackets) for LDN and MDX and KEN and SRY? 

Normally that Census Places selection list is only populated if a **single** County is selected. So if the Researcher selects KEN  and MDX or LDN and ESS (ie 2 counties) the Census places list is not populated (as the notes on the page say). 
So it would perhaps seem rather inconsistent. 
Whatever we do we will need to clarify/explain for the Researcher I think.

**Comment by DeniseColbert** [comment]
Decision in scrum: advise users (upon selection of London) that they should also try other counties in their searches for London

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG 
I have checked the code to make sure that LND is not 'expanded' as I wasn't sure how I had left it on **Test3**. 
I have added an informational 'Tip'  about Greater London - not sure if this will suffice, or if the wording is ok - see what you think - it is deployed **Test3**.

**Comment by geoffj-FUG** [comment]
It appears that we cannot do anything for London so this story is only about the other counties.

@AnneV-Learn I think they are all done other than LND. Please confirm.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG
Yes that is correct. Please test on Test3 as I have added a 'Tip' (below Nearby Places) about what to do if Searching London which you may or may not like.

**Comment by geoffj-FUG** [comment]
We have a problem with HAM / IOW.
We record POBs against IOW for places in IOW. However IOW is also part of HAM.
If I search for Sarah Jarvis IOW I get one result, birth place West Cowes. If I look for her in HAM she does not appear. I only get the HAM entries.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG updated code is now available for testing on Test3

**Comment by geoffj-FUG** [comment]
Oops. Wrote on wrongg story!

Geoff

**Comment by geoffj-FUG** [comment]
That looks good.

I checked CHI as well. All OK.

We can deploy.

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
