### ISSUE TITLE
Update donate link

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#415]
Link is now: https://www.freeukgenealogy.org.uk/help-us-keep-history-free/

**Comment by FreecenBren** [comment]
But if you are on the SEARCH  page at https://freecen2.freecen.org.uk/search_queries/new

 And you click on the Make a Donation button at the bottom  it does not take you to that address. “ Hover over the link below” 
• Contact Us
• Make a Donation
• Policies

It takes you to this one,

https://www.freeukgenealogy.org.uk/about/help-us-keep-history-free/

So that link needs changing

Sent from Mail for Windows 10

From: PatReynolds
Sent: 17 February 2018 15:15
To: FreeUKGen/FreeCENMigration
Cc: Subscribed
Subject: [FreeUKGen/FreeCENMigration] Update donate link (#415)

Link is now: https://www.freeukgenealogy.org.uk/help-us-keep-history-free/

**Comment by DeniseColbert** [comment]
I have fixed the link in the button on https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen

@Vino-S could you do the footer link please?

**Comment by FreecenBren** [comment]
Thanks Denise.
 Should this link have a picture of the donate button as it only has the
small text wording there.
Clicking on the text ‘Donate’ though does take you to the correct page.
Tested on my IPad

**Comment by DeniseColbert** [comment]
https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen does have the Donate button; do you mean the text on FreeCEN1? We do want the Donate button placed on FreeCEN1- it is on the FreeCEN1 waffleboard: https://github.com/FreeUKGen/FreeCen-1-Issues/issues/4

**Comment by FreecenBren** [comment]
On my Windows 10 PC 

When on the FC1 page at https://www.freecen.org.uk/  and click on either these links I get the Green Donate button.

sign up page on FreeCEN2: https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen 



On the my IPad

But when doing the same on the IPad I do not get the Donate button but the following empty box with the text in it.


https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen


I have rebooted the IPad but still get the same.
I do not know which server it users though.
The “text”  link works and takes me to the page with the Green Donate Button showing.

https://www.freeukgenealogy.org.uk/help-us-keep-history-free

But at least not getting the ERROR PAGE anymore.



Sent from Mail for Windows 10

**Comment by DeniseColbert** [comment]
It sounds like there might be an issue here with a (wrong) link showing where the donate button should be. Are you able to screenshot Brenda?

**Comment by FreecenBren** [comment]
Never found out on the iPad so asked it. Sorry it is big. Tried attaching
it but this was all it would do

**Comment by DeniseColbert** [comment]
Hmm, it's not showing anything. I'll try to get it tested. Thanks Brenda.
