### ISSUE TITLE
Create text for volunteer landing page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#423]
Volunteer 'landing page' - where they are taken once they've logged in.
Needed by #481
E0 U6 S7 C7: P20

**Comment by PatReynolds** [comment]
Draft for comment https://docs.google.com/document/d/1C21P0U4xVioaK7ZySKA0aZzNlVuIMhHogkX9gHkJ0WA/edit?usp=sharing

**Comment by richpomfret** [comment]
For us to check the text and approve.

**Comment by richpomfret** [comment]
@AlOneill to review. We discussed how this text might also change depending upon user or transcriber type.

**Comment by richpomfret** [comment]
Added comments. It might be good to add in a few links to some of the documents Brenda sends around to new transcribers - they then know where to find them if required. Files are hosted here: https://drive.google.com/drive/folders/1Xx_bPtxx-kITkpX9NqpEbl7fRbQqrX5U?usp=sharing

**Comment by richpomfret** [comment]
Additionally, shall we also include a link to the transcribers google group?

**Comment by PatReynolds** [comment]
That would be good - would fulfil #557 - what do you think, Brenda?

**Comment by richpomfret** [comment]
Perhaps we will get a surge of sign-ups due to it being Jan? In which case, it would be great to get this new text/links implemented this month.

**Comment by PatReynolds** [comment]
I believe all comments here and on document are now resolved.

**Comment by AlOneill** [comment]
Document including 'markup' looks good — will need to review once implemented (it is an app page and not on Refinery).

 Using an iframe may or may not be a good idea as whole of target page will be available and volunteers may or may not be familiar with them.

**Comment by richpomfret** [comment]
@Vino-S can you add this and let us know once it is ready for us to review?

**Comment by Vino-S** [comment]
@richpomfret , I have added the text in live website. Please have a look and let me know your feedback. 
I have not added the the following
`Current Actions (in panel to right - see screenshot above) 
(everyone) profile [edit your own], roadmap 
(managers and coords only) contacts [from website], manage userIDs, syndicate coordinators [list]
(managers and tech volunteers only) Refinery CMS, search performance, 
(managers only) feedback, message system
`
Please let me know if I need to add the above also

**Comment by richpomfret** [comment]
Also give Brenda permission to add people to the google transcriber group.

**Comment by richpomfret** [comment]
Looks good. :)

**Comment by AlOneill** [comment]
Just a couple of things:

Three of the four links in the opening paragraphs are set to open in a new tab, without warning. Although this is not a public page (and so full accessibility criteria do not apply), it could be confusing for a volunteer — for example, one who is not internet-savvy.

If it *were* a public page then link text such as "click here" or its variants would be a definite no-no: suggest we get in the habit of *always* giving some context to link text, so that a screen-reader's list of links on a page is meaningful. 

If we are concerned that a volunteer may not *recognise* a link when they see one,  better to phrase as, "use this link to 'sign up to the google group' " (link text is the part in single quotes) or similar.

**Comment by PatReynolds** [comment]
This story may contain elements/suggestions that do not refer to the Volunteer landing page.

Elements relating to the volunteer landing page have now been added, but the Open Data signup has gone awol, so I wil re-open that story.

Suggest closing this one.
