### ISSUE TITLE
Make it clearer when no results found, that we haven't transcribed all records

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#454]
Many comments implying this info is being missed - consider stating in bold that our database isn't complete.

**Comment by Captainkirkdawson** [comment]
The current text is Freereg based; talks about registers
We have also changed the Transcriptions link to records.
Need to have different texts for different apps

**Comment by DeniseColbert** [comment]
@DeniseColbert to look at this message in FR & FC and come up with draft text

**Comment by DeniseColbert** [comment]
Draft text ready for feedback: https://docs.google.com/document/d/1n58RWUVyqGe1pBf6YC7KAFkAdKE90m4hFJ60vBkWmZs/edit?usp=sharing

**Comment by AlOneill** [comment]
Have left some comments and suggestions.

**Comment by AnneV-Learn** [comment]
@DeniseColbert - I have reviewed and left one minor comment

**Comment by PatReynolds** [comment]
@DeniseColbert has resolved Anne's comment - please proceed with implimentation

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by PatReynolds** [comment]
Tested - working as expected, thank you @Captainkirkdawson  Needs a second pair of eyes for typos as my eyes are wonkier than ever.

**Comment by AlOneill** [comment]
@Captainkirkdawson @PatReynolds No typos spotted. Can I suggest that the spacing between the paragraph above the list and the list itself be reduced a little by adding the class `push-half--bottom` to the paragraph (this is our standard practice on Refinery pages)?

I should've made a comment on the link text "Search tips" earlier — apologies. As it points to (the top of) the "Help" page, then the link text should be the same as in the main navigation. Also, it would be good to rearrange the sentence a little so that the key information is presented ahead of the link. I suggest:

"For advice on how to get the most out of your searches, see the search tips in our [Help] page."

I note that the spacing for the text between the h2 (No results found) and the paragraph is controlled by the use of break elements and that the text is contained in inline elements (no paragraphs — no block elements). It is not an error per se, but it is unconventional.

**Comment by Captainkirkdawson** [comment]
@AlOneill Revised on both test3s. I have always and will be unconventional. Need you to keep me focussed
I changed the text on gaps to _Some reasons for missing records_ for consistency of ideas

**Comment by AlOneill** [comment]
@Captainkirkdawson Excellent. Thank you.

I mentioned the unconventional markup because I have a dim memory of an idea that some screen-reader users move through a page by going to the next _paragraph_. I might be imagining that idea — I'll try to find out and will get back to you if I find anything definitive and that warrants a change.

PS it might be a mistake to rely on me to keep you focussed — my cognitive skills are all over the place :-)

**Comment by PatReynolds** [comment]
I'll mark as ready for deployment - will need to return to this if @AlOneill  finds that there is an isue.

Thank you all - a varst improvement

**Comment by AlOneill** [comment]
@PatReynolds The navigation issue is complicated — different users will use different methods. I'm still considering what would make most sense in the context of that page — and also more widely, for the sake of consistency and predicability for our screen-reader users. I'm currently leaning towards a change of some sort.

**Comment by PatReynolds** [comment]
Sorry, @AlOneill what navigation issue?

**Comment by Captainkirkdawson** [comment]
Deployed
