### ISSUE TITLE
Continue use of Chapman Code?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#488]
Can Field T be changed to TWYS? I.e. can FC2 cope with the text as entered by the enumerator?

**Comment by AlOneill** [comment]
I does not look like a trivial change as places described by CHP codes were spelt or abbreviated in inventive ways by some enumerators. Some counties in SCT and IRL had more than one name in use: the recorded name is currently entered in the Notes field if it is not obvious from the CHP.

And validation of a file would fail if the TWYS version is unknown to the process. Could not be applied retrospectively.

Transcribers wouldn't like it! More, and more careful, typing required.

**Comment by PatReynolds** [comment]
Possibly remove OVB except for where person is stated to be British?  Possibly remove OVB except for where country is known to be a British colony/dominion at the time of birth - or leave this for a Validation task?

**Comment by FreecenBren** [comment]
I would say that 90%+ of OVB are transcribed because the Enumerator added
the words British Subject.
Therefore the Transcriber would transcribe it AS IS.

The remainder would/should be picked up by the Validator.
Removing the OVB option would go against what we tell them to Transcribe AS
IS.
Leave it for the Validation Process is my preference.

**Comment by PatReynolds** [comment]
@PatReynolds to move comments re OVB to other story, and to write out some examples of  censuses, where the use of Chapman code is innapropriate
