### ISSUE TITLE
Help page created,

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#51]
Using existing FreeCEN and FreeREG2 content as a basis

**Comment by AlOneill** [comment]
Page draft is complete: it is a draft in that I expect details to need editing as Search capabilities are refined.

Page renamed as [Information for Researchers](http://test2.freecen.org.uk/information-for-researchers), as agreed in today's scrum.

Perhaps it is time to add a link from the Search page, so that testers can view and comment on the content?
