### ISSUE TITLE
County coords can access all/active/specific places in their county. Add/Edit information about the Place.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#529]

**Comment by PatReynolds** [comment]
@FreecenBren is this something that has been brought over from the FreeREG roadmap that has no meaning on FreeCEN?

**Comment by Captainkirkdawson** [comment]
It is essential that we remember that the Freecen2 Places. collection is used for validation of the POB.

All have access to display entries in this collection through the Search Place Names action.

We have provided coordinators as well as data administrators and system administrators with the ability to add and edit a place, including its physical location (lat/lon or grid reference). They also have the ability to add alternate place names. They can do this for **any county**.

@geoffj-FUG and I have been discussing who else should have the ability to add and edit places.

Given how the collection is used it seems reasonable to **add validators** to the list of people who can add and or edit.

There remains the question as to whether transcribers and or proofreaders should have any form of editing or addition. Perhaps just to add an alternate name to an existing place in any county.

It is essential that the collection remain a high quality collection and not degenerate.

**Comment by geoffj-FUG** [comment]
Kirk

 

As intimated before I do not believe that Transcribers / Proofreaders should have that function as we can lose quality of the data.

 

Some transcribers / proofreaders validate. How difficult is it to restrict the function so that is available only when a piece is in validation in that volunteer’s File list?

 

Geoff

**Comment by rhodamackenzie** [comment]
I also feel transcribers and proofreaders should not have any form of editing or addition for placenames (but could suggest this to their validator

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Cannot think of an easy way of doing as you suggest but will keep thinking

**Comment by geoffj-FUG** [comment]
May I fly a kite?
At the moment we have a field in the Volunteer profile that says experience. I dont find it very useful though I did uodate it once.
If we replace the levels of learner etc with Transciber, Proofreader, Validator, Coordinator it roughly equates to the skill level. We can leave Learner at the bottom of the pile if that is needed.
Now you have a field that can govern what buttons appear, just as you must have a flag somewhere that identified a Coordinator so that you can control the menu.
A Coordinator can open the validator menus for a volunteer by setting the skill level to Validator.
Just an idea
Geoff

**Comment by geoffj-FUG** [comment]
Kirk
The transcriber and proofreader have read only access. Thats fine.
We set up Chas with a piece to validate but left his role as transcriber. He only had read only access.
We then changed Chas role to Validator. He gained Read Write access.
Coordinators have had Read Write access all the time.
So we are now working correctly.
(Chas is the only tester who is validating and is not a Coordinator). 
Geoff
