### ISSUE TITLE
Link to freecen1 from freecen2 homepage

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#537]
Needs to be ready in time for the update to make FC2 the main site.

NB not a refinery task

**Comment by richpomfret** [comment]
@PatReynolds to add in text for us to use.

**Comment by smrr723** [comment]
The current text shows "FreeCEN2 is a work in progress; we want your feedback (link opens in a new tab) on all aspects so that we can make it better."

I will just add to this, to make it:

"FreeCEN2 is a work in progress; we want your feedback (link opens in a new tab) on all aspects so that we can make it better.  You can visit the old FreeCEN website here - https://freecen1.freecen.org.uk/"

Is this ok?

**Comment by helhyde** [comment]
Yes, that is good.

**Comment by richpomfret** [comment]
@smrr723 can we add this text?

**Comment by smrr723** [comment]
Added - will be live once the production update is complete in the next hour or so.

**Comment by smrr723** [comment]
Now in production.
