### ISSUE TITLE
Update the email text for new registrations

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#542]
The current email sent to new users states - 

> You will also be shortly receiving an email with full details of how to transcribe for the project from the Chair, Brenda Bowers.

This results in members emailing Brenda if they do not hear from her within 24 hours.

**Suggested change -** change the text above to say "shortly (within 1-3 days)", AND/OR include some starter documentation/instructions to get the users started and give them something to do whilst awaiting the personal response from Brenda.

FYI @FreecenBren

**Comment by FreecenBren** [comment]
It should actually say  something along these lines-
“You will also be shortly receiving an email with full details of how to transcribe for the project from the Coordinator who looks after your chosen County”.
Cheers 
 

Sent from Mail for Windows 10

From: Scott Murray
Sent: 11 November 2018 23:06
To: FreeUKGen/FreeCENMigration
Cc: Brenda; Mention
Subject: [FreeUKGen/FreeCENMigration] Update the email text for newregistrations (#542)

The current email sent to new users states -
You will also be shortly receiving an email with full details of how to transcribe for the project from the Chair, Brenda Bowers.
This results in members emailing Brenda if they do not hear from her within 24 hours.
Suggested change - change the text above to say "shortly (within 1-3 days)", AND/OR include some starter documentation/instructions to get the users started and give them something to do whilst awaiting the personal response from Brenda.
FYI @FreecenBren
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by smrr723** [comment]
Thanks, Brenda.  Have added in your suggested text - will be in production code after next weeks update.
