### ISSUE TITLE
Enhance responsiveness of contact system

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#566]
Currently contacts all go to one volunteer - a contact about the website performance (e.g. search not working) might not be seen promptly.  (NB answer is not More Caffeine for the volunteer!!!)

E 2 U 2 S7 C6: P17

**Comment by Captainkirkdawson** [comment]
Clearly a personnel management issue not a system issue

**Comment by DeniseColbert** [comment]
@AnneV-Learn to make Website problem and Enhancement Suggestion go to her and Vino

**Comment by AnneV-Learn** [comment]
@DeniseColbert - I have just done some investigation before making any changes :

'Contact Us' communication emails are sent to users with the role 'contacts_coordinator'. Currently this role is only assigned to the 'Cen Coms' user - see below - (does anyone monitor that email address?)

![Screenshot 2022-10-07 at 11.41.27.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/529adaa3-2524-4ccc-bcdf-45d1c8223ae5)

Then depending on the 'contact type' copies are also emailed to users with the following role/secondary role:

![Screenshot 2022-10-07 at 12.18.02.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/85bdd9ce-fca4-489d-9466-4f0ef4fbfcd3)

NB Volunteer Coordinator user - (does anyone monitor the email address?):

![Screenshot 2022-10-07 at 12.06.20.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/86d3b6b7-4270-4ccb-86b9-8a938d95d05a)

**Comment by DeniseColbert** [comment]
Yes, I get the Cen Coms and Volunteer Coord emails. It's a concern that no one seems to be receiving four types of contact, that needs some thought.

**Comment by DeniseColbert** [comment]
@Vino-S to assign me to the roles with no one currently performing

@DeniseColbert to deal with unanswered contacts and make new stories if needed

**Comment by DeniseColbert** [comment]
@Vino-S to also change Richard's comms to Anne

**Comment by DeniseColbert** [comment]
@Vino-S to take me off the emails that go to volunteers that ask for me to be included in their reply.

**Comment by DeniseColbert** [comment]
@Vino-S to create a Newsletter Coordinator role (Chris Mahoney)

Then Pat can be made Comms Coordinator and emails can say "A copy of the action request was sent FreeCEN Communications Coordinator Pat Reynolds [pat.reynolds.volunteer@freeukgenealogy.org.uk](mailto:pat.reynolds.volunteer@freeukgenealogy.org.uk). Please include them in any correspondence. (Instead of Copies of the action request were sent to the following. Please include them in any correspondence
Denise Colbert [denise.colbert@freeukgenealogy.org.uk](mailto:denise.colbert@freeukgenealogy.org.uk) Pat Reynolds [pat.reynolds.volunteer@freeukgenealogy.org.uk](mailto:pat.reynolds.volunteer@freeukgenealogy.org.uk) as it is now)

Also, add in ability to CC other roles.

**Comment by DeniseColbert** [comment]
Newsletter coord role should get reports (all statistics etc) and Thank You form submissions

**Comment by DeniseColbert** [comment]
@geoffj-FUG to send Vino Chris's UserID so she can liaise with him re. testing

**Comment by DeniseColbert** [comment]
@Vino-S to ask Chris to test

**Comment by DeniseColbert** [comment]
@Vino-S to give Pat's (volunteer) role access to all archived contacts

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG is now a transcriber with special powers: does this finish this story?

**Comment by DeniseColbert** [comment]
Done, closing
