### ISSUE TITLE
FreeCEN2 times out in a second or two

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#567]
Searching Alcock, Nottinghamshire, 1841, windows 10/chrome, timed out in a second or two at 9.57-ish this morning.  Had this issue last week.

**Comment by PatReynolds** [comment]
Hi @sharadd15 and welcome to Free UK Genealogy!  Someone will be in touch in the next few days to get you set up, but if you have a few minutes in the meantime, could you try and replicate this bug (not yet proven to be a bug)?  Thanks, Pat (Executive Director of Free UK Genealogy, the charity covering FreeREG, this and other projects)

**Comment by PatReynolds** [comment]
Issue seems to be if you have used FreeCEN2 before, resolved with clearing cache.  Please could someone put a note to that effect on the homepage of FC2. Please still test, @Sharadd15 to check that new users do not have this issue.

**Comment by richpomfret** [comment]
Tested (Chrome, OS X) and got results within a few seconds based on the Alcock search above

**Comment by Captainkirkdawson** [comment]
@PatReynolds 
As noted on slack on 29 Dec the issue was a result of an incorrect configuration file on colobus. The maximum search time had been set at 10ms instead of the normal 100s thus causing the fast time out. This was apparent by looking at the timeout being used which is displayed on the search form.
![freecend](https://user-images.githubusercontent.com/2874694/50563286-cfc87180-0cd8-11e9-9708-15f64d32ac5c.JPG)
This configuration file had been in use on colobus since June 2017.   As a result any user assigned to colobus would have timed out.
An updated version of the configuration file with the normal max search time was installed.

**Comment by richpomfret** [comment]
Many thanks @Captainkirkdawson and good to see you involved here on FreeCEN. ;)

**Comment by richpomfret** [comment]
Moving to done.
