### ISSUE TITLE
Contact us capability

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#57]
Basic capability (as with FreeREG2 at 1.3).  Use learning from FreeREG2 to help workflow.

**Comment by PatReynolds** [comment]
FreeREG experience suggests having a person who can be 'helpdesk' and route things onto the waffle board, if need be, would be useful, and take the load of those doing development work

**Comment by dougkdev** [comment]
This is working for freecen now, I just need to add the names/emails of the
people we want to receive the contacts.
One question:
In freereg, any screenshot is saved into the system but not embedded in the
emails.  Coordinators/admins can look at the contact online (have to log
in) to see the screenshot.  In FreeCen we aren't really logging in at this
point and it seems it would make sense to embed the screenshots in the
emails themselves.  Was there a reason we didn't embed the images in the
emails in FreeReg (bandwidth, privacy, spam, etc.)?

**Comment by PatReynolds** [comment]
Hi Doug,

We are having some issues with the FreeREG contact system, so I'm keen to
set up FreeCENs to avoid the issues.

Can you confirm which side of the 'membership' wall contact system you are
talking about?  Or both? And does it give choices?

I'm not sure how far off getting contacts sorted on FreeREG - it might be
worth just sending everything to one person who can respond / put onto
github in the short term.  Ideally not Brenda!  The creaking really only
started with FreeREG once we had the coordinators involved, so a more
sophisticated routing system isn't needed at the start.

Best wishes,

Pat

On Friday, 23 October 2015, dougkdev <notifications@github.com> wrote:

> This is working for freecen now, I just need to add the names/emails of the
> people we want to receive the contacts.
> One question:
> In freereg, any screenshot is saved into the system but not embedded in the
> emails. Coordinators/admins can look at the contact online (have to log
> in) to see the screenshot. In FreeCen we aren't really logging in at this
> point and it seems it would make sense to embed the screenshots in the
> emails themselves. Was there a reason we didn't embed the images in the
> emails in FreeReg (bandwidth, privacy, spam, etc.)?
>
> On Fri, Oct 9, 2015 at 12:10 PM, sean-wood <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Assigned #57 <https://github.com/FreeUKGen/FreeCENMigration/issues/57>
> to
> > @dougkdev <https://github.com/dougkdev>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FreeUKGen/FreeCENMigration/issues/57#event-431692566
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/57#issuecomment-150639481>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
Thanks, Pat.
I am only speaking about the contacts coming from outside of the membership
wall right now since we don't yet have members logging in on FreeCen,
although the contacts from within the membership wall are handled fairly
similarly once that comes online.  The contact form allows the user to
select a type of contact: data problem, website problem, volunteer,
question, or thank you. In FreeReg, they get routed based on contact type,
and those listed as "website problem" automatically get put into github as
incoming issues. Automatic routing is one of the pending stories for
freecen.  I can have all contacts go to one person. Do you have a
preference for who that is?  Would it make sense to have either you or Sean
be that first contact?

**Comment by benwbrum** [comment]
We didn't include the screenshots as attachments because it never occurred
to us to do so.  By all means, please do if it's easy!

Ben

**Comment by dougkdev** [comment]
Now attaching screenshot in confirmation email to the person who submitted
the contact, but including links (instead of attaching) in emails to us.
That way user has a record of what they submitted, but our email doesn't
get clogged with screenshot image attachments. We can click the screenshot
link directly from the email to us if we want to look at it.

**Comment by PatReynolds** [comment]
Thanks Doug,

Can you start a document to document the FreeCEN2 contact system?  Please could you include where the texts of the auto-emails are (and how we get to edit them).

Thanks,

Pat
