### ISSUE TITLE
Testing The Big Merge (on test2.freecen.org.uk)

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#579]
Testing FC2 required as per the magnificent merge that's COMING SOON.
What is the Great or Magnificent merge?
FreeCEN2 is built upon the same code base as FreeREG2 but with  an application sensitive setting  so that it displays pages using the CEN colour scheme,  provides unique CEN functions and disables REG specific functions.
It had been expected that  FreeREG2 code changes would be incorporated into the  FreeCEN2 code on a regular basis . This happened initially but unfortunately stopped 2 years ago. Since FreeREG2 has updated all of the software on which it and CEN are built it was decided that we should bring FreeCEN2 code back up to date with   FreeREG2  code. This is the Great Merge.
When completed it will provide CEN with all of the communications capabilities built for REG,  all of the underlying software component updates, all of the guarding added to REG for bots and incorrect inputs as well as all of the on line member tools and system management.

**Comment by benwbrum** [comment]
Functionality to test in particular:

* Click through every screen of the site, looking for (or CTRL-F) "FreeREG" instead of FreeCEN
* Search on FreeCEN-specific  fields like Birth County
* Verify advertisements and cookie warnings are displayed correctly
* Test email (especially any contact-us notifications) and "messages"
* Test the "manage counties" functionality
* Test transcriber registration

**Comment by benwbrum** [comment]
Do we have any sort of tag for issues resulting from these tests?

**Comment by PatReynolds** [comment]
I don't think so.  What would you like? MergeBug?

**Comment by PatReynolds** [comment]
MergeBug created.
On "Test the manage counties functionality" - would this be best done by someone familiar with FreeREG and how the functions _should_ work?
Testing Volunteer sign up seems to work fine - but changing password generates an error:
![image001.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c37263d9b190120013e30d/125516c66e82c728ace21e0d46e1999b2487d3f9deabf301b44fff9e2c4533317346f67f71ddb22beb172e59595f47ac415a5f44f9fb8b22afbf2e6c981e5ab38532022d8c6853beb2901eb80bbb258e4c84b6ba8a48c3eb3b26f5c6.png)

**Comment by Captainkirkdawson** [comment]
Have updated the userid_details collection to reflect production. This means all Members of production can log in to the system for testing.
Corrected a few merge issues on the Member actions. Removed Actions unique to FreeREG

**Comment by Captainkirkdawson** [comment]
Volunteering and password reset both work as expected on test2

**Comment by Captainkirkdawson** [comment]
All aspects have been tested to the best of my ability as someone who does not use FreeCEN on a regular basis.

**Comment by Captainkirkdawson** [comment]
Summary of where we are:
Master has been merged into freecen_parsing by @benwbrum , tested and bugs fixed by myself. Brought into step with the current master yet again. It is now running on test2 cen with no known issues. 
Recommend that the merged branch replace freecen_parsing in production and become the base code for CEN Development. Master should be merged into the merged branch every 2 weeks, These 2 steps are essential to avoid future divergence and having to do this all again.

**Comment by Captainkirkdawson** [comment]
Ugh
@richpomfret @Vino-S @PatReynolds 
Just went to merge freecen_parsing into master-into-freecen and guess what 6 areas of conflict!!! We have to get away from updating parsing or we will spend hours resolving conflicts

**Comment by Vino-S** [comment]
I too agree with @Captainkirkdawson . We need to stop working on freecen_parsing in a order to stop ourselves from creating more conflicts. We can continue once the merge is completed. 

Can I suggest to update only` master` every sprint as most of the time we have common requirements and changes for both REG and CEN?
We can filter on code level for fixes of FreeCEN/ FreeREG specific issues.
Then we will update the `freecen branch` with `master` every sprint, so that we have same code base consistently as long as we can.

**Comment by benwbrum** [comment]
We think that testing is complete and that this branch is ready for deployment.  We may need a plan for deployment to production.

**Comment by Captainkirkdawson** [comment]
The master-into-freecen has been superseded by the multi modal master branch which is the common MyopicVicar code base that supports our applications. We should test this and place into production rather than master-into-freecen

**Comment by benwbrum** [comment]
We need to test both FreeREG and FreeCEN on test2 with the multi-modal code.  @Vino-S is also testing the VLD/build processing files.  

This is the branch that needs to be deployed; there is no reason to deploy the interim `master-into-freecen` branch instead.

**Comment by benwbrum** [comment]
Denise has tested the base-line search for FreeCEN with citations etc.  We need a more comprehensive search of e.g. CEN-specific searches.

**Comment by richpomfret** [comment]
Closing - any new bugs/issues that arise on LIVE can be added as specific stories.
