### ISSUE TITLE
Change TEST2/3 to reflect FR

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#581]
Currently we have TEST3 (dev) and TEST2 (test) on FreeCEN, which is the opposite of what is used on FreeREG. This has led to issues/confusion in the past, particularly in relation to cms updates on Refinery. There appears to be less work involved in changing FC, so let's do that in order for both projects to have the saming naming conventions.

**Comment by richpomfret** [comment]
@smrr723 @Vino-S @Captainkirkdawson do you anticipate any hidden problems we might face in changing the naming conventions? Any possible conflict on Github or our deployment process?

**Comment by Captainkirkdawson** [comment]
On REG test2 is a development deployment. test3 is a production deployment. Both are for testing code. Complex code development is applied to test2. We apply bug fixes etc to test3 for final checkout before deployment to the production servers. The terms development and production in the above have a rails meaning. They serve static assets differently and they can have different performance settings.

**Comment by richpomfret** [comment]
Thanks @Captainkirkdawson. IF we were to swap the naming conventions around on FR (as we are investigating for FC), would you anticipate any errors or major issues?

**Comment by Captainkirkdawson** [comment]
@richpomfret 

Why would we change the FR scheme??? Its been that way since day 1. Everyone knows it

We would have to get lemon to change the urls in Apache to point to different folders if you wanted to make such a change

Sorry but I do not see any benefit.

CEN has never actively used 2 sites on vervet at least not to my knowledge So why don't they adopt the same logic as REG?????

The logic was actually based on a progression. test1 were our personal servers, test2 open to users for their testing of development code and test3 pre-deployment of minor code fixes. We abandoned the personal servers as the costs were too high when we were using our own servers and went to our own machines

**Comment by smrr723** [comment]
I can't see any negative side effect from changing the FC scheme to match FR.  We don't have anything on there tied to our production deployments.

@Captainkirkdawson I think Rich meant that we will be changing FC's test servers to match the (correct) FR naming convention.  Right now, FC test2 is equivalent to FR test3 and causes confusion occasionally.  The FR setup will be untouched if I understand correctly.

**Comment by Captainkirkdawson** [comment]
Sorry but that is not how I read the penultimate post

**Comment by richpomfret** [comment]
@smrr723 is correct, we are investigating changing FC to match FR (not the other way around). @Captainkirkdawson my previous question perhaps wasn't clear in that respect, but was one designed to flag/elicit what might go wrong with such a change by considering it from a FR perspective. 

Thanks both. I think we can go ahead and roll this out later this week (if you're around @lemon-ukgen). Please keep us informed here and on the Slack sprint channel.

**Comment by lemon-ukgen** [comment]
I have made the change to FreeCEN2 test sites:


https://test2.freecen.org.uk/ -> `/home/apache/hosts/freecen2/development` (RoR root)-> `freecen2_development` (db)

https://test3.freecen.org.uk/ -> `/home/apache/hosts/freecen2/production` (RoR root) -> `freecen2_production db` (db)
