### ISSUE TITLE
Issue with selecting place (of census)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#606]
There is one aspect of the new site that is an improvement. That is that after selecting a census county the places in that county are listed in a new box for selection.
But that presupposes that you know which district your target person was in, which is no use in places like Glasgow where people moved around in and out of sub-districts that are not all even parishes, like Blythswood. Even in FC1, using Glasgow as the place fails to turn up the results in Barony, Blythswood or Gorbals which were returned in the search for Marg* Kirk, and how is some poor searcher from the other side of the world supposed to know the names of all the sub-districts in Glasgow?

#155 is the sophisticated solution, and is scheduled for 1.4

See also #465 - Searching place when you don't know a county

NB: searching place of birth the answer is "use nearby places"

**Comment by PatReynolds** [comment]
Is this still valid, or has it been addressed with other developments?

**Comment by Captainkirkdawson** [comment]
Still valid; maybe even more so

**Comment by PatReynolds** [comment]
I _think( discussion was that civil parish should be used because it is/?can be mapped across all censuses.- but can't find discussion now.. It may be subdistrict?  or give user the choice of searching the cp/subdistrict OR the district?  

I feel Civil Parish is best (once CP name mapped to all the variant names) with 'nearby places' added as a priority.

Thoughts @Captainkirkdawson @geoffj-FUG @rhodamackenzie (and everyyone).

**Comment by PatReynolds** [comment]
Piece name used currently.

All three levels should be used (future).

**Comment by PatReynolds** [comment]
#155 is the solution to this, so closing
