### ISSUE TITLE
Review Indexes

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#648]
Some FreeCEN fields are not indexed (e.g. Birth County Chapman Code).  The missing indexes need to be identified and implemented.

E 1, U 6, S 7, C?: P

**Comment by Captainkirkdawson** [comment]
As a start it would appear that a large number of searches include a birth_county which is unindexed. Most of those do not include a census_county which is indexed. Is that because of the form layout?
The SSD is not used in CEN so is not required as a search index element
a) The first step is to write a rake task to determine the actual search parameters used
b) Secondly modify the search performance statistics to display the search parameters for Cen
c) Thirdly modify the site statistics to list the Cen records.

**Comment by PatReynolds** [comment]
Purely from my own usage ... I am guessing that if the tree has been built from BMD and REG info, the birth county is known, but and maybe marriage (giving a married surname) but 'current location' decades later is unknown.  With rarer surnames, and a known/approximate birth date, searching without limiting by census county reduces the results to a manageable.  I wonder if we can get the json files from FreeCEN1, to see what happens there?  [if we can analyse them].

**Comment by PatReynolds** [comment]
@Captainkirkdawson please change priority I have given if I've got it wrong, and estimate size.  TY, Pat

**Comment by Captainkirkdawson** [comment]
This is an Epic. The first cut has been done. Will review after completion of the 3 tasks identified

**Comment by Captainkirkdawson** [comment]
Based on the statistics of usage where 50% of searches include only a birth_county the fact that we include indexes only for census counties must have a significant impact. We should replicate the indexes used for census county with birth county and adjust the hinting accordingly. Once that is done we should consider a dual chapman birth_chapman set of indices. 
While doing so we should eliminate the secondary date field of the index as CEN does not use that field.
The performance statistics show that all long running searches are those using a birth county

**Comment by Captainkirkdawson** [comment]
Indexes designed and created for CSVProc
