### ISSUE TITLE
Record produced using a citation generated url is missing Printable Format, [not possible to add Next Dwelling and Previous Dwelling, Next Record and Previous Record]

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#675]
In implementing the citation I noted that FreeCEN does not implement a next or previous record produced by a search. Instead there is a next and previous dwelling.
Is this deliberate? It means that there is no way, other than going back to the results, to step through the results. Should there be? Should both be there?
Decided in prescrum 15/5: yes, both should be there.  

Two actions: 
1/ redesign page so that the additional buttons can be accomodated, and
2/ create new buttons

**Comment by PatReynolds** [comment]
This is deliberate.  For discussion, should we add a 'previous entry in search results' and 'next entry in search results' feature?

**Comment by PatReynolds** [comment]
Already implemented, so suggest closing.

**Comment by Captainkirkdawson** [comment]
There is no citation for a next or previous dwelling.

**Comment by PatReynolds** [comment]
All the buttons are missing.

**Comment by PatReynolds** [comment]
All inoriginal story complete, Kirk to look at the print button.

**Comment by Captainkirkdawson** [comment]
Please refresh my mind on what is required on the print button

**Comment by PatReynolds** [comment]
Same 'Printable format' functionality as on the normal details page, please.

**Comment by Captainkirkdawson** [comment]
@PatReynolds I still do not understand what is required. Are you saying that in addition to the ability to copy the citation you want the ability to print the citation? or something else?![citation.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/69803ac0-db53-4081-a5ba-22659a1651b8)

**Comment by PatReynolds** [comment]
When someone visits a page, based on a citation rather than a search, e.g. "General Register Office: 1891 Census Returns database, FreeCEN (https://www.freecen.org.uk/search_records/59041560e9379091b19f2e09 : viewed 7 Sep 2021), William FLEMING, 14, Jaquest's Yard, Northamptonshire, England; from 1891 "England, Scotland and Wales census," database and images; citing The National Archives RG 12/1216, Folio 21, Page 35, Schedule 201, The National Archives, Kew, Surrey.
They should see a 'Printable Format' button on https://www.freecen.org.uk/search_records/59041560e9379091b19f2e09 that has exactly the same functionality as the 'Printable Format' button on https://www.freecen.org.uk/search_records/59041560e9379091b19f2e09/william-fleming-1891-northamptonshire-kettering-1856-?locale=en#

**Comment by Captainkirkdawson** [comment]
Added and deployed to test3

**Comment by Captainkirkdawson** [comment]
If testing on test3 you will get a citation such as  localhost:3000/search_records/60e282b1bd30f2d562e7fc2c

You need to paste the search_records/60e282b1bd30f2d562e7fc2c on the test3 server address https://test3.freecen.org.uk/
So it is https://test3.freecen.org.uk/search_records/60e282b1bd30f2d562e7fc2c

This is ONLY for testing purposes

**Comment by PatReynolds** [comment]
Working fine, thank you, Kirk
