### ISSUE TITLE
Extract country of Birth (OVB and OVF) from places recorded in Notes

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#684]
Possibly implement via machine learning

**Comment by geoffj-FUG** [comment]
This issue is affected by Story #1310. 
Putting my Validator hat on I would put an alternative POB in the Alternative POB fields (FC2) or in the Validators Choice fields (FC1) if I thought that it was a probable choice after I had researched the verbatim entry.
If I added a POB to the notes it was to make a researcher aware of a possibility, however remote. The intention is not to provide an Alternative POB in a majority of cases. It can only really be considered as a hypothesis.
I feel that to try to  interpret a POB entered in the Notes as a viable option is fraught with danger. They are only put there to offer a researcher a possible area for them to research to prove or disprove as an option.
Geoff

**Comment by geoffj-FUG** [comment]
This story is relevant to the vld dataset. When we are combining OVF and OVB into one Chapman Code of OVF an entry in the Notes field is proposed to show that the person is a British Subject. See Story #1310
If this happens we will have resolved the issue a different way and this story will no longer be needed.
Geoff

**Comment by PatReynolds** [comment]
Needed for Georeferencing/seraching by place of birth outside of UK

**Comment by geoffj-FUG** [comment]
When we have all these places in the Gazetteer they will be georeferenced through the Gazetteer entry.

Georeferencing has no impact on this story. Once VLDs stop and the vld dataset is stable we will be able to re-validate any entry that is not in the Gazetteer. A lot of these will be simple reversals of the entry to meet the greater to smaller rule. Others will be expanding abbreviations necessitated by FC1. We cannot do this whilst vld records are still being added as that will simply mean that we will have to re-validate a second time.

Geoff

**Comment by geoffj-FUG** [comment]
Once the changes in story #1310 is complete this story will no longer be required.
Geoff

**Comment by DeniseColbert** [comment]
See above, closing
