### ISSUE TITLE
Site Statistics page is not working (FC2)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#685]
May be a feature still in Test3 / test2.

E1 U6 S7 C6: P20

**Comment by Captainkirkdawson** [comment]
This is because there are no cron tasks set up for vervet that would create the statistics. that applies to both reg and cen

**Comment by richpomfret** [comment]
So....I would have thought that this might be resolved as part of the great merge, but your last comment @Captainkirkdawson appears to indicate otherwise?

**Comment by richpomfret** [comment]
Not needed on test2/3 so closing.

**Comment by richpomfret** [comment]
Checked and broken on LIVE, so reopening and moving across.

**Comment by Captainkirkdawson** [comment]
Site statistics do not work in production or in test.

In REG they contain; number of searches, number of records by type (ba, bu, ma) and total

Since REG is updated daily all fields change on a daily basis

In CEN  we could also have number of searches, number of records by type (1841, 1851 etc) and total
But the latter field will be static for a month which is likely why the report was never produced.

Do we need it? or only when we change update process for CEN?

**Comment by PatReynolds** [comment]
It's not working because I was looking on test16, not www16!   So closing.

**Comment by Captainkirkdawson** [comment]
Reopened as this was issue on site statistics

**Comment by Captainkirkdawson** [comment]
Have activated site and search statistics on test3

**Comment by PatReynolds** [comment]
Tested on test3 and working fine, thank you.

**Comment by Captainkirkdawson** [comment]
It is worth adding that statistics are now in the footer

**Comment by Captainkirkdawson** [comment]
deployed
