### ISSUE TITLE
Amend Excel column adjustment instructions and add to FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#687]
Document at https://drive.google.com/file/d/0BzRDUeF70MtpcEdZZzl1WnNlYm5qaXRmNVdZTExIQ2ZpaXJB/view?usp=sharing needs converting to Refinery and Windows 10 instructions adding

E0 U1 (rarely used) S3 C7: P11

**Comment by AlOneill** [comment]
Needs to be more general than just for Excel, including OpenOffice, for example.

What is different on Windows 10?

**Comment by PatReynolds** [comment]
Don't know about Windows 10 changes - request was from Brenda.

**Comment by AlOneill** [comment]
OK. Will place on "Spreadsheet Tips" page (to be created).

**Comment by AlOneill** [comment]
Have created a draft "Spreadsheet Help" page, but Refinery will not save added content: will add this to story re Refinery issues.

**Comment by DeniseColbert** [comment]
@AlOneill to find draft page on her computer

**Comment by geoffj-FUG** [comment]
Alison These might fit quite neatly under the Handbook tab  of the Your Actions menu item on FC2. Geoff

**Comment by AlOneill** [comment]
I have a number of problems with this request:

1. @geoffj-FUG I do not know what you mean by "under the Handbook tab of the Your Actions menu item". Do you mean somewhere on this page: https://test3.freecen.org.uk/cms/freecen-handbook ?

2. I cannot find a page named "Spreadsheet Help" or similar on my computer — 3 years and 2 laptops on — I cannot remember the details of what I was trying to do

3. @DeniseColbert , even if I could find the file, both it and the Google Doc referenced above describe FC 1 spreadsheets where setting the column width to the correct number of characters combined with using a monospace font served a very practical purpose — that purpose does not apply to FC 2 files, as I understand things

I _could_ put together some generic advice (i.e. that should work with any spreadsheet software, not only Excel) for adjusting the column widths to make them the width of the **column headings** — or whatever is going to help transcribers best. Is that the headings or is something else more useful?

Where should the advice be put?

**Comment by geoffj-FUG** [comment]
Alison

 

The date of the story’s original creation certainly directs it to the FC1 spreadsheet.

 

You are correct in that FC2 spreadsheet columns are not width restricted. I suspect that your thoughts that this is about setting the number of characters in a column and using a fixed width font is probably correct.  The column headings in FC2 spreadsheets have no relationship to the number of characters allowed, nor does the column width need managing..

 

In the absence of any up to date information I would surmise that this story is no longer required and can be closed. I stuck my oar in because this story had recently been re-allocated. Sorry.

 

Geoff

**Comment by DeniseColbert** [comment]
Irrelevant so closing
