### ISSUE TITLE
Convert Alison's listing of Countries as OVF and OVB for Freecen2 Places

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#688]
See also #684 which is blocked by this story, and may not be needed

**Comment by AlOneill** [comment]
Re the Milestone, surely this is needed for volunteers (to complete POB CHP) as much as for researchers?

**Comment by PatReynolds** [comment]
I thought OVB and OVF came from the Census,  not the transcriber.  If the censuses all say a country name, why use OVB/OVF?

**Comment by FreecenBren** [comment]
The census only says the country and sometimes the town/village etc.
It also can say if they are ‘Naturalised British Subjects’

If it says that then we use OVB whatever the country of Birth in the CHP
column. In the POB we enter the details that the enumerator has entered.

So born in New York, USA we will use OVF unless it says ‘Naturalised
British Subject’
If it does not say that then we go by Alison’s list, and either enter OVB
or OVF.
So India, Australia etc. will all be OVB

**Comment by geoffj-FUG** [comment]
As the Validaotrs gradually populate the Place Names Database this information will be available there, together with Lat/Long and link to Google Maps and a relevant web page. The Database does not just have Countries it has places within countries.
The list will then become defunct (probably about 12 months time).
Geoff

**Comment by AlOneill** [comment]
**Some places are time-sensitive:** for instance, the Ionian Islands (Corfu, Ithaca, Kephalonia, Kythira, Lefkas, Paxos and Zakynthos or Zante) were British **from 1809 to 1864 only**. In such cases the date of birth is important in deciding whether OVB or OVF is appropriate (in the absence of other information in the census entry). Will this be reflected in the database?

**Comment by geoffj-FUG** [comment]
Alison

 Most validators will plump for OVB and that will be correct most times. 

In reality we don’t know whether a person not born in the UK is OVB or OVF if they appear to be OVF in the census. That is because we do not know their parentage or other circumstances. It was not important until the 20th Century when it starts to appear as a census question.

The Ionian Isles will be entered into the database as a default of OVB. If a person has been transcribed as OVF then it will be up to the validator to resolve it. The years that they were OVB should appear in the Notes in the Place Names Database.

 Geoff

**Comment by geoffj-FUG** [comment]
Alison

 

Most validators will plump for OVB and that will be correct most times. 

 

In reality we don’t know whether a person not born in the UK is OVB or OVF if they appear to be OVF in the census. That is because we do not know their parentage or other circumstances. It was not important until the 20th Century when it starts to appear as a census question.

 

The Ionian Isles will be entered into the database as a default of OVB. If a person has been transcribed as OVF then it will be up to the validator to resolve it. The years that they were OVB should appear in the Notes in the Place Names Database.

 

Geoff

**Comment by geoffj-FUG** [comment]
Alison

 

I have attached a spreadsheet (to your direct copy of this email).

 

Can you transfer your OVB information to this spreadsheet (including latitude and longitude) so that it can be uploaded directly to the Gazetteer, please?

 

In every case you should enter the Chapman Code as OVB. 

Genuki etc column is the proof that it exists (e.g. Wikipedia) and Source is the web address.

 

That will effectively complete this story.

 

Geoff

**Comment by AlOneill** [comment]
Blimey! I walked straight into that one.

This will be a biggie, because:
* My listing is for the 19th century only — expanding it to cover the 20th century will be complicated and pains-taking
* I currently have no latitude & longitude information (CEN1 did not require it)

The spreadsheet will take me in the order of months to complete, so if anything about your request was said in jest, now is the time to say so :-)

I have a bunch of questions and am kicking off with:

1. Can I take it that 'Grid reference' and 'Latitude & Longitude' is an either-or situation? (I don't know a source of world-wide Mercator grid references, unless Google Maps carries that information, or similar?)
2. For a large geographical area, which nearly all of these are, how should I determine a single latitude and longitude? (Whatever the method, the figures could change with time, with changes to the extent of territories, location of capital city and what-not.)

**Comment by geoffj-FUG** [comment]
Alison

 

Just do a few at a time. They will gradually get done. We can upload spreadsheet page(s) in batches.

 

Grid references are only UK based. So you will only use latitude and longitude.

 

I get latitude and longitude simply by Googling place latitude and longitude. A decimal comes up and that can be copied and pasted into the 2 cells and then edited. Note that South and West are both negative when you edit the cells. So for New Zealand you would simply Google ‘New Zealand latitude and longitude’ and it comes up with  40.9006° S, 174.8860° E. You will enter this as -40.9006 and 174.8860.

 

When you click on Locate in our Gazetteer Google maps will take you to about the centre of the country. It is up to the researcher then to explore further.

 

Geoff

**Comment by geoffj-FUG** [comment]
Alison

 

PS – If you go to the FreeCEN2 Gazetteer you will see what I did with the Ionian Islands. Search Ionian with no County selected and it will bring up all the entries.

 

Geoff

**Comment by PatReynolds** [comment]
We should (some how / somwhere record that we are using the WSG84 (maybe add to the About page?)

Just in case (would hate to find that I should have mentioned this before) and it is news to Alison or anyone else working on coodinates:  ... nb that Google uses N and S, E and W for lat and long.  South and West are  recorded as negative,, eg the -40.9006 in Geoff's example = 40.9006S  Piositives (e.g. 174.8860E in Geoff's example) are simply recorded as 174.8860

**Comment by geoffj-FUG** [comment]
Pat

 

There is a thorough explanation on latitude and longitude in the Handbooks.

 

Geoff

**Comment by AlOneill** [comment]
I've converted my original listing of 19th century OVB territories to CSV and have created the extra columns (fields) required.

@Captainkirkdawson @geoffj-FUG
Qualifying dates are currently expressed using en-dashes (rather than hyphens — I'm a typography nut, after all!), for example: –1801, 1810–1816, 1820–. As such dates will be in the Notes field, I'm going to assume that a UTF-8 en-dash is acceptable here, unless I hear otherwise. TY

**Comment by geoffj-FUG** [comment]
Ali

 

Is the list in spreadsheet form? If so can you send to Kirk and he can upload it.

 

Thanks

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG the listing (CSV spreadsheet) is nowhere near ready for upload. I'm about one-fifth of the way through a first pass — adding latitude and longitude, alternative names and checking qualifying dates into the 20th century. Some parts of the world, e.g. southern Africa, are complicated and will need a second pass at least.

**Comment by geoffj-FUG** [comment]
Alison

 

That’s fine. I misunderstood your previous update.

 

Geoff

**Comment by PatReynolds** [comment]
There needs to be a policy decision on how to proceed.

**Comment by geoffj-FUG** [comment]
Pat

 

The process exists.

 

There is a standard spreadsheet into which Alison is putting her entries. It is the same spreadsheet as we used to add the London places to the Gazetteer.

 

When Alison is ready she will send us the spreadsheet and all the places will be added to the Gazetteer. That will give us a comprehensive list of overseas places that are all OVB Chapman Codes. It will be available to all our volunteers.

 

Geoff

**Comment by geoffj-FUG** [comment]
Alison
I think that you should look at story #1310.
It may make this story obsolete. However the information collected so far will still be useful as it will still enhance the Gazetteer.
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG As far as I'm concerned, this story, _is_ obsolete. I've only made a first pass through British Europe and Africa, producing a list of mainly obscure places that is not ready for adding to the Gazetteer and might never be needed for the census returns. Does it not make more sense for validators to add to the Gazetteer only those places that are needed? My listing so far would clutter the Gazetteer rather than enhance it :-)

I'm not bothered that my findings so far will not be used — it's far more important to get the process right.

I'm aware of #1310 — I sighed with relief when I saw it!!

**Comment by geoffj-FUG** [comment]
I have asked for #1310 to go ahead. If that happens this story will not be required.
Geoff

**Comment by geoffj-FUG** [comment]
Story #1310 appears to be going to happen in the near future. When #1310 is completed this story can be closed

**Comment by geoffj-FUG** [comment]
Once story #1310 is completed in June this story will no longer be needed.
Geoff

**Comment by DeniseColbert** [comment]
See above, closing
