### ISSUE TITLE
Implement  Source Sans Pro Regular as basic font

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#731]
General trustee opinion is  a change is needed and accepted Source Sans Pro Regular.

Will likely impact the table displays

**Comment by Captainkirkdawson** [comment]
Need to be assessed at systemwide before any decision is taken at individual app level

**Comment by PatReynolds** [comment]
Before assessment, alternatives need to be explored, as we know this proposal demands very significant resources.  I will open a story for this.

**Comment by richpomfret** [comment]
Ready for user testing over on TEST3.

**Comment by DeniseColbert** [comment]
Tested and working well. Far preferable to light version!

**Comment by PatReynolds** [comment]
@suffolkroots and @Sherlock21 as folk who have been alerting us to the issues with contrast since before I came on board, I thought you might like to have a look at https://test3.freereg.org.uk/ to see if we've managed to achieve sufficient contrast to solve the wishy-washy-hard-to-read text issue.  We are almost there with colour contrast, and have had excellent UX volunteers working on spacing on FreeBMD2 that we can implement on FreeREG.  Thanks, Pat

**Comment by richpomfret** [comment]
@Captainkirkdawson let's roll this out across projects.

**Comment by suffolkroots** [comment]
I was unaware of any testing request re this issue. Having now looked at T3 it is obvious that the font in the buttons is far too small.

**Comment by suffolkroots** [comment]
No nothing of this, never posted on it, so was unaware of any testing request. Alerted incidentally today, first comment---font in buttons is far too small.
