### ISSUE TITLE
Consider the future of County Coverage Pages 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#747]
Examples of county pages
http://freepages.genealogy.rootsweb.ancestry.com/~bowbren/index.htm
http://www.mborrill.org.uk/Rutland
http://www.rootsweb.ancestry.com/~sctfc/

Is this information best positioned in one or more of the following
* About (visible to researchers, either in a new subsection, or in the new 'history' subsection?
* details' section of Database Coverage?
* information for transcribers and information for coordinators (link from their pages)?
* somewhere else

**Comment by Captainkirkdawson** [comment]
Perhaps we also need to consider the future of the Database Coverage pages. From a researcher perspective they are a horror

**Comment by geoffj-FUG** [comment]
I have added this as a note so that it doesn't get lost.
In CSVProc we have given the Coordinator the ability to break a large piece up into smaller pieces (min size 1ED) and identify it by adding _a (underscore plus a letter) as a suffix to the piece number. 
The 1851 PARMS has also bee broken up to avoid civil parish duplications being rejected.
The question is "How does the system now know when a piece is completed?" 
The 1851 PARMS breakup is easy - we can treat each sub-piece separately and we know what they are from the PARMS. 
The pieces broken up by the Coordinator are not obvious to the system. The Coordinator has the record of this.
Geoff

**Comment by Captainkirkdawson** [comment]
This is highly dependant on how we integrate the information from FR1 loaded data with FR2 loaded data.
It is also linked to Requirements for Incorporation Statistics#998

**Comment by PatReynolds** [comment]
For review for closure and/or new stories now the Coverage pages have been re-implemented.
