### ISSUE TITLE
Add language to search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#756]

**Comment by Captainkirkdawson** [comment]
Assuming this is simply a filter of a broad search then it is relatively straightforward

**Comment by Captainkirkdawson** [comment]
The rake task shows the following content of the language field
1841/1851 empty as is 1871
1861 "o", "i", "c", "u", "r", "e"
1881 "-", "G", "x"
1891 "W", "-", "B", "E", "G", "x",  "N"

I have no knowledge of their meaning.

Guidance is needed on interpretation and how to proceed.

CEN1 provided a drop don selection of Any English Welsh  and Both

**Comment by FreecenBren** [comment]
1841/1851 empty as is 1871

1861 "o", "i", "c", "u", "r", "e"
None related to Language
Would be interested to see an example where these are used.
Only the U recognised as a genuine letter to use after the address column.
U = Unoccupied and that relates to all the census so again which column was it entered under.
Should only be used in column H  when it was Transcribed.

1881 "-", "G", "x"
See below for 1891
Again none related to Language.

1891 "W", "-", "B", "E", "G", "x", "N"
W = Welsh Spoken
B = English and Welsh Spoken
E = English Spoken
X = query on transcription
N = Schedule not used or Page not used, but also could be one of the  occupation status for 1891 census only.
*	= No place of birth,  or nothing written for that column (refers to any column that is compulsory but nothing to enter so they use a – otherwise CSVCHECK will give it as a WARNING.)
G = nothing as not one of the options. (Would be interested to see which PIECE has it.
 
Again need an example or two to look at why it is being used.

**Comment by AlOneill** [comment]
I believe "G" stands for Gaelic spoken. It was asked in SCT census from 1881.

**Comment by AlOneill** [comment]
In 1881, people in SCT were asked only, "Do you speak Gaelic?".

In 1891, the question in SCT was English, Gaelic or Both: so a "B" in a SCT census meant yes to both Gaelic and English, *not* Welsh and English.

**Comment by FreecenBren** [comment]
The B  then has 2 uses
in the England and Wales Counties census for those speaking both English
and Welsh.
In Scotland Counties B = Both  Gaelic  and English spoken.

The *Fields PDF* is what we refer to nowadays, that *incens* is not used.
But we have to remember that a lot of the transcriptions were transcribed
when we all did use it.

This is what Rick Parsons wrote about those letters.
https://west-penwith.org.uk/fctools/doc/reference.html

This information has been obtained by studying the format of actual files.
Some subtle details may have been missed.
IN-CENS filesRGnnpppp.DAT and HO51pppp file format

(the leading letters are the column names from "dat2csv -a" output and the
next letter is the column name for the default output)

-a  DEF

A       0  1 Deletion marker (D or blank)
B       1  4 Not used. Was Registration district - this usage is discontinued.
C       5  6 A six digit number (leading zeros) which counts the households
D      11  4 A four digit number (leading zeros) which counts members in each
             household
E   A  15 20 Parish name (I don't check this, it is up to you to get it right!)
F   B  35  4 Enumeration district (3n+1a, the remaining numeric fields have
             trailing spaces)
G   C  39  5 Folio number (4n+1a)
H   D  44  4 Page number (4n)
I   E  48  4 Schedule number (3n+1a)
J   F  52  5 House number (4n+1a)
K   G  57 30 House/Street name (default -)
L   H  87  1 Uninhabited flag (b, u, v, n, x or -)
M   I  88 24 Surname (capitals, default -)
N   J 112 24 Forenames (default -)
O   K 136  1 Flag for name fields (x or -)
P   L 137  6 Relationship (default -)
Q   M 143  1 Condition (M, S, U, W or -)
R   N 144  1 Sex (M, F or -)
S   O 145  3 Age (no default but 999=unknown/unreadable)
      148  1 Age unit(y, m, w, d or -)
T   P 149  1 Flag for detail fields i.e. rel/cond/sex/age (x or -)
U   Q 150 30 Occupation
    R        Employed Status (extracted from occupation field)
V   S 180  1 Flag for occupation (x or -)
W   T 181  3 County code (3a capitals, no default but UNK if not known)
X   U 184 20 Birth place (default -)
Y   V 204  1 Flag for birth place (x or -)
Z   W 205  6 Disability (default blank)
AA  X 211  1 Language (W, E, B, G or blank)
AB  Y 212 44 Notes (default blank, no case conversion)
      256    Start of new record

Most of the alphabetic fields are converted so that each word starts with a
capital letter. The exceptions are shown above. The algorithm used in
IN-CENS, does not allow for initial punctuation such as ( or " but csv2dat
does a better job.
HO41pppp.dat file format

The same as the RGnn file format except where shown

B    1  4 Book number (4n) (ENG/WLS) Was 1841 CON Parish number
             - this usage is discontinued.
C    5  6 Household number (sometimes with trailing spaces)
D   11  4 Members in household (sometimes with trailing spaces)
I   48  4 Blank (schedule not used)
J   52  5 Blank (house number not used)
P  137  6 Blank (relationship not used)
Q  143  1 - (condition not used)
W  181  3 County code (3a capitals - INC, OUC, IRL, SCT, OVF, UNK)
X  184 20 Blank (birthplace not used)
Z  205  6 Blank (disability not used)
AA 211  1 Blank (language not used)

Very useful site.

**Comment by PatReynolds** [comment]
My summary: only 1891 contained language, so search only needed on 1891 census.
Search opetions:
Welsh only
English and Welsh
Gaelic only
English and Gaelic
Other (presume English only)

If you want to cut time processing (and add time developing) then only searching for Gaelic options on Scottish records, and only for Welsh options on Welsh records would be implemented.

**Comment by FreecenBren** [comment]
Unfortunately that is not the case.
 
The Wales census have them also in the 1861 census.
The W  for Wales spoken etc., is often written  alongside the schedule number on the images but we enter it in column X.
 
Examples from  Caernarvonshire 1861 attached.

**Comment by PatReynolds** [comment]
Please implement dropdowns as above, for all censuses.

**Comment by Captainkirkdawson** [comment]
Code available for evaluation on test3 CEN.

**Comment by PatReynolds** [comment]
Searched Alcock, speaks Welsh (only search terms used).  Started with a wide search, too many results, narrowed it down by birth year to 1870 to 1890, too many results.  No results 1870-1874 or 1875-1880 or 1880-1890!

Looking for Jones, speaks both English and Welsh, none born in 1790 "too many" in 1791. Trying to narrow down (disabled, or widower, first name Mary or Mari) got none.  

@richpomfret or @DeniseColbert could you try to test this one, too, in case I'm doing something wrong?

**Comment by Captainkirkdawson** [comment]
An example follows. No language:
![jones1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9cd39008-8be1-4085-8a30-8742598c05aa)
Welsh
![jones2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/68a98ed1-cd2b-41c1-af32-91080c0758cd)
Both 
![jones3.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/99ebac45-ac84-4958-b069-dfee62a6c38a)

However the details has NO field for language. Story #782 written

**Comment by PatReynolds** [comment]
This now appears to work, however we don't show the result in the detailed results page (no Language column!), so cannot test thoroughly.

**Comment by Captainkirkdawson** [comment]
There is supposed to be a language field in the detailed result for 1891 and Welsh Counties. However in my testing the field is NOT  present in the display

**Comment by Captainkirkdawson** [comment]
A bug was found in the code and corrected. Language is now in the detailed results for 1891  in counties for both Scotland and Wale. applied to test3

**Comment by PatReynolds** [comment]
1891 now works fine for Welsh counties.

Issue with Scotland:
Search for MCDONALD, born Inverness-shire, resident in Caithness three results, two speaking both, one with a dash. But filtering by Both gets neither.  

1861 is difficult see (Brenda's comments 10 Dec 2019) that Welsh was recorded "often written alongside the schedule number on the images but we enter it in column X." But this field has in it "o", "i", "c", "u", "r", "e" - no W, or B or X. I suppose it might be C for Cymraeg (Welsh) and E for English.  Welsh for both is ddau, dau or nau (Welsh changes at the front of words, as well as the end, which makes it difficult to learn, and to guess what a welsh speaking transcriber would be using as an initial. 

Language needs adding for 1881 (see Alison's comment on Gaelic, 9 Dec 2019.

Tested McDonald residence 1891 Caithness: 454 results, Gaelic 6 results, Both 148 results.  Seems to work fine (think I didn't start again last time but 'revised results'.

**Comment by Captainkirkdawson** [comment]
No idea on this one.
Will research next week.
Have abandoned deployment

**Comment by Captainkirkdawson** [comment]
Deployed
