### ISSUE TITLE
Information for Coordinators Help page has gone

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#763]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/72109c10-e26e-440b-8f2c-8b8337e706e5)

Possibly as a result of Test 3 transfer?

**Comment by Captainkirkdawson** [comment]
The page is there as DRAFT hence not displayable; If you want the page to be displayed you must remove its draft status and we will update.
Applies to all the pages in refinery where most are draft.

**Comment by PatReynolds** [comment]
The problem is: there was a page called (I think) Information for Coordinators.  It was not replaced by DRAFT Information for Coordinators. The DRAFT IfC page did not have the this-is-a-draft tickybox ticked, and therefore would have been displayed/findable, if there were any links to it, but there not being any links, did not appear in the slot for Information for Coordinators, hence the 404 error.  

So we need to recover the old page and resurrect it. 

But I still can't work out how the old page disappeared, other than it was mistakenly deleted from test3.  The instructions may need updating.

**Comment by AlOneill** [comment]
The problem was that there was no page called (plain) "Information for Coordinators" on test3.

A similar situation existed for "Information for Transcribers".

Both pages, with a short message only, now exist on live and on test3.

**Comment by AlOneill** [comment]
It turns out another page is also missing from "live" and test3: **About** is one such — still checking for others.

About does not have DRAFT in its title, but it is saved as a draft and so not viewable. I think that the most recent edits to about were fairly minor and to do with the setting out of "Why is FreeCEN changing".

The markup looks OK, so will save (without "Save as draft") as a viewable page on both live and on t3.
