### ISSUE TITLE
Create side bar adverts for FreeCEN

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#779]

**Comment by Captainkirkdawson** [comment]
@PatReynolds have created a side ad for CRN; looking at its deployment

**Comment by PatReynolds** [comment]
Looks good on test3 (and test2), thank you.

**Comment by Captainkirkdawson** [comment]
I am surprised at your comment @PatReynolds in my testing I only get one side ad and it changes to the other side on a refresh! still a work in progress
Also its delivering a smaller ad 120x600 although we are asking for 160x600.
Also it is set up to deliver the same ad likely should be different

**Comment by Captainkirkdawson** [comment]
@PatReynolds Did some reading and found that advertisers prefer 300 width to 120 or 160; putting one of those wider instead of 2 narrower one seems better; the first ad with that was much more pleasing and there is better variety.
Its running on test 3 let me know what you think. I put it on the right but changing it to left is no issue

**Comment by Captainkirkdawson** [comment]
Deployed
