### ISSUE TITLE
"Nearby Places" does not search nearby places

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#780]
A search for 'nearby places' searches places that are further away.  e.g. their are Alcocks in Newark and Northallerton, just over 100 miles apart.  But one place is not searched from the other, but places 200 miles plus away are searched.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/98468e9c-96e6-459f-8cf4-9919d1219a62)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/cf93f42b-8405-41a1-847a-8ed3a185ee67)

NB the other places searched on FreeCEN are unordered, on FreeREG they are ordered by distance (see image below)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/bbfb992c-87dd-4fba-bfa2-d2efa407d17d)

E3 U3 S5 C4: P15

**Comment by Captainkirkdawson** [comment]
It appears that the location field for places in CEN have NEVER been set. They all have the location [0,60] on both production, test3 and test2. The lat and lon are there but not the location field. The location field is the one used by nearby calculator. As a result ALL places in cen are in the same location!

**Comment by Captainkirkdawson** [comment]
Further research shows that the problem lies much deeper than an unset location field which is relatively easy to fix (a one time rake rake and some code to ensure it is always present and created when new places added;  estimate of an 8)
The deeper issue is that there are 2815 places with data in cen production of which 351 have a latitude of "60" and 354 with a longitude of "0". ie the default values.  Of these 279 are in Scotland, 63 in England 3 in Wales and 9 elsewhere.
Until these places are assigned valid latitude/longitude values and these are added to the location then the NEARBY feature WILL NOT function and clearly has not for several years.
I can program a rake task to list the places in error if that is required (estimate 5)
I recommend that the NEARBY feature in CEN be removed until these data issues are fixed.

**Comment by richpomfret** [comment]
Next steps - need a data manager. Also require Richard Light to assist.

**Comment by richpomfret** [comment]
@Captainkirkdawson to remove this function too. Also require a notice to let folks know.
