### ISSUE TITLE
GAP Report: a list of Census records which do not exist

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#786]
The GAP is for management,  and to assist researchers
Census records which do not exist, e.g. were on a boat which sunk and table of census records that are available, but we do not have available to transcribe. Integrates with the RAP (census records available for transcritption) and DAP
See FreeUKGen/MyopicVicar#2040 for the FreeREG GAP - some elements should may be imported for FreeCEN
Census records which do exist, but we do not yet have, with (for management) who has the images.

The GAP will tell a researcher if their search result did not include one or more GAPs.

**Comment by PatReynolds** [comment]
@Captainkirkdawson  is there anything which needs to be counted (ie. any implications for the report generator? i.e. story #93).

**Comment by Captainkirkdawson** [comment]
I think  a list of what is required by county basis would be good as part of the Records action

**Comment by PatReynoldsFUG** [comment]
Three pages, covering different aspects:

https://blog.nationalarchives.gov.uk/missing-from-the-census/ for information on mis-scans by TNA and similar omissions 

https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/ (section ten)

https://www.findmypast.co.uk/articles/census-for-england-wales-and-scotland-missing-pieces

**Comment by PatReynoldsFUG** [comment]
For discussion: how detailed does the GAP data need to be.  The FreeREG GAP is useful at a page level, because damage to a Parish Register might just be a few entries (corner of a page with spilled ink), pages (torn out) or whole register - as registers are in date order (mostly!) this might entail saying e.g. that Births 26 Dec 1722 to 4 Jun 1723 are missing - so the a GAP might only be reported to a user who includes Births for 1722 or 1723 in their search.

**Comment by DeniseColbert** [comment]
IF we can add fields to Parms (Vino to check) we could place two text fields, each with three options:

Available in the Universe: Yes, No, Part
Available in FreeCEN: No, Yes but not digitised, Yes and digitised

**Comment by geoffj-FUG** [comment]
In progress see #247

Geoff
