### ISSUE TITLE
Navigation buttons dissapear on previous/next dwelling

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#796]
Search finding
MCDONALD	Helen	Sister	U	F	14	General Servant Domestic	CAI	Latheron		B
(using language B) : moving to previous or next dwelling looses buttons for 'next record', 'back to results' 'refine rsearch' etc.  The same in an English 1871 search.

**Comment by Captainkirkdawson** [comment]
Looks like we introduced a regression somewhere along the line. This is an urgent show stopper on release

**Comment by PatReynolds** [comment]
May be unrelated, but on live looking at 
(https://www.freecen.org.uk/search_records/5a153c30f4040b9d6e4c67cd : viewed 24 Jan 2020), Sarah ALCOCK in household of Thomas ALCOCK, Bennington Grange, Newark, Nottinghamshire, England; 1851

moving to second next dwelling generates a 404 error.  Maybe hit last record in piece?

**Comment by FreecenBren** [comment]
If you do the same search in FreeCEN one you will find that the next but
one record relates to a missing schedule number but FC1 shows it and FC2
shows the error 404. I will look at the original  CSV and see why. We
recorded a Missing schedule of Zero. It could will be an empty dwelling but
will double check.
Why FC2 does nothing is out of my control but the CSV might give me a clue.
Will let you know my findings when I get home to look at it.

**Comment by helhyde** [comment]
Just tried with Agnes Austin, born 1840 - 1860, resident Horncastle,
Lincolnshire: moves forward, fine. Backwards 2 and #404 error.


.Same but resident Manchester, no problems four forewards or back.

**Comment by Captainkirkdawson** [comment]
@PatReynolds your recent postings are for a very different issue

**Comment by Captainkirkdawson** [comment]
Have developed a solution to the original issue. That fix deployed to test3
Have not the slightest idea on the issue behind the later comments. Will take a few days to assess.
Placed deployment on hold.

**Comment by Captainkirkdawson** [comment]
@PatReynolds are you using the search record link given to you in a citation? if not how are you getting such a link?
There is an issue in production of displaying a link from a citation. 
Applies to both REG and CEN. A fix was developed for REG over Christmas but has yet to be deployed to production. So the fix is apparent on test3. That fix would also apply to CEN.

Now you might not like the fix. The fix implements that a link from a citation you do NOT get navigation links. Why? Because the link to a specific individual which is what a citation is does NOT have the context from the search that generated the record hence we know nothing other than that one record.

**Comment by Captainkirkdawson** [comment]
deployed
