### ISSUE TITLE
Add other Census years on to FreeCEN

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#806]
We now have data from 1901, Somerset.

An attempt to load this to FC1 failed, as it is only set up for 1841-1891.

For discussion on 19th Feb: is it worth changing on FC1, or better to wait for FC2 direct upload?  Costs/timescales will help to inform choice.

**Comment by richpomfret** [comment]
Wait for FC2 direct upload. Can use this as a test case for direct upload. @AlOneill to send example to Pat and @PatReynolds to then discuss this with Brenda.

**Comment by AlOneill** [comment]
Turns out that the changes I mentioned occurred in 1911 rather than 1901 (doh!).

Seems that 1901 returns collected much the same information as later 19th century returns, except that there is now a separate column on the enumerator's summary for "Working at home". (I have looked at ENG and SCT, but do not have access to WLS.)

However, in SCT, the number of "rooms with windows" (which makes for some grim reading and was collected since 1861) has never had its own field — I was told to put a note in column Y (Notes field). Do we continue this practice or create a new field?

**Comment by Captainkirkdawson** [comment]
As part of the upload project 807 support for 1901 and 1911 is being provided.

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret @FreecenBren 
As we move forward it is essential that we recognize that 1901 and 1911 census returns will not be entered into CEN1. 
We will accommodate the new fields and other adjustments through the implementation of the Flexible CSV approach adopted for REG in the upload and processing of data into CEN2.
CEN is well positioned to use this approach as it already incorporates the concept of field specification with the second line of the CSV file specifically the column headers.

**Comment by geoffj-FUG** [comment]
I agree with Pat.

 

FreeCEN1 is essentially an archive file, though some functionality is still being used.

 

This should be FreeCEN2 only. Coupling it with direct upload makes sense.

 

Geoff

**Comment by Captainkirkdawson** [comment]
We are adding At home and Rooms as 2 new fields for the 1901 census

**Comment by Captainkirkdawson** [comment]
What do we need for 1911

**Comment by geoffj-FUG** [comment]
Agreed

 

Using Rooms allows for the 1901 <5 rooms and the 1911 number of rooms.

 

At Home allows entry of the data that is additional to 1901.

 

Geoff

**Comment by geoffj-FUG** [comment]
The following information is recorded in 1911:

 

1911

As 1901, with extra questions:

*	For married women only, the number of years of their present marriage, the number of children born of that marriage, the number still living, and the number that had died.
*	As well as their occupation, the industry in which the person was employed. If employed by a government, municipal or other public body, the name of that body.
*	Parish and county of birth for anyone born in the UK (which included all of Ireland). If born elsewhere in the British Empire, the colony or dependency, and the state or province.
*	For anyone born outside England and Wales, whether they were resident or visitor in the country.
*	Nationality of anyone born overseas whether British by parentage, British by naturalisation (including year of naturalisation) or, if a foreign national, of which country.
*	In the Infirmity column, the age at which the person had become afflicted.

(Source: National Archives)

 

My initial overview of 1901 – 1921 was:


At Home

1901 and 1911 at home

I believe it is also in 1921


Number of Rooms

1901 if Rooms < 5, 
1911 Rooms 

I believe it is also in 1921


Nationality

1911

No field required. Handled by OVF / OVB


Years Married

1911 onwards

I believe it is also in 1921


Number of children born

1911 onwards

I believe it is also in 1921


Number living

1911 onwards

I believe it is also in 1921


Number deceased

1911 onwards

I believe it is also in 1921. These 3 children fields can also be used as a checksum.


Place of employment

1921

 


Industry

1921

 


Materials 

1921

 


Employers name

1921

 

 

 

I had not picked up before on the year Naturalised entry. Given its rarity I think that could be entered in Comments (currently Column Y). Ditto for Resident / Visitor if born outside of UK.

 

There is also an issue in 1901 regarding the language spoken if you lived on the Isle of Man. If so we should be able to adapt the Welsh spoken field. If that is currently a logical field it may have to be made so that it accepts a code. (e.g. W for Welsh, E for English, G for Gaelic etc).

Question – Does this also apply to Scotland?

 

So my table needs reviewing. It needs to be read in conjunction with a census page on the screen.

 

I will throw it open for comment.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

There is also an issue in 1901 regarding the language spoken if you lived on the Isle of Man. 

 

We should be able to adapt the Welsh spoken field that already exists in the Welsh census. If that is currently a logical field it may have to be made so that it accepts a code. (e.g. W for Welsh, E for English, G for Gaelic etc). It can then be used universally.

 

Question – Does this also apply to Scotland? I don’t know too much about Scotland.

 

Geoff

**Comment by Captainkirkdawson** [comment]
This post was original on a different story but place here for better context. The originator was Geoff

Kirk



Scotland 1911



I don’t have access to Scotlands People so cannot view a real census book. The census records were transcribed into an Enumerators book as in previous years.

The reference was different. The sample page is 1911/739/1 Page 5.



There were additional fields:

“There were new questions relating to fertility of marriage:  on duration of marriage;  the number of living children born to each marriage;  and the number alive at the time of the census.

There were changes to several others:

categories for people with disabilities were revised and the introductory section to the third report on the 1911 census refers to the intended use of the terms as:

lunatic - in cases where the infirmity had been acquired during life

imbecile - in extreme cases where the infirmity had existed from birth or an early age

feeble-minded - in milder cases where the infirmity had existed from birth or an early age.

the question on occupation was extended to find out which industries or services a worker was connected to in addition to their personal profession or occupation

the question on place of birth was extended to include nationality for those born in a foreign country, that is, outwith British territory, colonies and dependencies. “

(Source: nrscotland)



So the complete set of fields on the census page, but not the fly to the ED, are:



Civil Parish and Parish Ward

Ecclesiastical Parish

School Board District

Burgh Ward of

Parliamentary Constituency

Municipal Burgh



Address Number

Street

Unoccupied or Building in Progress

Number of rooms with one or more windows

Name and Surname

Number of Persons I Household

Relationship to Head

Age in Male or Female column

Gaelic or G & E

Years married

Whether married, single or widowed.  There are also numbers in this column in the sample image. What are they for?

Years married

Children living

Children deceased

Profession or Occupation

Industry

Employer, Worker, Own Account

If working from home

Birthplace

Nationality if born in a Foreign Country

Disability (limited number of Codes)



This is different to the England and Wales census and may explain some of our spare fields.



I am going to try and find someone with access to Scotlands People who may be able to advise me on the full ED formats.



Geoff

**Comment by PatReynolds** [comment]
https://www.nrscotland.gov.uk/research/guides/census-records/1911-census has images, if that helps.

**Comment by PatReynolds** [comment]
@rhodamackenzie  tos ee if she can find the initial pages of each year to send to @geoffj-FUG

**Comment by rhodamackenzie** [comment]
Sorry folks, I haven’t had an notifications for 10 days! Here I am again, Geoff, in reply to your list of Scotland census 1911, I attach the sample sheet from the front pages.
These are the fields:

Civil Parish and Parish Ward
Ecclesiastical Parish or Quoad Sacra Parish
School Board District

Parliamentary Burgh
Parliamentary Constituency
Municipal Burgh
Burgh Ward
Special Water District
Special Drainage District
Special Scavenging district
Special Lighting District
Island
Number of Schedule
Road, street, &c., and No. or name of House
Houses Inhabited
Unoccupied or Building in Progress
Number of rooms with one or more windows
Name and Surname
Number of Persons in House
Relation to Head of family
Age in Male or Female column
Gaelic or Gaelic and English
Whether married, single or widowed.
Duration of marriage
Children born alive
Children still living
Personal Occupation
Industry
Employer, Worker, Own Account
If working from home
Birthplace
Nationality if born in a Foreign Country
Disability (Codes 1,2,3,4)

**Comment by geoffj-FUG** [comment]
Thanks Rhoda

 

I will compare this with my listing.

 

Geoff

**Comment by rhodamackenzie** [comment]
Also, for second language, it can only be Gaelic or English and Gaelic, so code as 1/2?

**Comment by geoffj-FUG** [comment]
Rhoda

 

The field is also used for Welsh W, Manx M, Manx and English etc. So we have to use a letter(s)

 

Geoff

**Comment by rhodamackenzie** [comment]
Oops 3 options in Scotland then G, E or GE
Rhoda

**Comment by rhodamackenzie** [comment]
I tried to attach a pdf file, it hasn't worked, how do i do this?

**Comment by rhodamackenzie** [comment]
[ScotlandsPeople_C1911_sample sheet.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4487279/ScotlandsPeople_C1911_sample.sheet.pdf)

**Comment by PatReynolds** [comment]
That's uploded just fine, @rhodamackenzie

**Comment by geoffj-FUG** [comment]
Rhoda

 

Was English recorded or was it the daefault? It was the default elsewhere.

 

Geoff

**Comment by rhodamackenzie** [comment]
Yes, English was the default so that field should always G or G&E or blank (for English)

**Comment by Captainkirkdawson** [comment]
Census 1901 and 1911 fields are incorporated into https://docs.google.com/document/d/1CLd_1CsVQcTyjtAFwsmSqQAm8NC02jmV/edit
Believe this should be closed.

**Comment by PatReynolds** [comment]
Agreed, @Captainkirkdawson so closing.
