### ISSUE TITLE
Convert on line  freecen_csv_entry into a search record

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#831]
Take a freecen_csv_record and convert to search record

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @PatReynolds A first version of the conversion has been applied to HO107_895 for RUT in 1841.
The initial issue encountered was this is a hundred see story #975 for a policy decision on this.
To proceed I created a freecen2 place called Stanford with location and edited the piece to use this place name
The file was then converted and is available for searching on test3.
An example I have been using is a search for Attay in Rutland.
There you will see the Results page, and the details page. The latter is a new display. All features such as citations and print format work (The latter needs tweaking) There is the ability to look at neighbouring dwellings and also next and previous search results.
Please have a look at it.
Please remember this is a first version.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG The first version of the conversion has been applied to your RG14_14114 file (1911) and is available for searching on test3.
A search of smith in 1911 will provide sample search result as well as access to the details for each of the individuals using similar dwelling display. Similarly you can step through search individuals as well as dwellings.
The display is a little cramped but they are all valid fields for that year.
The conversion process is NOT ready for your testing yet. This was a proof  of concept stage and a demonstration that the search works and displays the results appropriately.
I am sure you will want to search for other names.

**Comment by geoffj-FUG** [comment]
Kirk
Looks good. We are really on our way now!
I did a search on my iPad too and the result was quite readable despite the amount on information on the screen. I chose William Smith and he had a family of 6.
If I was a researcher I would accept that because there is a complete family for me to read about.
Just a few queries:
Is there going to be a key to the Occupational category? The meaning is not obvious to the lay person
I also presume that the folio/page is going to be brought down. The Folio / Page are not appearing in the citation. They are critical to locating a record to verify it.
When I go to Next Dwelling I lose the citation buttons. They are not there when I go back to the original record either. I get them back if I go to the search results and select William again.
I understand that some of these things may well be in hand, but thought I should mention them so they do not get missed.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Thanks 
The CSV displays follow the practices of the current displays. 
There are no current changes planned (other than mobile version) so we need stories if you think there are changes or improvements to be made.
Have added
Do we add explanation for Occupation Category #977
Do we move folio/page number information to dwelling line#979
Citation button not there when you go back to original dwelling#980

WRT to **The Folio / Page are not appearing in the citation** They are not part of the citation format which is used to identify where a researcher located the information. The citation is not specifically used to locating a record to verify it.
WRT to **When I go to Next Dwelling I lose the citation buttons.** This is the same for the current display. The next and previous dwellings are not related to the individual  who was the subject of the search

**Comment by geoffj-FUG** [comment]
Story #1028 has affected this as we have to recreate the files to Incorporate. This will be tested once #1028 has been tested.
Geoff

**Comment by geoffj-FUG** [comment]
Citation Button is now behaving itself.
Folio/Page is displaying on screen OK
Other issues covered elsewhere.
This can be closed
Geoff
