### ISSUE TITLE
deleted flag

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#832]
Is this a derived or entered field.

If derived based on what??

**Comment by geoffj-FUG** [comment]
Kirk

 

Which field?

 

Geoff

**Comment by Captainkirkdawson** [comment]
The deleted flag; sorry it was in the story title

**Comment by geoffj-FUG** [comment]
Kirk

 

That is a good question. Is the deleted flag needed?

 

Originally it was used in WinCC so that the proofreader could give a soft delete. The Validator could then confirm the deletion or restore it to the data. Once the piece was uploaded the soft delete became a hard delete (my presumption) and the record did not appear in the database.

 

Then WinCC got attacked by Virus checkers and eventually it was killed by hardware enhancements. So we went to spreadsheets and the soft delete became a hard delete and the field was defunct.

 

The answer to the question requires a policy decision – do we continue to allow proofreaders to do hard deletes in the csv file?

If the answer is Yes, we no longer need the field;

If the answer is no, we need the field but we also need to include it in our procedures.

 

In general proofreaders are experienced volunteers. I have no compunction in allowing my County proofreaders to hard delete and I am not aware of any problems that have arisen. Having a procedure in the new csv process is an added problem, and removing the soft deleted record is an additional step. So my view is that we do away with the soft delete and therefore the field. 

 

But I am not the arbiter of these things.

 

Regards

 

Geoff

**Comment by PatReynolds** [comment]
HI @Geoff, could you explain what would be deleted/why?

**Comment by geoffj-FUG** [comment]
Pat

 

As an instance - In the census an enumerator may have made an entry and then drawn a line through it. The transcriber has then transcribed it ‘as is’. 

 

The .csv file was then changed to a .dat file and loaded into WinCC. So there is an incorrect line in the data file. The proofreader would delete it, but it would be a soft delete.

 

The piece was then passed to the validator. It was still a .dat file so nobody could look at it as they can with a .csv file. The deleted entry would display on the screen and the validator would examine it. They could agree and leave the soft delete or they could disagree and remove the soft delete. 

 

Somewhere in the system, presumably on upload, the soft delete would become a hard delete and the record would disappear.

 

Some pieces have whole pages that have been crossed out. 

 

There can be other instances such as a transcriber losing their place and repeating records that have already been done. There are various causes. They were reasonably rare, say 2 in a 3000 record piece.

 

I hope that helps.

 

Geoff

**Comment by PatReynolds** [comment]
Thanks, Geoff, that's just the information I was looking for.

**Comment by Captainkirkdawson** [comment]
Based on the input from Geoff it seems clear that the deleted flag is indeed needed and should be included in the CSV file.
