### ISSUE TITLE
Ability to load VLD files directly into FC2

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#834]
As part of the overall transition to FC2 we need to be able to load VLD files directly into FC2

**Comment by geoffj-FUG** [comment]
Kirk
@johnt-freecen has asked: Has any thought been given to converting a VLD file into the new format of file to be re-loaded into FreeCen2? Otherwise we will need to continue with the parts of the old system to handle corrections to the VLD files when we have a user correction to make. Steps in the procedure would need to be Download existing file, correct records in file, re-Incorporate file.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen There is a short answer, yes because we wrote this story and no because there has been no action on it since to move forward we have to have the CEN2 infrastructure working first. But it is likely getting time to moving this forward.
The initial thought is that we write a task that downloads the file in an appropriate CSV spreadsheet format and from there on it is no different to the processing of any other csv spreadsheet

**Comment by geoffj-FUG** [comment]
Kirk

 

The FreeCEN2 Traditional format aligns with the vld format pretty well. If we can make these 2 files fit together we can use our existing processes.

 

Geoff

**Comment by Captainkirkdawson** [comment]
CSVProc can handle the traditional format of csv file so there is no basic requirement to load a VLD file.
CSVProc will download the traditional headed csv file in the correct format for the year.
We can download a VLD file from CEN2 in csv format and it can be processed by CSVProc
Suggest this be closed.

**Comment by PatReynolds** [comment]
Downloaded VLD can be uploaded as other CSV using CSVproc - will go through same proofreading and validation checks (but this can be quite useful).
