### ISSUE TITLE
Change in field header names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#841]
@geoffj-FUG @rhodamackenzie @colin1959 
For the past 20 years FC has been using the following field (column) headings. 
Civil Parish,ED,Folio,Page,Schd,House,Address,X,Surname,Forenames,X,Rel.,C,Sex,Age,X,Occupation ,E,X,CHP,Place of birth,X,Dis.,W,Notes

Would there be objection if the CSV downloads used the actual field names ie

'civil_parish', 'enumeration_district', 'folio_number', 'page_number', 'schedule_number', 'house_number',                           'house_or_street_name', 'uninhabited_flag', 'surname', 'forenames', 'name_flag', 'relationship', 'marital_status', 'sex', 'age', 'individual_flag', 'occupation', 'occupation_category', 'occupation_flag', 'verbatim_birth_county', verbatim_birth_place', 'birth_place_flag', 'disability', 'language', 'notes'

This would make it feasible to introduce flexible ordering and field positioning in the future.

Some transcribers might find the change disconcerting but?

**Comment by rhodamackenzie** [comment]
I can’t see that being a problem, I have not seen one of the spreadsheets, but As long as there is space to fit the full words  in without making the visible page area too unwieldy, I see no reason why not. This leaves no ambiguity for new transcribers

**Comment by geoffj-FUG** [comment]
I am not sure if Rhonda and Susan are receiving this. Please let me know.
Kirk, Susan, Rhonda (and Pat and Brenda FYI)
I believe that we need to start at the top and drill down. That will let our Newbies catch up with Kirk and I a little.
I have attached 2 files. One is the New Process as I understand it. No detail just an overview.
The second is an appendix which contains a flowchart. I know it is a bit rough but the flowcharting in Word is not the best!
All this is done from the perspective of England and Wales pieces because that is what I am used to. I know nothing about Scotland so Rhonda might like to put us right in that regard as we go along.
Once we are all agreed on the content of these documents we can drill down to the content of the spreadsheet. 
Kirk is currently trying to build an aeroplane whilst it is in the air like the old Anderson Digital ad. Hence the ad hoc questions based on his understanding of FreeCEN. I would like to start at the top and drill down so that we don’t miss anything. It also keeps us all on the same wavelength.
One of the next things to answer is Kirk’s question on what fields do we need for 1911 so lets have a look at that as well. It keeps things going.
Your feedback on this overview would be appreciated.

 Geoff

**Comment by geoffj-FUG** [comment]
Kirk et al

 The original field widths were set in row 3 to guide the transcriber to the number of characters allowed. That automatically limited the number of characters in the column headers as a long name where there was a short entry allowed would have distorted the spreadsheet.

 We now have a major change. FC2 does not have the length limitations that FC1 had. To my mind that makes Row 3 obsolete (Factcheck please Kirk).  Eliminating Row 3 also removes the constraints on Row 2.

 With no constraints we can put whatever we like into the headings. However, caution is required as we don’t want to make the screen display too wide. So I would suggest one option is that we can use the new field names (that makes Kirk’s job easier because the field names are consistent). I would however suggest that if we do this for screen display purposes the row in the spreadsheet needs text wrapping. That will remove wasted space on the screen.

 For instance the uninhabited_flag is 16 screen characters but the field entry is one character. Wrapping it will split the text and save screen space. Occupation_category is even worse.

I have an alternative thought. If we can put shorter headings in the columns (say use Row 3 because it disappears anyway) and put the field names in Row 2 we can hide Row 2 and then the field names wont affect the display width on the screen. (Comments please) (Will that work Kirk?) The field names will still be there in the .csv file for programming needs.

I would like to do up sample spreadsheets and run them past the coordinators. They will have to deal with the transcribers!


Geoff

**Comment by PatReynolds** [comment]
Hi Geoff - edited your comment o remove repeated text.

Do the censuses always have the columns in the same alphabetical order (i.e. does B always come straight after A, does does Z come straight after Y?  If not, then the transcriber may want to move the columns to reflect the pattern in the original, and end up with A B M N C F X Y Z D ... etc (flexible CSV can cope with this).  IF so, then one of the top rows should be the letters, because transcribers are familiar with them.

Wrapping is good.

**Comment by geoffj-FUG** [comment]
Pat
No, the transcriber is not to move the columns. It crashes the checking software. The order we use at the moment is the order the data appears in the census. 

We need to tread carefully for 1911 because the forms are different. They were not summarised, they are the original document completed by the householder.

The A, B etc are the column designations on the spreadsheet. They are not entered by us. They are part of the cell reference, e.g. A1, G2 etc.

Wrapping is good, but it still wastes screen space for flags. That’s why I suggested hiding a row with the field names in it. That row can be locked so that the transcriber does not see it. That lets us have both field names and shorter headings in the spreadsheet. I am not sure of the impact on Kirk though.

Geoff

**Comment by geoffj-FUG** [comment]
@Rhonda @Susan
It appears that my processes document and flow chart may have gone missing on its way to you.

I have put a copy in Google Docs FreeCEN FreeCEN Processes.

In the Document there are some queries in red. Can you have a look, please and provide feedback.

Geoff

**Comment by rhodamackenzie** [comment]
Thanks for this Geoff, I’m on the front line as a doctor for CoVid so dipping in and out when I can, could I see a copy of the old spreadsheet please? It would make more sense to me then.

**Comment by geoffj-FUG** [comment]
Hi all
I have been looking at the spreadsheet fields needed to cover all years up to 1911. There are a lot of them.

So I believe we have 2 choices:

*	One spreadsheet so that we have uniformity in testing but 2 versions with 19c census version having fields hidden and locked. It would then to all intents and purposes have the same look and feel as the current spreadsheet. The 20c censuses would use the full spreadsheet with the hidden fields unlocked and visible;
*	A forms view so that only those fields applicable to that year are visible.

For transcription I would favour the first option. 

Still working on the detail.

Geoff

**Comment by rhodamackenzie** [comment]
> Hi all I have been looking at the spreadsheet fields needed to cover all years up to 1911. There are a lot of them. So I believe we have 2 choices: * One spreadsheet so that we have uniformity in testing but 2 versions with 19c census version having fields hidden and locked. It would then to all intents and purposes have the same look and feel as the current spreadsheet. The 20c censuses would use the full spreadsheet with the hidden fields unlocked and visible; * A forms view so that only those fields applicable to that year are visible. For transcription I would favour the first option. Still working on the detail. Geoff

I would favour the first option also

**Comment by rhodamackenzie** [comment]
> @rhonda @susan It appears that my processes document and flow chart may have gone missing on its way to you. I have put a copy in Google Docs FreeCEN FreeCEN Processes. In the Document there are some queries in red. Can you have a look, please and provide feedback. Geoff

Geoff - please note my name is Rhoda, not Rhonda, as #Rhonda is attached to another person

Also for the queries in red in "The Process " document, where would you like us to respond to these? In this thread? There are many I cannot answer though.

**Comment by geoffj-FUG** [comment]
Rhoda

 

My apologies. I should have looked at your name closer.

 

Kirk has closed the thread. If the thread doesn’t accept this then reply back direct to me.

 

I will put up a spreadsheet format later today (I am in Australia). I will put it into the FreeCEN processes folder on Google Docs.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Sorry @geoffj-FUG the closing was an error on my part. It is an important story

**Comment by geoffj-FUG** [comment]
@susan  @rhoda 

 

I have added 2 documents to the FreeCEN Processes.

 

One a spreadsheet called Sample England and Wales Spreadsheet FC1. This is the transcription spreadsheet that has been used up to now. It was designed for FC1. It is the sample sent out to new transcribers. It was originally called Censdemo.csv

It is the base document that we will build the new spreadsheet from. It is important to know whether Scotland use exactly the same spreadsheet, or whether they use a different version. If Scotland is different we need to know so that we can get the fields right.

 

The other is called The CSVProc Process Version 2. It is an update of the Process Document that I uploaded yesterday. It is revised to take into account some of the feedback I have received so far. Once again there are queries in red. As these are cleared I will keep updating the document and it will become our bible. We will also have something that can become part of the documentation.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
The BIG question on the revised spreadsheet for input to FR2 is what do we propose? 1) a brand new csv layout with a census logical layout: 2) a layout based on the current CSV layout with augmentations: 3) a layout based on the VLD field layout with augmentations. 4) a flexible CSV layout where the column contain the input for the field **named** in the column header. Before we do too many mockups let's try to nail this down.

The initial layout used for code development was 2) the current CSV layout with augmentations; initially the augmentations were simply 2 for 1901 fields. It was quickly realized that there were additional fields required to create the final database entries. Initially 2 were identified (deleted and ecclesiastical parish) then we saw we needed to add 2 fields for birth county and place as selected or standardized versions in addition to the 2 entered by the transcriber initially which are the verbatim versions (TWYS). Then came the fields of a detail flag and unoccupied notes which may or may not be required. Nor are we sure about the Scottish fields and we need to add 1911 and prepare for 1921.

At the same time we need to bring our existing transcribers along with us and we know that people hate change so I would not recommend option 1). The VLD format in option 3) is not logical from a census perspective and hence would be inadvisable. The approach of tagging on additional fields in 2) could be made to work but is likely to be subject to errors and not easily adaptable or logical if fixed in column order. 

What is needed is a layout that can be adjusted. We need a flexible approach one that can be adjusted as needs change. Hence I am going to argue for the flexible csv approach 4). In this layout the columns are specified by the column header row as has been done in principle for the past 20 years except that we use meaningful names and NOT the spreadsheet column name. I would prefer using the internal field name as the column name but am not wedded to that. The key requirement is that the descriptions are fixed so that they can be linked to the appropriate internal fields. 

If we adopt this approach the transcriber uses only those fields that are appropriate to the census year and country. (The system can validate that the appropriate set has been used at the start)

**Comment by geoffj-FUG** [comment]
I am happy with 4. 

I saw the spreadsheet as an array separated by commas and processed row by row. I had not interpreted it as a set of fields that could be dealt with individually. So I am learning!

I now see the significance of the field names in the spreadsheet columns. 

Let me have another think about that one.

 Geoff

**Comment by FreecenBren** [comment]
I agree with Geoff.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG
You mentioned you had not seen an entry display.
This is the current version
![Entry Display.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cca8769b-1439-4eeb-b07d-124f57f0f74a) 

Just click on the image and it will enlarge.

**Comment by Captainkirkdawson** [comment]
I am sure you and others can suggest improvements.

There are 2 documents you might want to review
An initial document on the upload process is available at.
https://drive.google.com/file/d/1WpEM-1O4A11l6TtQQ7YzsQZ2XvX2WMod/view

and one on the online system
https://drive.google.com/open?id=1IPIx_VTc0NoEUawjckbPgkGzv4Kw1C6t

Please remember these are works in progress.

**Comment by geoffj-FUG** [comment]
Kirk

 

Scotland 1911

 

I don’t have access to Scotlands People so cannot view a real census book. The census records were transcribed into an Enumerators book as in previous years.

The reference was different. The sample page is 1911/739/1 Page 5.

 

There were additional fields:

“There were new questions relating to fertility of marriage:  on duration of marriage;  the number of living children born to each marriage;  and the number alive at the time of the census.

There were changes to several others:

categories for people with disabilities were revised and the introductory section to the third report on the 1911 census refers to the intended use of the terms as:

lunatic - in cases where the infirmity had been acquired during life

imbecile - in extreme cases where the infirmity had existed from birth or an early age

feeble-minded - in milder cases where the infirmity had existed from birth or an early age. 

the question on occupation was extended to find out which industries or services a worker was connected to in addition to their personal profession or occupation

the question on place of birth was extended to include nationality for those born in a foreign country, that is, outwith British territory, colonies and dependencies. “

(Source: nrscotland)

 

So the complete set of fields on the census page, but not the fly to the ED, are:

 

Civil Parish and Parish Ward

Ecclesiastical Parish

School Board District

Burgh Ward of

Parliamentary Constituency

Municipal Burgh

 

Address Number

Street

Unoccupied or Building in Progress

Number of rooms with one or more windows

Name and Surname

Number of Persons I Household

Relationship to Head

Age in Male or Female column

Gaelic or G & E

Years married

Whether married, single or widowed.  There are also numbers in this column in the sample image. What are they for?

Years married

Children living

Children deceased

Profession or Occupation

Industry

Employer, Worker, Own Account

If working from home

Birthplace

Nationality if born in a Foreign Country

Disability (limited number of Codes)

 

This is different to the England and Wales census and may explain some of our spare fields.

 

I am going to try and find someone with access to Scotlands People who may be able to advise me on the full ED formats.

 

Geoff

**Comment by FreecenBren** [comment]
Not sure where it fits in but they can also include the wife’s Maiden name
but not sure which Census Year.

Margaret will help there.
Brenda

**Comment by rhodamackenzie** [comment]
[ScotlandsPeople_C1911.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4426780/ScotlandsPeople_C1911.pdf)
here is a scotlands people 1911 census page

**Comment by rhodamackenzie** [comment]
IF excel is being used for the transcribers, the headers can be aligned at any angle to save text wrapping 

<img width="223" alt="excel header alignment" src="https://user-images.githubusercontent.com/62574522/78355292-60a98f00-75a5-11ea-985f-2cc9dbf0e120.png">

**Comment by FreecenBren** [comment]
At the moment Excel is used by the majority, but I have lots who use Mac and Open Office just to name two.
Some have Excel on their Mac but not many. We have those as well who dislike Excel for some reason.
Not sure if that is useful or not!

**Comment by PatReynolds** [comment]
Happy with 4!

**Comment by rhodamackenzie** [comment]
Sorry folks, I haven’t had an notifications for 10 days! Here I am again, Geoff, in reply to your list of Scotland census 1911, There are the fields:

Civil Parish and Parish Ward

Ecclesiastical Parish or Quoad Sacra Parish

School Board District

Parliamentary Burgh
Parliamentary Constituency
Municipal Burgh
Burgh Ward
Special Water District
Special Drainage District
Special Scavenging district
Special Lighting District
Island
Number of Schedule
Road, street, &c., and No. or name of House
Houses Inhabited
Unoccupied or Building in Progress
Number of rooms with one or more windows
Name and Surname
Number of Persons in House
Relation to Head of family
Age in Male or Female column
Gaelic or Gaelic and English
Whether married, single or widowed.
Duration of marriage
Children born alive
Children still living
Personal Occupation
Industry
Employer, Worker, Own Account
If working from home
Birthplace
Nationality if born in a Foreign Country
Disability (Codes 1,2,3,4)

**Comment by geoffj-FUG** [comment]
Rhoda has provided a list of fields in the 1911 Scotland census. I have matched them to our list of fields so far:

 

Scotland census 1911 

 


Field

Do we have it?


Civil Parish 

Yes


Parish Ward

Yes


Ecclesiastical Parish or Quoad Sacra Parish

Yes


School Board District 

Yes


Parliamentary Burgh 

No


Parliamentary Constituency 

Yes


Municipal Burgh 

Census place?


Burgh Ward 

Is this exclusive i.e. Does only one Ward ever occur? If so we have it covered.


Special Water District 

We have Sanitary District only


Special Drainage District 

We have Sanitary District only


Special Scavenging district 

We have Sanitary District only


Special Lighting District 

We have Sanitary District only


Island 

Is this Census Place?


Number of Schedule 

Yes


Road, street, &c., and No. or name of House 

Yes


Houses Inhabited 

Uninhabited


Unoccupied or Building in Progress 

Yes


Number of rooms with one or more windows 

Yes


Name and Surname 

Yes


Number of Persons in House 

No but it can be counted from the family members. It sounds like a checksum?


Relation to Head of family 

Yes


Age in Male or Female column 

Yes


Gaelic or Gaelic and English 

Language


Whether married, single or widowed. 

Yes


Duration of marriage 

Yes


Children born alive 

Yes


Children still living 

Yes


Personal Occupation 

Yes


Industry 

Yes


Employer, Worker, Own Account 

Yes


If working from home 

Yes


Birthplace 

Yes


Nationality if born in a Foreign Country 

Yes


Disability (Codes 1,2,3,4) 

Yes

 

Geoff
