### ISSUE TITLE
Do we add the International Chapman Codes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#846]
@geoffj-FUG wrote

Do we introduce International Chapman Codes for overseas births? 1901 onwards. Too difficult in 19C.

**Comment by PatReynolds** [comment]
IRL is used for Irish POBs but results just have a blank, neither Ireland nor Armagh (etc.)
SCT is use for Scottish POBs but results just have a blank, neither Scotland nor Inverness (etc).
OVB is used for Oversea POB in the British Empire (etc.) and results show 'Overseas British'
UNK is used for Unknown but results just have a blank.
If you search for County Armagh, the results show Co Armagh.
OVB and OVF work as expected.

Suggested stories:
1/ Make IRL, SCT and UNK visible in results as Ireland, Scotland and Unknown OR, if a county is known for IRL or SCT, the county (possibly with country too?
2/ story #498 - specify place of birth ordering 
3/ use machine learning to identify the country in OVB and OVF places to permit serching by specific country. = story #648

**Comment by geoffj-FUG** [comment]
Pat

 

Oops – I have posted into the wrong #. Can you move it please? I am not sure how.

 

Geoff

**Comment by PatReynolds** [comment]
Geoff notes:
Geoff notes:
Pat, 
Kirk and I are working on the Place Names issues at the moment. It is going to take a while but we believe that we can come up with a workable solution.
We have established a Place of Birth protocol in the manual of Bigger to Smaller. So Bathpool Nr Taunton would be transcribed as is and then SOM Taunton Bathpool would be entered in the suggested place of birth fields in the spreadsheet by the transcriber.
In the master place names file you will find Bathpool as originally created from the Gazetteer. The validator will enter Taunton Bathpool into the alternative place field  in the master file and in the future all transcriptions containg Taunton Bathpool will pass validation. 
To take that further we could include international codes under OVF or OVB. 
Lets take we have a place such as Calcutta Bengal. We would transcribe it as Bengal Calcutta (larger to smaller). We would ensure that it exists (it did and it does), add it to the database as OVB Bengal Calcutta (it was a British Colony at the time), add the lat/long and whenever it crops up in the future the system will accept it. We would also add alternatives such as East Indies Calcutta (larger to smaller) so that it is validated in those cases too.
Geoff

**Comment by PatReynolds** [comment]
UNK is a different story to SCT and IRL

Pat to make new stories for /3 too.

OVB and OVF and other special codes tpo be validated, no need to validate 'India' or 'France' at the moment - Pat to make part of /3 above.

**Comment by PatReynolds** [comment]
#926 written to ensure UNK appears as Unknown in results and #937 to ensure that ENG, IRL, SCT and WLS appear.

**Comment by PatReynolds** [comment]
Irish birth counties now appearing in results - e.g. ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/6ecec88a-7f33-490a-8bad-aba44592aee9) 
No other stories needed, so I think this one can be closed.

**Comment by richpomfret** [comment]
Closing.
