### ISSUE TITLE
Explain 'syndicate' and 'county' in documentation

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#847]
Need to remove ''syndicate' from 'syndicate coordinator' Also need to remove 'county' from 'county coordinator'. Other mention of 'syndicate' or 'syndicates' needs replacing with 'county team' or teams, as appropriate.

a task for a member of the documentation team

Syndicate is peole , county is data

**Comment by PatReynolds** [comment]
Hi @colin1959  is this something you could help with - we've decided to drop the distinction between 'county coordinator' and 'syndicate coordinator' - could you go through help for Transcribers and make the changes in this story (on test3)?

**Comment by colin1959** [comment]
Hello Pat

I'm sure I can give this a go, it's all a learning curve.
Where do Iocate Help for Transcribers?
Colin Mincher
 

    On Tuesday, 21 April 2020, 11:16:31 BST, PatReynolds <notifications@github.com> wrote:  
 
 


Hi @colin1959 is this something you could help with - we've decided to drop the distinction between 'county coordinator' and 'syndicate coordinator' - could you go through help for Transcribers and make the changes in this story (on test3)?

**Comment by colin1959** [comment]
This page contains general information and advice about being a transcriber. It is basic information, to get you started.
Syndicates and Counties
You will be assigned a Coordinator (C) who will deal with you as a person. Your Coordinator will answer questions, monitor your work, and upgrade your skill level as you begin to work with the more difficult census images: your Coordinator is your mentor.
Your Coordinator will be the Coordinator (C) of the County and Census Year for which you initially choose to transcribe. As a Coordinator, they manage the data available for transcribing as well as other technical aspects relating to their county and census years. You will need to contact the relevant Coordinator when you need more work.
Image Server
We will be setting up an automated system for allocating images for transcription, linked to an Image Server. In the meantime, the CC will arrange to send you images to transcribe — the method varies from CC to CC.
Working for more than one county
When you first begin to transcribe for FreeCEN, your Syndicate and County Coordinators will be the same person. If you want to work for a different county, you simply remain with the same Syndicate, but contact the new County Coordinator for work. Each CC can see all your work for their county and census years, no matter which Syndicate you belong to. Your Syndicate Coordinator can see your work for all counties and all census years.

**Comment by colin1959** [comment]
Syndicates and Counties
You will be assigned a Syndicate Coordinator (SC) who will deal with you as a person. Your SC will answer questions, monitor your work, and upgrade your skill level as you begin to work with the more difficult census images: your SC is your mentor.
Your SC will be the County Coordinator (CC) of the County and Census Year for which you initially choose to transcribe. As a CC, they manage the data available for transcribing as well as other technical aspects relating to their county and census years. You will need to contact the relevant CC when you need more work.
Image Server
We will be setting up an automated system for allocating images for transcription, linked to an Image Server. In the meantime, the CC will arrange to send you images to transcribe — the method varies from CC to CC.
Working for more than one county
When you first begin to transcribe for FreeCEN, your Syndicate and County Coordinators will be the same person. If you want to work for a different county, you simply remain with the same Syndicate, but contact the new County Coordinator for work. Each CC can see all your work for their county and census years, no matter which Syndicate you belong to. Your Syndicate Coordinator can see your work for all counties and all census years. 

The database
You need to be familiar with the terms we use to describe the FreeCEN database and how these relate to the transcription files you create. The database itself is simply an organised set of information held on the servers that make FreeCEN work. (You could think of the database as the digital equivalent of a multi-storey building, its rooms filled with filing cabinets that contain transcribed census returns.)
FreeCEN has a single database which is organised by Census Year, County, Piece number, and Civil Parish. We use the same Piece numbers as the National Archives.
You’ll be using Images of a census — the pages of an Enumerator’s book — as your source, transcribing the data (information) it contains into a spreadsheet. You can use any spreadsheet program (or app) that you have on your computer.
When you have finished, your transcription is then checked by a Proofreader — an experienced Transcriber.
The final checks are done by a Validator who is often the CC. Next, your file is uploaded to the FreeCEN Database on the original FreeCEN site (FreeCEN1): the database there is updated once every four weeks. Finally, your file is copied to the database on this new FreeCEN site (FreeCEN2).
Once in the database, all the records you transcribed will be available to be found by a Search.

Transcriber Actions
If you are not logged in, select Members on the Main menu (at the top of every page). Log in using your UserID (or email address) and Password. You can avoid the need to type these every time by checking the Keep me logged in box and allowing your browser to save passwords. (Every few months, you will be asked to confirm your current email address — this is to help ensure that we send important messages to the correct address.)
Once logged in, you will see some information about the system status: this is for all members, not only the technical team! You will also see a set of buttons: these are your Actions — a set of online tools for managing your Profile (see next item) and more.
Profile is your details. Please make sure that these are kept up-to-date by selecting Edit. The coloured fields are those that you can edit. Your telephone number is not essential but it is useful if we find that we cannot contact you by email: it is not made public. Alternatively or additionally, please let us have your postal address. It is helpful to have at least your country, so that we can keep time differences in mind when contacting you.
Roadmap takes you to a page detailing how we plan to develop FreeCEN2 over time, with new features and enhancements for Transcribers, Coordinators and Researchers. We welcome feedback on the Roadmap, and comments on how FreeCEN2 is developing.
Once you have selected an Action, you will notice that there is a row of breadcrumbs (links) just under the main menu that guides you back to previously-visited pages. It is a good idea to use the breadcrumb links, rather than your browser's Back button — especially if you have made any edits online. If you do use the Back button, then please reload the page (Ctrl+R on Windows, Cmd+R on a Mac) before you click on any further links.

Problems logging in?
If your UserID is reported as incorrect: 
Remember that it is case-sensitive: SuperUser is not the same as superuser, for example.
If you can’t get your UserID accepted, try using your email address instead. Once you are logged in, check the details of your UserID in your Profile.
Use the password reset request link to reset your password if necessary. Please note that the activation email sent to you is only valid for 24 hours — if you miss this, you will need to request a reset again.
If neither UserID or email address is working for you, contact your Syndicate Coordinator. Please help them by explaining what you have already tried.
If you get no message, then either your Profile is marked as Inactive or you are using the wrong password. Ask your SC to check your Profile and mark you as active.
Problem with password reset request?
If you have requested a password reset, but have not received the email, then please ask your SC to make the request for you.

Sending messages
To avoid overloading us with messages, please follow these guidelines
If your message is about improvements to the system, please look at the Roadmap to see if we already have it on the to-do list. If it is not there and: 
If the improvement is for version 1.3 (improvements for transcribers), please tell us your idea via the Contact page, with full details of what is needed.
If the message is about an improvement for researchers (version 1.4), please use the feedback form, which will open in a new tab. 
If the message is about a bug or system failure, ask your Syndicate Coordinator (SC) to trouble-shoot for you. If they can't help, please use the Report a Problem button at the bottom right of all screens (when you are logged in).
All queries about data need to go to the relevant CC: use the Contact page, selecting Data Question on that form.
Everything else needing a response should go to our Contacts Coordinator: go to the Contact page and select the appropriate category (type) on that form. Please remember to include your UserID and as many details as possible: having to get back to you to ask for them takes us time.

**Comment by colin1959** [comment]
#847 

- [x] read & review document 'help for transcribers'.

- [x] copy & paste to google docs.

- [x] amend document & save.

- [x] review & raise any issues.

- [x] create link & post to Github.

- [ ] Close issue.

**Comment by colin1959** [comment]
https://docs.google.com/document/d/1fZuNH9RxQY_ws7883TQdvyJ18M9opyj0EyinFBvbw2E/edit?usp=sharing

info, link to 'Help for Transcribers'

**Comment by colin1959** [comment]
Document update ' Info Transcribers' now on refinery cms.

Colin

**Comment by AlOneill** [comment]
@colin1959 I don't know what you have been told about working on Refinery and how we use this board, but I think it is too soon to be closing — the issue itself is not complete, even if your part in the update is done.

Updated pages need to reviewed for content and then the HTML markup needs to be checked.

So am re-opening and returning to "In progress".

**Comment by colin1959** [comment]
Thanks for highlighting, it's a matter of learning by your mistakes I think.I made a comment and closed by mistake instead of just a comment. Regards😷 
Colin Mincher
    On Friday, 15 May 2020, 20:40:38 BST, AlOneill <notifications@github.com> wrote:  
 
 


@colin1959 I don't know what you have been told about working on Refinery and how we use this board, but I think it is too soon to be closing — the issue itself is not complete, even if your part in the update is done.

Updated pages need to reviewed for content and then the HTML markup needs to be checked.

So am re-opening and returning to "In progress".

**Comment by PatReynolds** [comment]
@Captainkirkdawson is there a plan to relabel  the buttons so that they do not use the word 'syndicate' either, and county coordinator is just 'coordinator'?

**Comment by Captainkirkdawson** [comment]
@PatReynolds Not at this time. It is important to remember that there are 2 distinct roles Manage the data and Manage the People regardless of who does what.

**Comment by PatReynolds** [comment]
Two distinct roles now documented.

@PatReynolds to consider
(a) clarity of button labels
(b) where/what else needs changing

**Comment by PatReynolds** [comment]
Suggest button title  'County Coordinator' is replaced by 'County Information'  (Systemwide?)
'Syndicate coordinators'  needs Transcriber Agreement removing (Systemwide issue). Just a duplicate of 'county coordinator'?  

Suggest removing Transcriber Agreement accepted from 'Country Coordinator'  (Systemwide)

'Manage Counties' seems to be CSV proc information for all volunteers - suggest combining with Roadmap Button contents and retitling 'Changes to FreeCEN' or something covering both Releases and Roadmap (which is probably too long as a button title).

'Manage FreeCEN Coverage' seems not to allow you to change the coverage ... rather it is about downloading CSV files ??? Change to 'Manage your County'?

'Manage Syndicates' doesn't work on FreeCEN or FreeREG - what if any functionality needs to be here?

**Comment by Captainkirkdawson** [comment]
@PatReynolds 
Please remember that county coordinators, country coordinators and syndicate coordinators are restricted to senior managers only. The term coordinator was used to distinguish from the Manage Counties, Manage Syndicates actions.

If the Transcriber Agreement action is to be removed from either of the county/syndicate management actions it should be removed from the county coordinator. Since the action deals with people.

'Manage Counties' is only there for county coordinators and more senior roles its how they manage their county using CSVProc; so not not understand suggestion of combining with Roadmap

'Manage FreeCEN Coverage' is only for senior roles and was added as means of getting access to the coverage. In reality it duplicates what is behind the CEN1 implementation under CEN2. It is there for developing a future capability. 

The 'Manage Syndicates' doesn't work on FreeCEN or FreeREG - what if any functionality needs to be here?. You are correct it does not work for the Executive Director or Project Manager roles on either. It does now on test2 cen note test2. I had neglected to give you a slection list.

**Comment by PatReynolds** [comment]
Pat to look on Test2

**Comment by geoffj-FUG** [comment]
Clarification included in Dec 2020 version of FreeCEN Full Handbook. Will be available on cutover.
Geoff

**Comment by PatReynolds** [comment]
Buttons now all fine.

Information for County Coordinators now needs revision in light of changes (new story made - #1054)
Information for Transcribers is now updated (story #126)
Access to information about transcription agreement status needs discussion (story #1055)
Purpose of Manage FreeCEN Coverage Action unclear (story #1056).
Otherwise complete.

**Comment by geoffj-FUG** [comment]
This is now covered in the Handbook.

Geoff
