### ISSUE TITLE
Ability to download a validated file (vld) from CEN2 in CSV

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#851]
Should we be able to download as csv as well as dat?

**Comment by richpomfret** [comment]
@geoffj-FUG what do you think?

**Comment by Captainkirkdawson** [comment]
Geoff wrote
Definitely.
We need to phase out the old tools including FCTools.
FCTools was used to convert vld files to csv files and back again. Why? Because we get queries and reports of problems.
I know we can edit a file online, but there is sometimes a need to edit it offline. Just this week we had a report of a missing entry in a family on FreeCEN. I have to convert the vld file, add an extra person to the spreadsheet and then convert it back. It is now waiting for Brenda to reload at the next update.

So if a file that has been uploaded as a vld can be downloaded as a csv then the Coordinator has control over queries. It can be reloaded in Traditional FreeCEN format via CSVProc.

**Comment by PatReynolds** [comment]
Changed the story from 'download a vld file' to 'download a validated CSV in light of abocve discussion.  Leaving the 'high priority' flag on as I need to understand the priority of this.

**Comment by geoffj-FUG** [comment]
Pat

 This should be done once the validation, PARMS editing and publication steps have been created. (i.e. CSVProc is in a position to be implemented).

 Validation is happening at the moment. We cant go live until the other 2 steps are in place.

 We will then have a number of Actions to prioritise including but probably not limited to Downloading vld files, Scotland and Ireland. 

 The downloading of vld files can continue with the old software as long as uploading the amended files via FreeCEN1 is available. The new method has to be developed prior to FreeCEN1 uploads ceasing.

 I presume that these priorities will be subject to executive guidance. 

 Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  Your urgent review and comment is required.
I have started looking at this story and have a number of questions. I assume that the purpose of the download is to reprocess through CSVProc hence the output must be processable by CSVProc.
0) There is no field header so I would propose to use the year census spreadsheet.
1) How should we structure the CSV file in terms of how entries were originally structured?
Specifically; the original transcription entries were based on propagation. ie. the enumeration_district	civil_parish	ecclesiastical_parish	where_census_taken	ward	parliamentary_constituency	sanitary_district	location_flag	folio_number	page_number	schedule_number	uninhabited_flag	house_number	house_or_street_name	address_flag fields **were only entered when they changed** hence most of those fields were blank and the systems promulgated the values. 
I am unclear if the original vld file had the fields promulgated during the validation process or if it was done by the processing software for cen1 or cen2. Clearly in cen2 the vld entries of most fields are populated
![vld entries.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/adca8041-1b02-4147-8a1b-125773f74ee1)
![vld entries 1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/065ab76b-255e-40eb-8bd3-32e057b7a86e)
Should the vld_csv_downloader include all fields of should it depopulate and replicate the original transcription structure? Unsure of the impact on the CSVProc of having all the fields populated.
2) I notice all the flag fields are populated with the hyphen. Is that done by the validation software? I assume that should be turned into blanks as CSVProc expects only xX or blank
3) The deleted_flag field is either true or blank; **this has identified a serious issue with CSVProc** while we include the deleted_flag as a field and display that in the flags section. There is NO ability to create it; nor is there any use of it in displays for the researcher; nor is the field written out on a download of a file; nor is there any mention of the field in the handbook
4) there is a separate field for unoccupied notes. There is no such field in CSVProc. We use the standard notes field for such information. I would propose to concatenate anything in that field into the notes field
5) the age has 2 fields  a number and a unit. CSVProc only expects one field so propose to concatenate
6) This is a validated file hence one would expect the record valid field to be included as well as the deleted_flag. 
7) CSVProc does not accept the record valid or deleted flag UNTIL a file is in the validation phase. We do noot want to have to strip field to load set the validation flag and then reload with the validation fields; so likely need to have a means of saying this file should be uploaded and shown as in validation

**Comment by geoffj-FUG** [comment]
Kirk

 

Answers in red below

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
There are no comments red or otherwise.
There was also a copy of a contact request you had received.
So have not any feedback

**Comment by geoffj-FUG** [comment]
Reply sent off board

**Comment by Captainkirkdawson** [comment]
The code to generate a CSV file has been developed and is available for evaluation on test3
In a county select the Manage VLD Files option
![vld files.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b5415391-6e76-4834-9e8e-0593ec09294e)
On the listing of files select the show for one you wish to access
![listing.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/a053fedd-b506-401a-ac2c-71f01badc0c6)
On the heading of the file you can either look at the entries or Download as a CSV file
![download.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/f30e9dae-7cec-43b8-b558-46cc2133061d)
The csv file will be downloaded onto your computer
Available to county coordinator, master county coordinator data manager and system_administrator
The file can then be uploaded into CSVProc.
At this time the upload into CSVProc SHOULD ONLY be done on test3.
I suggest that a number of files be downloaded and uploaded to evaluate both the downloader and also CSVProc

**Comment by geoffj-FUG** [comment]
Kirk

 

Catching up on a backlog of emails.

 

I have just flagged this one to do in the next couple of days.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk
I have downloaded the vld file OK and opened it as a .csv fle.
If the piece is a vld file and is being downloaded then it has been validated. The .csv is not a validated .csv as there is no validation column.
The purpose of downloading a vld file may be as simple as correcting an ecclesiastical parish by one letter. We do not want to revalidate the whole thing.
I downloaded RG121918.vld It is not in my file list so I uploaded (not replaced) it. That worked OK. However I have 83 Error messages and 1883 Warnings. Why - because the data integrity rules have been tightened slightly plus 2 Warning generated for every Alternative POB.
Now I will go back to my comment above. If the validation column is there and set to true these items will not report. That is not quite acceptable either.
Question - when we download a vld file can it also be saved into the downloaders file list? That will presumably automatically produce the report. 
Next Question - When that report is produced can it be Errors only (not warnings). - I.e. Errors turn the flag to false. Warnings leave the flag as true.  
That will require the file to be tidied up but the warnings that have already been accepted in Valdrev to be as they are, and validation not repeated.
Incidentally one of the Errors is a blank line. In CSVProc we report it as an Error. In Valdrev it was ignored and obviously gets uploaded into the database. (Story #616 )
Geoff

**Comment by PatReynolds** [comment]
Deployed, but not tested. @geoffj-FUG could test

**Comment by geoffj-FUG** [comment]
Pat
See my comment from 22 December.
So far I have been able to download a vld file as a csv file OK in test.
But I cannot reload it, The .csv file has no validated column. It therefore needs revalidation.
The downloaded .csv file needs an additional column added and set to True for all records to show that the record is validated. Otherwise the complete piece has to be revalidated from scratch.
We do need a test to make sure that there are no Errors in the file. It should be the errors/warnings report without the Warnings. All Warnings should still have their Validated flag as True but Errors should be set to False.
That way the file cannot be reloaded until Errors have been removed.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
The file can be uploaded as downloaded. Yes it will produce all of the errors and warnings.
If we add the record valid field then it will not upload because it is a new file and therefore not being validated. 
There is no way of distinguishing a downloaded vld file from any other file. 
In fact if it has errors, and all I have tested to date do have errors, it cannot be in validation by definition.
So we are in somewhat of a catch 22.
There is one solution that is we add a bulk validation option. At that point a Previously Validated actions becomes available. This sets all records to true. The only downside I see is a coordinator could do this on every file even if it was a prior VLD file if they so wished but we have to assume they are sensible. 

On the matter of the blank lines in a vld file we could "ignore them" so they do not appear in the download. 
We should continue to error report the blank line in an uploaded file so that it is eliminated.

**Comment by geoffj-FUG** [comment]
Kirk
Have a look at Notes. They have been duplicated.
I have examined all the errors in detail:
Query - Is the report being generated before or after the fields have been prefilled? They are prefilled but reporting as Errors.

Have a look at Row 5429 et seq, These haven't sorted out the repetition when converted.

Row 5519 error is due to a change in rules. We do not pass the y after 999. It looks as if FC1 recorded it as 999y. We could just change the test to pass it.

The occupation categories are still concatenated with the occupation. I presume we cant do anything about that.

I was wondering why we had validated a file with so many missing 0 schedule numbers against unoccupied flag u etc. Row 5783 tells us. The programme sees the following 0 as part if the same schedule. We need an if u, b, v do not remove schedule number. That raises the issue of 1841. We cannot use the schedule number to show a transition because every one of them is 0. We need to use the change in household number to identify the transition.

Rows 6707 to 6709. I looked for hidden entries in the ED section but none were apparent. Not sure why these were reported.

Found a bug in testing page number results. I will create a story for that. (Story #1103)

I have changed all teh WAL to WLS!

I have corrected the file on my computer but not reloaded it. 

I have a workaround to reach incorporation. We need to sort out the above before I try it.

Geoff

**Comment by Captainkirkdawson** [comment]
What file was this? It does not look like HO107_1924 on test3 which is the one I thought we had been talking about. None of the numbers above relate to that file eg you report there is an error with line 5519 but I cannot see one 
![5519e.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/095e5818-4134-43df-bce1-5aecc9be98dc)
nor a warning
![5519.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/52eb801c-605e-455d-a320-78faeef20526)

**Comment by geoffj-FUG** [comment]
RG12_1918

**Comment by Captainkirkdawson** [comment]
Put on hold until Geoff has more time

**Comment by geoffj-FUG** [comment]
Kirk
RG12_1918
I will send you the report and the converted file.
Geoff

**Comment by Captainkirkdawson** [comment]
Thanks Geoff.

It is important that we have a common understand of the vld download to csv.

VLD files contain FULLY populated vld entries. i.e. the VLD software does the propagation.

Since CSVProc expects an unpropagated file the download DEPROPAGATES  the vld file

Do not understand the comment on Notes do not see any duplication . Yes there are note fields with the same content but for different records so that seems appropriate to me

Story raised It looks as if FC1 recorded it as 999y. We could just change the test to pass it.#1148

Story raised Decouple the occupation categories from the occupation on VLD download#1149

Story raided Investigate RG121918.vld download lines Row 5429 et seq#1150

Story Merchant Vessel Page Numbers #1103 still active

Raised story False? uninhabited_flag of x#1152 as response to **Rows 6707 to 6709. I looked for hidden entries in the ED section but none were apparent. Not sure why these were reported.**

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG New version applied to test3; all known issues addressed
