### ISSUE TITLE
Entry display to show only fields appropriate to that country and year for 1901 and 1911

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#864]

**Comment by Captainkirkdawson** [comment]
Display is modified to be selective.
Deployed to test3

**Comment by PatReynolds** [comment]
@rhodamackenzie to test Scotland @PatReynolds to test others.

**Comment by rhodamackenzie** [comment]
I have tested this and all appears to be well

**Comment by PatReynolds** [comment]
Searched for surname Alcock, born 1700 to 1800 census counties Lincolnshire and Nottinghamshire, 
1841 and 1841 - House number showing, but no records have anything in this field (is this an unwanted field, or just unlucky sample)?

Searching for Alcock in Aberdeen:
Scholar field is not appearing in 1861 or 1871 (Scholar is noted in the Occupation field).

Have not tested for language.

Could not test 1901 or 1911 as could not get a search result.


Otherwise, all good to 1891.

**Comment by PatReynolds** [comment]
Tried a search for Smith born 1800 to 1901 on the 1901 and 1911 censuses.  results - nothing found.

Are there any records to be found?

**Comment by Captainkirkdawson** [comment]
There are no records for 1901/1911 yet loaded into the database
