### ISSUE TITLE
Enable name variants in the Parms files to be accomodated in the drop down lists through a lookup

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#878]
Geoff wrote: Geoff: Discussion has been held about reporting and picking up a list from the PARMS to provide a Civil Parish filter. What will happen with the 2 PARMS formats for different years is that Walton in Gordano, for instance, will come up twice in the dropdown list, firstly as “Walton in Gordano” and then as the abbreviated “Waltonin Gordano”.

@geoffj-FUG please could you provide a link to this discussion

E2 U3 S4 C?

For discussion: solution  could be only the PARMS2 version will be shown, in the dropdown list, but both versions will be searched when the  PARMS2 version is selected.
Or solution could be that the PARMS1 versions are replaced by PARMS2 versions (rake task?)

**Comment by PatReynolds** [comment]
@PatReynolds  to do some thinking

**Comment by PatReynolds** [comment]
@geoffj-FUG has a solution been found, or do I still need to do some thinking?

**Comment by Captainkirkdawson** [comment]
No solution determined at this time. 
To some degree this is not urgent for implementation; it will become so when we want to move vld files and reduce the work load on the person doing the conversion.

**Comment by PatReynolds** [comment]
Can this now be closed?

**Comment by geoffj-FUG** [comment]
This is not a problem with files initially validated in FC2 - the POBs will conform to the Gazetteer.
However ther are a huge number of POBs in vld files (and some csv files where they have been converted from vld files) that were validated in FC1. If we want to allow people to search on Place of Birth (as opposed to District, Piece, Civil Parish) all the existing files initially validated in FC1 will need to be standardised. This will also be so if we want to search around a Palce,because the POBs with  abbreviated place names will not appear in the Gazetteer and will therefore not have coordinates.
Geoff

**Comment by Captainkirkdawson** [comment]
@PatReynolds needs to stay open

**Comment by Captainkirkdawson** [comment]
This is resolved by the use of Freecen2 Place  for pieces and Freecen2 Pieces
