### ISSUE TITLE
Coords can download a piece (or part of a piece)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#90]
Dependent on #85

**Comment by PatReynolds** [comment]
@geoffj-FUG this needs to be tested, too.

**Comment by geoffj-FUG** [comment]
Pat
Thats fine. 
The first step is to test the transcriptions for each year. That is where mot problems will crop up. 
We have put an 1881 piece through and highlighted an number of things to look at. We can now try to download that one when we are ready. I have an 1901 piece being transcribed from scratch. We will need to create populated test spreadsheets for each year. Once we get the transcription right the Proofread piece will naturally follow because they are the same spreadsheets. We then need to validate pieces and publish them on test3. Once that is all done we should be able to download all 4 versions of each spreadsheet and check version control.
Geoff

**Comment by PatReynolds** [comment]
@Captainkirkdawson can you confirm that testing is also needed on CSV spreadsheets which are already transcribed and on FreeCEN1 and FreeCEN2 ?

**Comment by Captainkirkdawson** [comment]
There are no csv files which are already transcribed and on CEN1/2. ie we can only download csv files that have been uploaded to CEN2. To upload to CEN2 there are additional fields that must appear that have been added by the proofreader/validator. These must  appear as header fields as well as records.

Now we could

**Comment by Captainkirkdawson** [comment]
There is no apparent need for a download
Geoff has said in the main epic
There is no need for a download as far as I can see. 
Suggest this be closed
