### ISSUE TITLE
Find better terms than "Next Dwelling" and "Previous Dwelling"

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#909]
These buttons (on a Search Detail page) do not necessarily link to an inhabited/habitable place, i.e. to the next or previous household group, in our census transcript: the "next dwelling" could be church, a business, a factory, etc., or a building under construction or vacant accommodation, etc. Dwelling implies a place that is (or could be) lived in.

The word dwelling as a concrete noun (as a physical thing), sounds formal and old-fashioned. It will be even less familiar to a non-native speaker of English. The word is currently used more often in one of its abstract senses: "I've got better things to do than dwell on a pipe-dream.", for example.

Would **Entry** be a better word? The `title` tag for a button could be "Household or building" (not accessible to all, but …). And we would explain what we mean by "Entry" in the Help.

Are there other words we should consider?

**Comment by Captainkirkdawson** [comment]
I fail to see the need for change; cen1 used "Household" for 20 years. Why cen2 uses Dwelling is beyond my knowledge base. Both are wrong and Entry is even worse as an entry can mean an entry in a vast number of collections.

**Comment by geoffj-FUG** [comment]
If we want to be pedantic it is next schedule and previous schedule.
Next schedule and previous schedule means absolutely nothing to a lay researcher, and our audience is lay researchers. We have always used next Household and Previous Household.
'The man (on his ipad) on the Clapham bus' would recognise next Household. If it turned out to be a Church he would say, "Oh look they lived next to the Church" and would look on a map to see where the Church was. He would then move on and would have understood exactly what the history was.
The fact that we are trying to identify a term that replaces Household to accommodate the Church (or factory, or unoccupied house etc.) appears to be an exercise in pedagogy.
In my opinion this story is destined to sit here for the next ten years with no resolution.
Geoff

**Comment by FreecenBren** [comment]
Well said Geoff, I agree with you 100%..

If it has already worked for 22 years then do not change it.

Brenda

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG so do we assume that you and @FreecenBren are suggesting that the current names that Freecen2 uses i.e. "Next Dwelling" and "Previous Dwelling" should be changed to "Next Household" and "Previous Household"?

**Comment by geoffj-FUG** [comment]
Kirk

 

I am happy with next Dwelling. It is as useful as next Household. It is understood by the end user.

 

Yesterday you suggested that we should prioritise the work that we still have to do. So, I was looking through Zenboard to see what was there. I came across this story.

 

My view is that it adds nothing to the usefulness of the system and should be closed.

 

Geoff

**Comment by FreecenBren** [comment]
What I was agreeing to was what  Geoff said.

 Why was it changed to Dwellings and not left as Household as per FC1 which
works fine.

**Comment by Captainkirkdawson** [comment]
@FreecenBren don't ask me. Well before my time. It has always been Dwellings on FreeCEN2 since its implementation in 2017

**Comment by geoffj-FUG** [comment]
Kirk

 

The cost in time of changing it far exceeds any benefit.

 

Geoff
