### ISSUE TITLE
Records changed on-line will not be overwritten by a file reload

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#91]

**Comment by FreecenBren** [comment]
Please add for discussion.

We will still need to be able to replace a PIECE online if an error has been reported with the Transcription and we have amended the VLD.

Currently I send these to Lemon on a 4 weekly basis stating that they are amendments so that he can replace it with the one already online.

This could be arranged to be done at COORD level as we used to be able to!

**Comment by richpomfret** [comment]
Requirement for new system.

**Comment by richpomfret** [comment]
@Captainkirkdawson to take a look and explore the required specification here.

**Comment by Captainkirkdawson** [comment]
This is easily done through a file  or piece of similar lock.

However the first set in moving forward with any of these actions is the assembly of a small team of coordinators/ coordinators/ transcribers who will drive forward the migration of Cen2 into a direct build system. No actions should be programmed until such a team exists to verify and validate the approaches.

**Comment by Captainkirkdawson** [comment]
The locking system is in place on test3
