### ISSUE TITLE
Need to add Special Chapman Codes to Freecen2 Places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#929]
Currently we only carry UK Chapman Codes in Freecen2 Places (Since it was based on REG requirement). CEN requires the special chapman codes

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG commented
If no entry is enumerated or the enumerator has written Unknown we make the Chapman Code UNK and enter a hyphen (as above). If you want a place name it can be simply Unknown. The only time we will ever use UNK in the place names file is for UNK – so it does not need to be able to be selected to update the file.

**Comment by geoffj-FUG** [comment]
Kirk

 

We could of course just code UNK – as always valid and move on. If it has been entered because of a problem then there should be a flag to bring it up in validation. 

 

The same goes for any valid Chapman Code with -. It is the flag that should cause it to need a Warning and that will be there.

 

The fact that we put a Warning on Notes catches the rare missing flag.

 

Geoff

**Comment by Captainkirkdawson** [comment]
All Special Chapman Codes including UNK can now have Place Names assigned to them where required. 
POB with a hyphen will be valid for these Chapman Codes as well.
Warnings will be generated if there is no Place Name for POB on these codes 
Please note this has no impact on Cen Search Results
Deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk
All looks OK now
Geoff
