### ISSUE TITLE
Report generator

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#93]
Economic 2, Urgency 6, strategic 8, Cost 5: Priority = 21

**Comment by Captainkirkdawson** [comment]
I know of no easy way of having general purpose report writers for our apps. Would this be for internal management or researchers? If the latter we are really talking about the development of an api.

**Comment by DeniseColbert** [comment]
@Vino-S to look at systemwide story document

**Comment by johnshaw1000** [comment]
Something like this perhaps? https://docs.mongodb.com/bi-connector/current/

**Comment by DeniseColbert** [comment]
Story on Systemwide: https://github.com/freeukgen/systemwide/issues/158
Doc: https://docs.google.com/document/d/1LD9zyYV1en5uzx0zP2_QSnMtSEuH3Vz_IQWWqvMEytU/edit

**Comment by AnneV-Learn** [comment]
I have looked at the requirements you posted @DeniseColbert and it seems to me that some of them could be addressed by the new stats that @Captainkirkdawson has developed (or am I missing the point) and some of the others by the new 'Records' functionality that is being looked into (#1191). We could perhaps add a button to the these reports which would allow download to a CSV file. This could then be read into Excel (or another Report writer of choice) by the end user to work up any 'fancy' reports. Additional 'subset' stats reports could be developed to meet the requirements so that the CSV data downloads pretty much match the reporting requirements. 
Looking at the MongoBI possibility (that @johnshaw1000 suggested) it seems to provide the ability to transform SQL queries to MongoDB queries, so that the data can be queried with SQL and then connected to various BI reporting tools e.g. Excel, MySQL Client, Looker, Tableau..... I have no experience of setting this sort of thing up but unless I am mistaken would at the very least involve end users understanding the data structures to get any meaningful data out of any adhoc reports.

**Comment by PatReynolds** [comment]
@DeniseColbert can you take a look at the specification, please? (ask me - Pat -  if not clear)

**Comment by DeniseColbert** [comment]
@AnneV-Learn many thanks for your input here. It would be good for you and I to chat about this outside of scrum, I'll email you to arrange.

**Comment by DeniseColbert** [comment]
@AnneV-Learn and I met today and discussed requirements in more detail. Ready :)

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn Anne has written a csv download action for the sit statistics, on test3

**Comment by PatReynolds** [comment]
@DeniseColbert to review (on test 3)

**Comment by DeniseColbert** [comment]
@Captainkirkdawson to tell @DeniseColbert where to look
