### ISSUE TITLE
Add Alternative Place Names to Search Place Names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#930]

**Comment by geoffj-FUG** [comment]
We have just identified two conditions which will make searching the valid place names file difficult.

If the transcriber has entered a comma or apostrophe in the verbatim place of birth or place of birth column there will not be a match. Can we create an error when this happens please so that we force an edit.

This will eliminate the Bishops Lydeard / Bishop’s Lydeard problem in the places of birth file that you have also identified in the PARMS. It will standardise the entries in the Alternative Place name field in the gazetteer download.

**Comment by Captainkirkdawson** [comment]
Index updated. Search Place Names now looks for alternate place name strings as well as Place Name strings. Deployed to test 3

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG please review

**Comment by geoffj-FUG** [comment]
The feedback I have from Coordinators is that we transcribe as is and use the alternative place names in the master database to gradually reduce the number of warnings.

**Comment by Captainkirkdawson** [comment]
Geoff reports
Secondly if I do a search and do not select a County I am getting the red Warning message. I also get it if I select the blank county. It works OK when I select a county.

We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Had to restructure index.
Fixed now
If the compound text index includes keys **preceding** the text index key, to perform a $text search, the query predicate must include equality match conditions on the preceding keys.
I was using chapman_code : 1 place_names : text; this will not work unless chapman_code is specified.
Solution is to have chapman_code follow the text field

**Comment by geoffj-FUG** [comment]
Works well now. Tested with no county selected, blank county option selected, incorrect county selected and correct county selected. All gave the correct results
