### ISSUE TITLE
Confirm reprocess acts as expected after edits

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#940]
I had the warnings list up for validation. I added a Place to the FreeCEN2 Places file. I then selected Re-process file and got the following message:

 

There is a problem with the file you are attempting to reprocess . Contact a system administrator if you are concerned

 

It is something that validators will do. Downloading and reloading a file to update it is not as user friendly as it could be. Is there a way that we can run this during validation – just updating the list?

 

Validators will be looking for the ability to reprocess the file during validation simply to refresh their Warnings list.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Propose to have the reprocess rewrite the physical file from the current entries (which is what the download does) and then process that file. Will add a transcriber lock to ensure future upload is blocked until a download is undertaken.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Before completing this story I need to know who and under what circumstance the reprocess task is to be used.
By all ? ie transcribers, proofreaders, validators, coordinators or by a restricted group? eg validator and coordinator?

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Reprocess handles both locked and unlocked files. Reprocesses the records on the system and writes a file that can be downloaded. On test3
Currently limited to validator, coordinators data managers and systems administrators pending on feedback from @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Kirk

 

I think we will limit re-process to the validator, coordinator and data manager.

 

The transcriber and proofreader work on the spreadsheet and upload it to test. That is a simple concept and is understandable by those with limited IT knowledge. We should keep to the kiss principle as far as possible.

 

The validator, coordinator and data manager will all work online. They are the ones who require the ability to reprocess online.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Yes, add system admin to my previous list of those who can re-process.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk
The need to refresh the report is caused by online edit(s).
At the moment I see the principal circumstance being during validation.  The validator will need to Refresh the report to update their Warnings list and to ensure that they have not edited something and caused a new Warning on a different record (I can't think of an example but mice and men do cross paths sometimes!)..
The Coordinator may want to physically run this Refresh prior to Publishing the piece on FreeCEN2. It is softer than a Re-Process which creates a physical report. Alternatively it could happen automatically during Publication as a safety check.
Another circumstance is that a Coordinator may edit a file due to a data report by a researcher. Refreshing the report would ensure that no Warnings have been created due to the online edit. This implies that the True against previous warnings is set as it is during validation. This can be done on download of a published piece from FreeCEN2 to CSVProc (i.e. set all Accepted to True because that was how it was when it was published). Alternatively I assume that True was saved in the CSVProc copy of the published file and that is the one that would be edited and then FreeCEN2 updated.
Transcribers and Proofreaders who edit something online should be forced to download the file because their principal medium for working is the spreadsheet. This stops them creating 2 different copies, one online and one spreadsheet.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG The reprocess currently produced a report for the owner of the file. It might be a little tricky to stop the report production since CSV Proc does not know why it is processing the file. An original upload, a replace, creating a copy for a Proofreader/validator or a reprocess
Apart from that it meets the requirement.

**Comment by geoffj-FUG** [comment]
Kirk

 

I can live with that. 

 

Some validators may find it useful to print out their validation list from their email.

 

This goes hand in hand with #934 so the two together will be a big part of validation.

 

Once these are done and also #925 I believe that we will have broken the back of getting CSVProc up and running.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Reprocess is operational then on test3

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I will test over the next couple of days

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Rep[rocess is working OK. I made a change and locked the file. It works fine.

 

Query – I have Reprocess in my menu as a Coordinator. Is there a menu item for a validator? A validator may only have a Transcriber / Proofreader menu set.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Action is available to validator  ('county_coordinator', 'country_coordinator', 'system_administrator', 'data_manager', 'validator')
