### ISSUE TITLE
Place names displayed misleadingly

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#98]
Mike S searched for the following record:

DoB=1849
PoB=CON Lostwithiel
Surname=Stephens
Forename=William
Census=1861

"F1 finds "Where Born" as "Cornwall - Lostwithiel" [cprrect] and Census Place as "Lostwithiel" [correct].  
F2 finds 'Location' as "Bodmin".  As a general user I don't know that Lostwithiel comes under Bodmin and it is not available in teh list of place names.

**Comment by benwbrum** [comment]
In further searches, F2 returns Lostwithiel results as "Powder" and "Lanlivery" and "Kea"

**Comment by dougkdev** [comment]
Please let's wait to test places until the places work is finished.  Birth
places
Regarding this specific error, I don't believe it is an error.
Lostwithiel is not in the list of places in FC1 either. If you look at the
detail page for the result, in both FC1 and FC2 the census

**Comment by dougkdev** [comment]
Sorry, I accidentally hit the send key while I was still typing.  Here's
what I was trying to type when I sent mid-edit:

Please let's wait to test birth places until the birth place work is done
(story #45).  I believe birth places will have a separate search field, so
I will change the label of the current place field to "census place" so
that is clear.

Regarding this specific example, I don't believe it is an error because
Lostwithiel is not in the list of census places in FC1, either.  If we look
at the detail page for the result, in both FC1 and FC2 the census place is
listed as "Bodmin."  That is the census place as specified in the PARMS.DAT
file for the piece this record was transcribed from.  Lostwithiel is the
Civil Parish name.  Both FC1 and FC2 list the civil parish as Lostwithiel
and the census place as Bodmin on the detail (dwelling) page.

It looks like the confusion is probably because on FC1 in the list of
results (not the detail page) it lists the Civil Parish name, Lostwithiel,
instead of the census place, Bodmin, under the column heading "Census
Place."  In FC2, we list the actual Census place, however, the column
heading is "Location."  I will change that to "Census Place" to avoid
ambiguity.  We could certainly also add the civil parish or whatever else
is wanted to the list of results, it is just a matter of deciding which
fields are necessary/useful in the list versus which would clutter the
display without adding much value.

The further results "Powder" and "Lanlivery" and "Kea":  I am not sure what
the additional search was for those results, so I'm not sure what I should
investigate there.
